### ISSUE TITLE
Custom marker image very slow performance

### ISSUE THREAD

**Issue by minotaurrr** [react-community/react-native-maps#2082] opened 2018-03-11 14:18 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz"
  }
```
### Steps to Reproduce

Markers with default Google Maps marker image show up very quickly, no issues at all.

But when I use a custom image (size is 1kb) it struggles to render.

### Expected Behavior

For markers to show up quickly.

### Actual Behavior

Markers take too long to show up. For about 200+ markers, it takes around 10-20 seconds.

### Reproducible Demo

App.js
```
import React from 'react';
import { Dimensions } from 'react-native';
import { MapView } from 'expo';
import Marker from './Marker';
import haversine from 'haversine';

const { width, height } = Dimensions.get('window');
const ASPECT_RATIO = width / height;
const LATITUDE = -37.812365;
const LONGITUDE = 144.962338;
const LATITUDE_DELTA = 0.0222;
const LONGITUDE_DELTA = LATITUDE_DELTA * ASPECT_RATIO;

export default class App extends React.Component {
  constructor() {
    super();
    this.state = {
      region: {
        latitude: LATITUDE,
        longitude: LONGITUDE,
        latitudeDelta: LATITUDE_DELTA,
        longitudeDelta: LONGITUDE_DELTA
      },
      data: [],
      isLoaded: false,
      boundingBox: {
        westLng: 0,
        southLat: 0,
        eastLng: 0,
        northLat: 0
      }
    }
  }

  componentDidMount() {
    this._mounted = true;
  }

  componentWillUnmount() {
    this._mounted = false;
  }

  getData = async (region) => {
    const centre = {
      latitude: region.latitude,
      longitude: region.longitude
    }

    const screenVerticalBoundary = {
      latitude: this.state.boundingBox.northLat,
      longitude: region.longitude
    }

    const distance = haversine(centre, screenVerticalBoundary, {unit: 'meter'});
    const url = `http://test.com`;
    let data = await(await fetch(url)).json();
    this.setState({data: data, isLoaded: true});
  }

  onRegionChangeComplete = (region) => {
    let boundingBox = this.getBoundingBox(region);
    this.setState({boundingBox});
    this.getData(region);
  }

  getBoundingBox = (region) => {
    let boundingBox = {
      westLng: region.longitude - region.longitudeDelta/2, // westLng - min lng
      southLat: region.latitude - region.latitudeDelta/2, // southLat - min lat
      eastLng: region.longitude + region.longitudeDelta/2, // eastLng - max lng
      northLat: region.latitude + region.latitudeDelta/2 // northLat - max lat
    }

    return boundingBox;
  }

  isInBoudingBox(coordinate) {
    if (coordinate.latitude > this.state.boundingBox.southLat && coordinate.latitude < this.state.boundingBox.northLat &&
        coordinate.longitude > this.state.boundingBox.westLng && coordinate.longitude < this.state.boundingBox.eastLng)
    {
      return true;
    }
    
    return false;
  }

  render() {
    return (
      <MapView style={ { flex: 1 } } initialRegion={ this.state.region } onRegionChangeComplete={this.onRegionChangeComplete}>
        {this.state.isLoaded ? this.state.data.map(p =>
          this.isInBoudingBox({ latitude: parseFloat(p.lat), longitude: parseFloat(p.lon) }) ? 
          <Marker key={p.st_marker_id} coordinate={ { latitude: parseFloat(p.lat), longitude: parseFloat(p.lon) } } callout="This is a test" />
          : null)
        : console.log('data does not exist yet')}
      </MapView>
      );
  }
}
```

Marker.js
```
import React from 'react';
import { MapView } from 'expo';
import { View, Text } from 'react-native';
import markerImage from './assets/marker-128.png';

export default class Marker extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            tracksViewChanges: true
        }
    }

    componentWillReceiveProps(nextProps) {
        if (this.props !== nextProps) {
            this.setState(() => ({
                tracksViewChanges: true,
            }));
        }
    }

    componentDidUpdate() { 
        if (this.state.tracksViewChanges) {
            this.setState({
                tracksViewChanges: false
            });
        }
    }

    render() {
        return (
            <MapView.Marker coordinate={ this.props.coordinate } tracksViewChanges={this.state.tracksViewChanges} image={markerImage}>
                <MapView.Callout>
                    <View>
                        <Text>{this.props.callout}</Text>
                    </View>
                </MapView.Callout>
            </MapView.Marker>
        )
    }
}
```

I found a few proposed solutions in the repo (adding key, the tracksViewChanges trick, getting rid of funny `this.setstate`, etc )but none really made any difference.

I am considering using clustering as suggested elsewhere but I would like to try to resolve the issue without having to use it.

Can anyone help please?

**Comment by GonzaloRecioG** [comment] 2018-03-11 17:17
Make sure to set the *tracksViewChanges* prop to false once Markers are rendered. For some reason on iOS if you provide a custom marker (Image, View, Svg etc..) it keeps re-rendering it causing the UI thread to go nuts forever.

For me, following this instructions from @heysailor, solved it:

> The recommended use of tracksViewChanges is to enable when the marker
> is being rendered or animated, then to disable it.
> 
> An example of use of tracksViewChanges would be to set it to false once
> onMapReady has fired. This can be accomplished by toggling a state
> property (e.g. `initialized`), and passing it to the child map markers
> in their `tracksViewChanges` prop. Markers would then render correctly
> on map load; CPU use falls off once the tracking ceases.

You can find the original quote on [the commit he made](https://github.com/hetaoai/react-native-maps/commit/35fa622f9ecbbc30b2d31ae48b3e1e74110f6326).

[This comment](https://github.com/react-community/react-native-maps/issues/369#issuecomment-340334468) from [@davidhellsing](https://github.com/davidhellsing) was pretty helpful too, and points on the same direction.

**Comment by minotaurrr** [comment] 2018-03-11 22:07
@GonzaloRecioG Shouldn't this bit take care of `tracksViewChanges` for all markers?
```
    componentWillReceiveProps(nextProps) {
        if (this.props !== nextProps) {
            this.setState(() => ({
                tracksViewChanges: true,
            }));
        }
    }

    componentDidUpdate() { 
        if (this.state.tracksViewChanges) {
            this.setState({
                tracksViewChanges: false
            });
        }
    }
```

**Comment by minotaurrr** [comment] 2018-03-12 03:30
@GonzaloRecioG I removed above code and put this instead in the MapView class
```
onMapReady = () => {
        this.setState({
            initialised: true
        });
    }
```

Then the Marker class would receive it as a prop like `<Marker tracksViewChanges={!this.state.initialised} />` but this didn't improve performance either.

**Comment by gogogous88** [comment] 2018-05-12 18:07
having the same issue and on ios map:
press one marker but instantly jump to another marker...
<callout> make the map slow in showing the markers.

**Comment by danielgindi** [comment] 2018-09-07 12:39
Actually the behavior on iOS is the normal behavior.
Google designed it to re-render like crazy all the time, as they don't work with actual views for some reason. They just re-render your view in their graphics context.

This should re-render like crazy on Android too - but it doesn't, which is a bug as vanilla Google Maps on Android does re-renders.

There should be simple logic to disable `tracksViewChanges` when it doesn't change anymore, like the many examples posted here.

**Comment by rborn** [comment] 2018-10-12 12:54
Closing as tracksViewChanges works fine now.

**Closed by rborn** 2018-10-12 12:54 UTC

**Comment by aeskafi** [comment] 2018-12-16 08:37
Hey
I think about this problem and I found a good solution for android platform.
you can find in node_module module folder :
in  **AirMapMarker.java at line 288** change the code to a new one :
`if (marker !=null) {
      marker.setIcon(getIcon());
    }`

**Comment by alvelig** [comment] 2018-12-16 23:41
@aeskafi what is the reason for improving performance?

**Comment by aeskafi** [comment] 2018-12-18 09:38
@alvelig In the way that I used, the problem with Java's removal of the previous marker is eliminated.
you can check the **AirMapMarker.java** at line **280 to 288** the function have hilarious bug :)

**Comment by danielgindi** [comment] 2018-12-18 11:21
@aeskafi It's not a bug. It's for updating the marker live, to mimick how it works on iOS.
You do not have to comment out code. All you have to do is set `tracksViewChanges={false}`.
If you are loading an image inside the marker, you could start with `tracksViewChanges={true}`, listen to the load even on your image, and then change it to `false`.

**Comment by Fuasmattn** [comment] 2019-01-22 12:32
@limpygnome If you only want a custom image for your marker you probably can fix the performance issues now using the icon property in the marker component which was added in [ v0.23.0 ](https://github.com/react-native-community/react-native-maps/releases)

Did not help me though since my markers also contain badges. My solution was the following 
`
  componentDidUpdate() {
    const { tracksViewChanges } = this.state;
    if (tracksViewChanges) {
      setTimeout(() => {
        this.setState({
          tracksViewChanges: false,
        });
      }, 100);
    }
  }

  static getDerivedStateFromProps(props: Props, state: State) {
    const { cachedProps } = state;
    if (!_.isEqual(cachedProps, props)) {
      return {
        tracksViewChanges: true,
        cachedProps: props,
      };
    }
    return {
      tracksViewChanges: false,
      cachedProps: props,
    };
  }

render() {
    const { tracksViewChanges } = this.state;
    const { children } = this.props;
    return (
      <MapView.Marker tracksViewChanges={tracksViewChanges} {...this.props}>
        {children}
      </MapView.Marker>
    );
  }`

The timeout however is not very pretty and probably dangerous to use here. But this helped to prevent markers to be initially rendered partially (sometimes). Any ideas why this could happen - without the timeout?

**Comment by sallarahmed** [comment] 2019-10-10 13:42
Image of custom markers is not showing when tracksViewChanges prop is set to false

**Comment by Abramovick** [comment] 2020-03-17 22:42
You need to clear the ```timeout``` to prevent memory leaks

**Comment by lucianoacsilva** [comment] 2020-08-20 14:13
> @Fuasmattn If that's the solution you're going for then you need to clear the `timeout` when un-mounting the component.

Same here, @sallarahmed. Anyone knows how could this be fixed?

**Comment by Abramovick** [comment] 2020-08-20 18:13
I'd be something like the code below with hooks. 
Or if you're using classes then i think you put something of this sort in `componentWillUnmount`. The point is just store the `timerId` somewhere and call `clearTimeout` on it when un-mounting.

```
const [tracksViewChanges, setViewChanges] = setState();

useEffect(() => {
    let timerId;

    if (tracksViewChanges) {
      timerId = setTimeout(() => {
        setState(false);
      }, 100);
    }
    
    return () => {
      clearTimeout(timerId);
    };
})
```

**Comment by lucianoacsilva** [comment] 2020-08-20 18:29
Sorry, @Abramovick . I referred to the wrong issue here. The one which I was refferering was this one:

> Image of custom markers is not showing when tracksViewChanges prop is set to false

Did anyone solve this?

**Comment by altany** [comment] 2021-03-26 11:49
@lucianoacsilva still working on it but I have kind of solved it by adding an onLoad method to the image component that redraw's the marker every time it changes.

**Comment by randomprogramming** [comment] 2021-03-30 11:52
@lucianoacsilva @sallarahmed Make sure that the starting value of your `tracksViewChanges` is TRUE, and set it to FALSE ONLY after the image loads. That was the problem for me.

`const [shouldTrackViewChanges, setShouldTrackViewChanges] = useState(true);`

**Comment by mohity777** [comment] 2021-05-15 21:48
import React, { memo, useEffect, useRef, useState } from 'react';
import {Animated, Dimensions, StyleSheet, View, Text} from 'react-native';
import {Callout, Marker} from 'react-native-maps';

const OUTER_CARD_WIDTH = Dimensions.get('window').width;

const CustomMarker = memo(({index, marker, onMarkerPress, scrollAnimation}) => {

  let inputRange = useRef([
    (index - 1) * OUTER_CARD_WIDTH,
    index * OUTER_CARD_WIDTH,
    (index + 1) * OUTER_CARD_WIDTH,
  ]);
  
  return (
    <Marker
      key={index}
      title={marker.title}
      description={marker.description}
      coordinate={marker.coordinate}
      onPress={e => onMarkerPress(e)}>
      <Animated.View
        style={[
          styles.markerWrap,
          {
            opacity: scrollAnimation.interpolate({
              inputRange: inputRange.current,
              outputRange: [0.5, 1, 0.5],
              extrapolate: 'clamp',
            }),
          },
        ]}>
        <Animated.View
          style={[
            styles.ring,
            {
              transform: [
                {
                  scale: scrollAnimation.interpolate({
                    inputRange: inputRange.current,
                    outputRange: [1, 1.5, 1],
                    extrapolate: 'clamp',
                  }),
                },
              ],
            },
          ]}
        />
        <View style={styles.marker} />
      </Animated.View>
      <Callout tooltip style={{width:160}}>
          <View style={styles.calloutCard}>
            <Text style={styles.name}>{marker.title}</Text>
          </View>
          <View style={styles.triangle} />
      </Callout>
    </Marker>
  );});

const styles = StyleSheet.create({
  markerWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 75,
    height: 75,
  },
  marker: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(130,4,150, 0.9)',
  },
  ring: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: 'rgba(130,4,150, 0.3)',
    position: 'absolute',
    borderWidth: 1,
    borderColor: 'rgba(130,4,150, 0.5)',
  },
  calloutCard: {
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderRadius: 6,
    padding: 5,
    width: 160,
  },
  name: {
    fontSize: 15,
    marginBottom: 2,
    color: 'white',
    textAlign:"center"
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 10,
    borderBottomWidth: 20,
    borderLeftWidth: 10,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'rgba(0,0,0,0.65)',
    borderLeftColor: 'transparent',
    alignSelf: 'center',
    transform: [{rotate: '180deg'}],
    top: -2,
  },
  callout: {},
});

export default CustomMarker;


Can some suggest how is to achieve this in this example because when setting tracksViewChanges={false} , the animation does not work. I want when marker is focused , it scales and becomes more darker in opacity than the other markers. Please help it is laggy

**Comment by zhenguet** [comment] 2022-02-21 08:10
How about a Marker move to over 1000coordinates as [my problem](https://stackoverflow.com/questions/71124554/how-to-optimise-react-native-maps-performance) @@

**Comment by Ajmal0197** [comment] 2022-10-08 04:47
My solution:

```
  const onRegionChangeComplete = param => {
    console.log('onRegionChangeComplete', param);
    if (parseInt(param?.latitudeDelta + '') < 1) {
      settrackViewChanges(true);
      setRegionChange(param);
    }
  };
  useEffect(() => {
    if (regionChange) {
      console.log('onRegionChangeComplete1', regionChange);
      settrackViewChanges(false);
      markerRef?.current?.redraw();
    }
  }, [regionChange]);

```
