### ISSUE TITLE
Custom Tile URL blank

### ISSUE THREAD

**Issue by wregis** [react-community/react-native-maps#1269] opened 2017-04-24 15:12 UTC
If I don't put an `com.google.android.geo.API_KEY` metadata on the `android/app/src/main/AndroidManifest.xml` file I receive an error message even if using a custom tile URL:

```
<MapView
    style={styles.map}
    initialRegion={{
        latitude: -14,
        longitude: -51,
        latitudeDelta: 0.9,
        longitudeDelta: 0.5,
    }}>
    <MapView.UrlTile
        urlTemplate="https://c.tile.openstreetmap.org/{z}/{x}/{y}.png" />
</MapView>
```

In order no get this to work, I put this:

`<meta-data android:name="com.google.android.geo.API_KEY" android:value="API_KEY"/>`

Even after that the map is just the google logo placed at bottom-left of a gray background.

Is there a way to get rid of this google logo and show my custom tile only?

**Comment by CandyOgre** [comment] 2017-04-26 09:14
@wregis You need to put your Google API Key here: `android:value="API_KEY"`, instead of `API_KEY`

**Comment by wregis** [comment] 2017-04-26 14:13
As I said, I did put, however, I do not have plans on using Google Maps as tile provider. So I'd like to skip this.

**Comment by wregis** [comment] 2017-04-27 02:04
Looks like this issue is a duplicate of #773

**Comment by anujsinghwd** [comment] 2017-08-24 05:13
Not Loading in android .
[https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js](url)

**Comment by alvelig** [comment] 2017-12-13 19:12
Duplicate of #773

**Closed by alvelig** 2017-12-13 19:12 UTC

**Comment by pawan8525** [comment] 2018-09-21 21:00
@alvelig @wregis  hi i am using below url of soil map tile
<MapView.UrlTile
        urlTemplate="https://c.tile.openstreetmap.org/{z}/{x}/{y}.png" />

in x,y i pass  converted lat long and in z i pass zoom level.
But my map overlay tile repeat, why i don't know?
Please help
