### ISSUE TITLE
[Discussion] Issue triaging process

### ISSUE THREAD

**Issue by alvelig** [react-community/react-native-maps#1883] opened 2017-12-14 15:11 UTC
Opening discussion to define the issue lifecycle and rules.

@rborn @christopherdro @zavadpe @satori-ytolstoguzov @kytwb Mention other people if you know they would help.

**Comment by alvelig** [comment] 2017-12-14 15:11
@calvinmikael

**Comment by rborn** [comment] 2017-12-14 15:17
I'd start with this:

- new issues has to follow the new template. If not they should be warned that if not updated it will be closed, label id with "no template",  wait for some time and then look at at or close it if not compliant
- old issues could be closed if they are really old or don't have activity for the last 3 months maybe? If there are comments we should re-open if needed. The closing message should say we're trying to clean this up so we're clear why we're doing this
- for new PRs we might have to make a template too and do the same as above
- for old PRs we should look on those that have no conflict and maybe merge them if they're ok/valuable

my 2c 😊

**Comment by christopherdro** [comment] 2017-12-14 15:37
Yea I think it's safe to start closing out tickets that are really old.
We can start by searching for issues with no comments and close out all the ones created in 2016. https://github.com/react-community/react-native-maps/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+comments%3A0

Just leave a small comment before closing letting requesting them to open the issue back up if the issue is still relevant today.

**Comment by calvinmikael** [comment] 2017-12-14 21:31
I think PR and Issue templates, along with closing old issues (while extending an olive branch for further discussion if the submitter is still being impacted) and merging old PRs if they're relevant is a good place to start.

**Comment by alvelig** [comment] 2017-12-14 21:33
Yep, I agree. Close but don't lock.

**Closed** 2018-01-18 04:54 UTC
