### ISSUE TITLE
Custom callouts and markers not working correctly

### ISSUE THREAD

**Issue by nazywamsiepawel** [react-community/react-native-maps#553] opened 2016-09-08 14:42 UTC
Hey all,

After upgrading to RN 0.32.0 and react-native-maps 0.8.0 weird things started happening with maps in my app. At first, I have experienced the callout cut-off issue (#427) which is "workaroundable". What puzzles me now is the issues that came after :

<img width="320" alt="screen shot 2016-09-08 at 15 34 15" src="https://cloud.githubusercontent.com/assets/334875/18353455/eef5197a-75d9-11e6-9f92-d00a314b6f01.png">
1. In order to trigger the callout I need to click a little bit over the custom marker (which in this case is the red square). Clicking on the red square itself doesn't do anything in this regard apart from triggering onSelect and onPress (callout should show at this point as well!).
2. After clicking a little bit over the marker the callout seems to show but under other markers. How to position it back on the top? It worked correctly in the previous versions.

Supplementary snippet :

```
 <MapView.Marker
            coordinate={marker.loc}
            onSelect={() => alert("test")}
            onPress={() => alert("test")}
          >
            <View style={{height:20, width:20, backgroundColor:'red'}} />
            <MapView.Callout tooltip={false}>
              <BCClickableCallout title={marker.title} bar={marker.bar} onSelected={() => { alert("go places")  </MapView.Callout>
          </MapView.Marker>
```

What happened in the new version that broke it all? Is it me doing something wrong or is it a bug?

**Comment by latimesmike** [comment] 2016-09-08 21:57
I'm also having the same problem, here is the code I'm using to test out the events:

```
import React, { Component } from 'react';
import MapView from 'react-native-maps';
import {
  StyleSheet,
  View,
} from 'react-native';

var styles = StyleSheet.create({
    container: {
    	backgroundColor: '#003D40',
    	flex: 1,
    	marginTop: 65
    },
    map: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
      },
})
class Main extends React.Component{
	constructor(props) {
		super(props);
		this.state = {
			region: {
		      latitude: 37.78825,
		      longitude: -122.4324,
		      latitudeDelta: 0.0922,
		      longitudeDelta: 0.0421,
		    }
		}
	}
	onRegionChange(region) {
	  this.setState({
	  	region: region
	  });
	}
	render() {
		return (
			<View style={styles.container}>
				<MapView.Animated
				      region={this.state.region}
				      onRegionChange={this.onRegionChange.bind(this)}
				      style={ styles.map }				 	  
				 >
				 	<MapView.Marker 
				 	      coordinate={this.state.region}
		 	      	 	  draggable
		 	       	      onSelect={() => console.log('onSelect', arguments)}
		 	       	      onDrag={() => console.log('onDrag', arguments)}
		 	       	      onDragStart={() => console.log('onDragStart', arguments)}
				 		
				 	  />
				 </MapView.Animated>
        	</View>
        )
	}
}
module.exports = Main;

```

(Running react-native 0.32)

Any help would be appreciated!

**Comment by nillo** [comment] 2016-09-17 22:47
I also have this problem, but it started with 0.28.0, it is exactly as describe above, but something changed between 27 and upwards, but i wasn't able to find the issue.

**Comment by ubatin** [comment] 2016-09-21 04:43
I'm have the same issues. On react-native 0.33.0 and react-native-maps 0.8.2

**Comment by nillo** [comment] 2016-09-22 17:55
I was able to fix this, by editing mapCallout.js within the react-native-maps package
```
import React, { PropTypes } from 'react';
import {
  View,
  requireNativeComponent,
  StyleSheet,
} from 'react-native';

const propTypes = {
  ...View.propTypes,
  tooltip: PropTypes.bool,
  onPress: PropTypes.func,
};

const defaultProps = {
  tooltip: false,
};

class MapCallout extends React.Component {
  render() {
    console.log(this.props.style)
    return <AIRMapCallout {...this.props} style={[styles.callout, this.props.style]} />;
  }
}

MapCallout.propTypes = propTypes;
MapCallout.defaultProps = defaultProps;

const styles = StyleSheet.create({
  callout: {
    position: 'relative', 
  },
});

const AIRMapCallout = requireNativeComponent('AIRMapCallout', MapCallout);

module.exports = MapCallout;

```

by changing the callout style to position relative. 
u could pass is as a prop.style, but i just changed it directly and the behaviour was normal again. "normal as in , as it worked before"

hope this helps someone

**Comment by christopherdro** [comment] 2016-10-16 05:11
@ryanhoer @nazywamsiepawel @nillo 

Can you confirm again that this is still working?

@ryanhoer Looks like you have a forked branch with that fix. Mind making a quick pull request?

**Comment by nillo** [comment] 2016-10-16 19:40
@christopherdro, i have just upgraded to 0.35.0, and it still works.

**Comment by christopherdro** [comment] 2016-10-16 19:45
@nillo that's great! Would you be able to submit a pull request with that small change and reference this ticket?

Thanks!

**Comment by magrinj** [comment] 2016-11-17 14:26
@christopherdro @nillo I just try the solution by changing 'absolute' position to 'relative' and doesn't seem to work for me, all the pin move in a wrong position on the map

**Comment by esutton** [comment] 2016-12-07 17:14
Fixed for me on iOS.  After update from 0.11 to **0.12.1** callouts no longer display behind markers

**Comment by gilbox** [comment] 2016-12-07 23:15
that's great, thanks for the report!

**Comment by magrinj** [comment] 2016-12-08 08:18
The problem still happened for me with the version 0.12.1 with custom markers and callouts.

**Comment by i8wu** [comment] 2017-02-15 00:44
Still having this issue with RN0.39 and maps 0.12.4

```<MapView.Marker
				ref={(MarkRef) => {
					// logger.log("MARKER: " + selectedResult.title);
					if (MarkRef != null) {
						// MarkRef.showCallout();
					}
				}}
				coordinate={{
					latitude: selectedResult.mkrLat,
					longitude: selectedResult.mkrLong
				}}
				title={selectedResult.title}
				description={selectedResult.description}
				identifier={selectedResult.title}
				key={selectedResult.title}
			>
				<MapView.Callout style={{ width: 100 }} >
					<TouchableHighlight underlayColor={'rgba(200,200,200,.1)'} onPress={() => gotoNavigationApp(selectedResult.mkrLat, selectedResult.mkrLong)}>
						<View style={{ flex: 1, alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap' }}>
							<Text style={{ flex: 0.8 }}>{selectedResult.title}</Text>
							<Icon style={{ flex:0.2 }} name={'location-arrow'} size={20} />
						</View>
					</TouchableHighlight>
				</MapView.Callout>
			</MapView.Marker>
			) : (null)}```

**Comment by i8wu** [comment] 2017-02-16 20:26
Seems like whenever additional markers, besides the initially rendered markers, are added to the mapview. This problem occurs. Which is unfortunate for me because I need to dynamically add markers to my mapview...

**Comment by alvelig** [comment] 2017-12-05 00:16
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 04:56
Duplicate of #418

**Closed by alvelig** 2017-12-15 04:56 UTC
Labels: bug

**Comment by hungdev** [comment] 2018-03-02 03:20
position, and set size for callout: {
    position: 'relative', 
    height: 100,
    width: 100,
  },
and it worked for me.
