### ISSUE TITLE
Weird dark overlay over the map appears only on Android

### ISSUE THREAD

**Issue by israelidanny** [react-community/react-native-maps#1346] opened 2017-05-19 16:07 UTC
I have a bizarre problem with `react-native-maps` that happens only on Android.

The map seems "darker", like some semi transparent overlay was put over it. The Google logo still looks as bright. Everything works as far as dragging, markers, zooming in/out e.t.c are concerned. 

I don't even know where to start trying to debug this. The same exact code looks fine on iOS. I made sure my app isn't actually showing anything over the map, it definitely comes from within the map (as you can see, the Google logo stays bright)

My `package.json` versions:
```json
"react-native": "^0.43.3",
"react-native-maps": "0.13.1",
```

![darkoverlay](https://cloud.githubusercontent.com/assets/1970424/26256673/66ec29f6-3cc6-11e7-8288-74f90e27e90a.png)

**Comment by israelidanny** [comment] 2017-05-22 17:59
One more detail I was able to notice is that it happens only when I attempt to show the map in a modal view. The same map looks nice and clear anywhere else, but showing it in a modal view makes the dark overlay / opacity thing appear.

**Comment by dfabarbosa** [comment] 2017-06-09 14:56
I have the same problem, and I am also using a modal...

@israelidanny did you manage to find a way to fix this?

**Comment by pfeiffer** [comment] 2017-06-15 08:42
Seeing this as well. Any idea?

**Comment by israelidanny** [comment] 2017-06-16 13:36
No fix found for me yet

**Comment by dabit1** [comment] 2017-06-23 17:31
I'm facing the same issue

**Comment by marcelojmacedo** [comment] 2017-07-02 15:59
Hi, I had the same problem. I changed my styles.xml, adding backgroundDimEnabled to my theme and it worked. I hope it helps anyone that is facing the same problem.

<style name="MyTheme" parent="Theme.AppCompat.Light.NoActionBar">
		<item name="android:backgroundDimEnabled">false</item>
</style>

**Comment by bsonntag** [comment] 2017-07-05 14:19
@marcelojmacedo Didn't work for me. Did you do anything else? What's your `react-native-maps` version?

**Comment by marcelojmacedo** [comment] 2017-07-05 15:00
Hi bsonntag, I don't think this is a problem with your React Native. I have got the same problem using Xamarin Forms. It seems to be something related with the Android Theming api, it fixed my problem just setting this property. android:backgroundDimEnabled

**Comment by bsonntag** [comment] 2017-07-13 11:42
I finally found a fix for this.

I only needed to pass the `transparent={true}` prop to the `<Modal>` containing the map.
I didn't have to change the _styles.xml_  file.

**Comment by omarcarreon** [comment] 2017-07-13 15:12
I fixed it passing`liteMode={true}` prop to `<MapView>`

**Comment by rtman** [comment] 2017-11-05 01:33
I can confirm that `transparent={true}` fixes this for me!

**Comment by alvelig** [comment] 2017-12-16 02:21
Use @tszajna0's workaround. Might not be directly related to the lib.

**Closed by alvelig** 2017-12-16 02:21 UTC

**Comment by Ahsanzz1** [comment] 2019-01-10 07:05
> Hi, I had the same problem. I changed my styles.xml, adding backgroundDimEnabled and setting it to false to my theme and it worked. I hope it helps anyone that is facing the same problem.
> `<style name="MyTheme" parent="Theme.AppCompat.Light.NoActionBar"> <item name="android:backgroundDimEnabled">false</item> </style>`

Did the trick for me.
