### ISSUE TITLE
marker zIndex ignoring other elements zIndex

### ISSUE THREAD

**Issue by blackPeanut** [react-community/react-native-maps#891] opened 2016-12-13 22:38 UTC
Marker zIndex ignoring other elements zIndex, but works when all markers are re rendered.
<img width="117" alt="screen shot 2016-12-13 at 11 39 06 pm" src="https://cloud.githubusercontent.com/assets/12514390/21162393/644034e0-c18d-11e6-970f-b355a4c19eed.png">

**Comment by ngandhy** [comment] 2017-06-14 18:17
This help?
https://github.com/airbnb/react-native-maps/pull/1405

**Comment by alvelig** [comment] 2017-12-05 00:18
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 05:03
Duplicate of #418

**Closed by alvelig** 2017-12-15 05:03 UTC
