### ISSUE TITLE
Custom marker images not showing on Android, working on iOS

### ISSUE THREAD

**Issue by wbattel4607** [react-community/react-native-maps#2083] opened 2018-03-12 00:35 UTC
### Is this a bug report?

Yes (I think)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
```
react-native: 0.53.3,
react: 16.2.0,
react-native-maps: 0.20.1
```
```
macOS High Sierra
iOS 11.2 Simulator (working as desired)
iOS 11.2 Physical Device (working as desired)
Android 7.1.1 Emulator (NOT working as desired)
```

### Steps to Reproduce

See Demo section...

### Expected Behavior

This is how it should work, as seen on iOS. Each user marker displays their picture.
<img width="373" alt="screen shot 2018-03-11 at 7 22 14 pm" src="https://user-images.githubusercontent.com/13490339/37260489-c3cfc6ee-2561-11e8-820c-eeb469e677be.png">

### Actual Behavior

This is what happens on Android. The markers do not show the images (I confirmed they are loading correctly, just not being displayed)
<img width="267" alt="screen shot 2018-03-11 at 7 23 48 pm" src="https://user-images.githubusercontent.com/13490339/37260492-cca41694-2561-11e8-8780-0edc8d9fe1a2.png">

They are also anchored differently for some reason, though that is less important.

### Reproducible Demo

I've been unable to get a demo working. I've tried to get a snack.expo.io demo working for about an hour and I can't get the dependency to resolve correctly.

<img width="262" alt="screen shot 2018-03-11 at 7 26 48 pm" src="https://user-images.githubusercontent.com/13490339/37260526-318cc3da-2562-11e8-8a92-a1b60d9dbbd6.png">

This is the relevant code. Everything is the same for iOS and Android, except that the Markers for iOS are animated.
```
<MapView ref={ref => {this.map = ref;}}
            provider={"google"}
            zoomEnabled={true}
            showsUserLocation={false}
            onPress={Keyboard.dismiss}
            style={styles.container}
            region={this.state.region}
            onRegionChangeComplete={this.onRegionChangeComplete}
            loadingEnabled={false}
            pitchEnabled={false}
            showsCompass={false}
            showsScale={false}
            showsIndoors={false}
            showsIndoorLevelPicker={false}
            customMapStyle={config.map.style}>
    {this.props.users.map((user) => {
        if (user && user.id && user.location) {

            let imageBorder = '#34ADFF';

            if (Platform.OS === 'ios') {
                return (
                    <Marker
                        //{...user}
                        key={user.id}
                        onLoad={() => this.forceUpdate()}
                        coordinate={(user.location) ? user.location.coordinates : user.coordinate}
                        anchor={{x: 0.5, y: 0.5}}
                        zIndex={4}
                        onPress={() => this.goToProfile(user)}>
                        <Animatable.View animation="bounceIn" style={{width: 62, height: 62}}>
                            <View style={[styles.borderStyle, {borderColor: imageBorder, borderRadius: 50}]}>
                                <Image
                                    style={styles.imageStyle}
                                    source={{uri: user.image, width: 50, height: 50}}>
                                </Image>
                            </View>
                        </Animatable.View>
                    </Marker>
                );
            }
            else {
                return (
                    <Marker
                        //{...user} if I uncomment this, the picture will show but will be full size and not inside the marker
                        key={user.id}
                        onLoad={() => this.forceUpdate()}
                        coordinate={(user.location) ? user.location.coordinates : user.coordinate}
                        anchor={{x: 0.5, y: 0.5}}
                        zIndex={4}
                        onPress={() => this.goToProfile(user)}>
                        <View style={{width: 62, height: 62}}>
                            <View style={[styles.borderStyle, {borderColor: imageBorder, borderRadius: 50}]}>
                                <Image
                                    style={styles.imageStyle}
                                    source={{uri: user.image, width: 50, height: 50}}>
                                </Image>
                            </View>
                        </View>
                    </Marker>
                );
            }
        }
    })}
</MapView>
```

If I uncomment the `{...user}` in the `<Marker>`, this happens.

<img width="267" alt="screen shot 2018-03-11 at 7 34 31 pm" src="https://user-images.githubusercontent.com/13490339/37260598-42e93f40-2563-11e8-9cf5-589d5e9eb19c.png">

I'm happy to provide more information if necessary, but I'm not sure what else would be helpful.

**Comment by alvelig** [comment] 2018-03-12 01:18
Your user object has image prop with uri, that is a valid prop for the marker. That's why they appear full size.

As for that they don't appear that is duplicate of #1870

**Closed by alvelig** 2018-03-12 01:18 UTC

**Comment by hariomsharma-jmd** [comment] 2019-02-14 14:36
Custom markers are showing semi transparent only on android and on ios these are showing perfectly. 
![screenshot_2019-02-14-20-03-53-600_com entrepreneur](https://user-images.githubusercontent.com/10772719/52793552-fdecef80-3093-11e9-8141-c96472762335.png)

Any Help? please

**Comment by akhilsanker** [comment] 2019-02-26 10:43
Hi @hariomsharma-jmd ,

Did you found any workaround for this? Iam facing this issue.
Could you please suggest any workaround?

Thanks

**Comment by pravinjohn** [comment] 2019-05-20 12:05
This solved for me on android.
using react-native-fast-image, onLoad triggers after fetching the image, call marker.redraw() in it.

**Comment by SintoAntony** [comment] 2019-07-18 13:15
could you please set a timer with 500 before redrawing the marker

**Comment by abhideepmallick** [comment] 2019-07-26 12:21
Here is a hack that works: https://github.com/react-native-community/react-native-maps/issues/2734#issuecomment-515428771
