### ISSUE TITLE
Custom Map Tile is not loading in android

### ISSUE THREAD

**Issue by anujsinghwd** [react-community/react-native-maps#1590] opened 2017-08-24 06:01 UTC
>If I don't put an com.google.android.geo.API_KEY
>**I want to use mapmyindia as tile provider not google**
>I am using this code but it's not working in android
[https://github.com/airbnb/react-native-maps/blob/master/example/examples/CustomTiles.js](url)

**Comment by alvelig** [comment] 2017-12-15 23:21
Duplicate of #773

**Closed by alvelig** 2017-12-15 23:21 UTC
