### ISSUE TITLE
Image marker overlays other image markers on iOS

### ISSUE THREAD

**Issue by alizahid** [react-community/react-native-maps#1393] opened 2017-06-08 00:03 UTC
Check out the screenshots below.

![img_3662](https://user-images.githubusercontent.com/941775/26906525-5440d6d0-4c07-11e7-9f8d-325a261d07e6.PNG)
![img_3663](https://user-images.githubusercontent.com/941775/26906526-5448a748-4c07-11e7-8275-35537c184acf.PNG)

Doesn't happen on Android, and doesn't happen with the default pins either.

My images are in asset catalogs for iOS and in drawables for Android, if that makes any difference (I tried `import`ing, too; didn't matter.)

**Comment by vinagrito** [comment] 2017-07-16 06:13
Following this

**Comment by alvelig** [comment] 2017-12-05 00:15
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 04:51
Duplicate of #418

**Closed by alvelig** 2017-12-15 04:52 UTC
