### ISSUE TITLE
Multiple markers using react-native-maps hangs and stuck navigation. Any fix???

### ISSUE THREAD

**Issue by hamidmustafa** [react-community/react-native-maps#854] opened 2016-12-02 14:32 UTC

**Comment by hamidmustafa** [comment] 2016-12-02 14:38
this is how my code is. its perfect. But screen gets stuck when i click button "Details" , which is inserted in marker pop up, to move to next screen. I am drawing approx more  300 markers on map . 
render() {
    return  (
      <View style={{ flex:1}}>
      <View style={{ flex:0.8}}>
      <MapView
          style = {styles.map}
          provider = {this.props.provider}
          showsUserLocation = {true}
          region = {{
            latitude:this.state.position.coords.latitude,
            longitude:this.state.position.coords.longitude ,
            latitudeDelta: 90,
            longitudeDelta: 90,}}>{
            this.state.marker.map((marker,index) => (
      <MapView.Marker
           key = {index}
           coordinate = {{latitude: marker.Latitude_Saloon_,
              latitudeDelta:0.015,
              longitude:marker.Longitude_Saloon_,
              longitudeDelta:0.0121,}}
           title = {marker.SaloonNames_}
           description = {marker.SaloonAddress_ }>

      <MapView.Callout
            tooltip={true}  style={{width:250,height:150}}>
                <CustomCallout>
                <Text>{marker.SaloonNames_}
                </Text>
                <Button
                  style={{backgroundColor: 'white',fontSize: 20, color: 'black'}}
                  styleDisabled={{color: 'red'}}
                  onPress={()=>this.onButtonClick()}>
                  Details
                </Button>
                </CustomCallout>
      </MapView.Callout>

      </MapView.Marker>))}
      <MapView.Marker
          coordinate = {{latitude:this.state.position.coords.latitude,
            latitudeDelta:0.015,
            longitude:this.state.position.coords.longitude ,
            longitudeDelta:0.0121,}}
          title={'Current Location'}
          description={'This is your current location'}>
     </MapView.Marker>
     </MapView>
     </View>
     </View> );
             }


// here is my OnButtonClick method.
onButtonClick = () => {
      console.log('you clicked Details button');
      console.log(this.props.navigator);
      nav.push({
        id: 'details_map',
        title:'details',
                });       }

**Comment by proProbe** [comment] 2017-01-19 22:12
I seem to have a similar problem. anyone who has seen this and knows the solution?

**Comment by zvoncha** [comment] 2017-01-30 10:05
Try to hide map markers before executing new view/popup for details...After user close details popup show markers again.

**Comment by alvelig** [comment] 2017-12-14 04:39
Duplicate of #369

**Closed by alvelig** 2017-12-14 04:39 UTC
