### ISSUE TITLE
[ios] markers with custom images that are far away still show in viewport top left corner

### ISSUE THREAD

**Issue by grigored** [react-community/react-native-maps#1588] opened 2017-08-23 18:31 UTC
I get the marker url async, so I render markers after the map has loaded. Even markers that should not be in the viewport still show up in the top left corner, as in the image. Here is a sample code to reproduce the problem. My current workaround is to increase the map height by 50, and then add marginTop: -50, so that the markers are hidden. Is there a solid fix? 
![b2pvczs3ev](https://user-images.githubusercontent.com/12827406/29632075-6f790024-884a-11e7-89f4-b57cb358a6c6.gif)
```
export default class AwesomeProject extends Component {
  constructor() {
    super();
    this.state = {
      markers: []
    }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({
        markers: [{
          latlng: {
            latitude: 20,
            longitude: -120,
          },
          id: 1
        }]
      })
    }, 100);

  }

  render() {
    return (
      <MapView
        style={{width: '100%', height: 500}}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      >
        {this.state.markers.map(marker => (
          <MapView.Marker
            key={marker.id}
            coordinate={marker.latlng}
            image="https://cdn3.iconfinder.com/data/icons/flat-icons-small-version/64/location-pin-512.png"
          />
        ))}
      </MapView>
    );
  }
}
```

**Comment by zhantx** [comment] 2017-09-05 01:28
might be a duplicate of #678

**Comment by alvelig** [comment] 2017-12-12 03:19
duplicate of #678

**Closed by alvelig** 2017-12-12 03:19 UTC
