### ISSUE TITLE
showCallout MapView.Callout

### ISSUE THREAD

**Issue by pauwlsky** [react-community/react-native-maps#822] opened 2016-11-23 22:33 UTC
Hello, 

thank you again for all the work you guys are doing, this module has still been working out great on our project 👍 

I was hoping someone might be able to help me with a needed fix, which involves showing a custom callout when the markers props update, right now it seems there is only a way to show the default MapView.Marker callout using `showCallout`.  I am currently doing this by using a ref with the target marker. 

Not sure if this is possible or if it may be added as a feature in the future, any information is much appreciated.

**Comment by SamiPussinen** [comment] 2016-11-24 12:35
+1

I think this would be the more 'correct' way to open the callout.

**Comment by pauwlsky** [comment] 2016-11-28 18:36
If there is not a way to do this, does anyone know if it's possible to style text in the default callout? I'm going to be investigating today and will re-post today with any updates.

**Comment by i8wu** [comment] 2017-02-18 01:50
@pauwlsky did you ever get anything working?

**Comment by pauwlsky** [comment] 2017-02-19 16:23
Hey @i8wu, unfortunately I did not. I would like to go back and see if there was any option for this. For now we had to use default callouts and abandon our custom styled ones on the project.

**Comment by alvelig** [comment] 2017-12-12 04:00
Duplicate of #275

**Closed by alvelig** 2017-12-12 04:00 UTC
