### ISSUE TITLE
Animated Polyline

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-native-maps#1697] opened 2017-10-11 18:41 UTC
I'm currently trying to make a run tracker essentially, I already have my marker animating along the course now I just need my polyline to follow the runner along the same course. The only way I've been able to do it now is by rendering multiple times a second to update the line on the map, but that is causing some performance issues.

Is there a way to update the polyline without triggering a render?

**Comment by rishabhmathur1693** [comment] 2018-03-12 07:38
Does anyone have a solution for this thing? I also need to implement this thing in my project and I haven't found anything anything in the document regarding Polyline animation.

**Comment by rborn** [comment] 2018-03-12 10:36
Closing as duplicate of #1566

**Closed by rborn** 2018-03-12 10:36 UTC
