### ISSUE TITLE
get all markers in range

### ISSUE THREAD

**Issue by joaoalbertocsjunior** [react-community/react-native-maps#1980] opened 2018-01-21 07:04 UTC
I have a Circle, i want to get all markers in radius. How to accomplish that?

**Comment by alvelig** [comment] 2018-01-21 18:41
Duplicate of #1919

**Comment by alvelig** [comment] 2018-01-21 18:41
You need to use geospatial calculation libraries. Unfortunately there's no standard way to do it in this library

**Closed by alvelig** 2018-01-21 18:41 UTC
Labels: question
