### ISSUE TITLE
Show callout as default

### ISSUE THREAD

**Issue by neilakoh** [react-community/react-native-maps#1041] opened 2017-02-15 02:10 UTC
I am not sure if this is really an issue or a guide that I missed out or something not implemented yet. I am trying to set the **callout** visible always specially on component render.  I can not find any function or parameter that handles this feature. Is this possible in the current release? Thanks

**Comment by viktorsec** [comment] 2017-04-04 11:13
I do this:

```javascript
setMarkerRef = (ref) => {
  this.marker = ref
}
…

<MapView
  …
  onRegionChangeComplete={null /*() => this.marker.showCallout()*/}
>
  <MapView.Marker
    …
    ref={this.setMarkerRef}
  />
</MapView>
```

However I am looking for a more clean solution.

**Comment by samcorcos** [comment] 2017-04-15 02:17
@viktorsec You can set the marker ref in the same line if you want, which reduces some of the code:

```js
<MapView.Marker
  ...
  ref={marker => (this.marker = marker) />
```

**Comment by neilakoh** [comment] 2017-04-19 02:58
Hi, sorry for the late response, I tried both ways; however, it is not working . . When I call `this.marker.showCallout()` it gives me the error saying:

> this.marker.showCallout is not a function

When I tried to `console.log()`  the `this.marker` it gives me these function / props.

![callout](https://cloud.githubusercontent.com/assets/15863359/25161500/dfd20e16-24ee-11e7-9b9c-38b0201fc930.png)

You see there is a MapCallout type as function, I am not sure if that is the one that needs to be triggered. Please advise thank you.

**Comment by frozenxis** [comment] 2017-05-25 01:02
@viktorsec , i would recommend setting a flag for showCallout because i get some weird flickering because of the continuous bubble rendering on map scroll.

>renderCallout() {
        if(this.state.calloutIsRendered === true) return;
        this.setState({calloutIsRendered: true});
        this.marker.showCallout();
    }

><MapView
                        initialRegion={region}
                        onRegionChangeComplete={() => this.renderCallout()}
                    >
                        <MapView.Marker
                            ref={marker => (this.marker = marker)}
...

**Comment by alvelig** [comment] 2017-12-12 03:56
Duplicate of #275

**Closed by alvelig** 2017-12-12 03:56 UTC

**Comment by stevematdavies** [comment] 2019-12-11 15:56
How can this be achieved using the React.UseRef() hook

**Comment by danlupascu** [comment] 2020-01-09 00:18
@stevematdavies

```javascript
import React, {useRef} from 'react';
import MapView from 'react-native-maps';

export default props => {
  const markerRef = useRef(null);

  const onRegionChangeComplete = () => {
    if (markerRef && markerRef.current && markerRef.current.showCallout) {
      markerRef.current.showCallout();
    }
  };

  return (
      <MapView onRegionChangeComplete={onRegionChangeComplete}>
        <MapView.Marker ref={this.markerRef}/>
      </MapView>
  );
};

```

**Comment by aravi365** [comment] 2020-05-27 05:09
> I do this:
> 
> ```js
> setMarkerRef = (ref) => {
>   this.marker = ref
> }
> …
> 
> <MapView
>   …
>   onRegionChangeComplete={() => this.marker.showCallout()}
> >
>   <MapView.Marker
>     …
>     ref={this.setMarkerRef}
>   />
> </MapView>
> ```
> 
> However I am looking for a cleaner solution.

But this opens only one marker callout when implemented.

**Comment by ekifox** [comment] 2021-01-20 00:08
How to open all callouts on the map? Not the only one.

**Comment by gpbaculio** [comment] 2021-03-24 18:59
This is not working unexpectedly, i update redux the region on onRegionComplete so i am sure each marker have individual ref:

```
const NearbyMarker = ({ coords, name, logo }: NearbyMarkerPropsTyps) => {
  const { nearbyRegion } = useSelector(({ explore }: AppStateType) => explore);

  const markerRef = useRef<Marker>(null);

  useEffect(() => {
    if (markerRef && markerRef.current && markerRef.current.showCallout) {
      markerRef.current.showCallout();
    }
  }, [nearbyRegion]);

  const coordinate = {
    latitude: coords[0],
    longitude: coords[1],
  };

  return (
    <Marker {...{ ref: markerRef, coordinate }}>
      <Callout tooltip>
        <MerchantMarkerContainer>
          <MerchantMarkerTitle>{name}</MerchantMarkerTitle>
          {Platform.OS === 'ios' ? (
            <FastImage
              {...{
                style: styles.image,
                source: {
                  uri: `https://s3.us-east-2.amazonaws.com/uploads.ryzecard.com/media/${logo}`,
                  priority: FastImage.priority.normal,
                  cache: FastImage.cacheControl.web,
                  headers: {
                    'Content-Type': 'image/png',
                    Host: 's3.us-east-2.amazonaws.com',
                    Accept: '*/*',
                  },
                },
                resizeMode: FastImage.resizeMode.cover,
              }}
            />
          ) : (
            <WebView
              {...{
                style: styles.image,
                source: {
                  uri: `https://s3.us-east-2.amazonaws.com/uploads.ryzecard.com/media/${logo}`,
                },
              }}
            />
          )}
        </MerchantMarkerContainer>
        <MerchantMarkerArrowBorder />
        <MerchantMarkerArrow />
      </Callout>
    </Marker>
  );
};
```

**Comment by anabeatrizzz** [comment] 2021-06-16 19:37
> How to open all callouts on the map? Not the only one.

@herenickname Did you made it?
