### ISSUE TITLE
Not Perform an Action When I was click on MapView.Callout?

### ISSUE THREAD

**Issue by lavarajallu** [react-community/react-native-maps#1334] opened 2017-05-16 11:54 UTC
I am Developing one appication i have given some Address Detaila in Callout.mapview but not perfoming any action 

This is my Code..
```
<MapView.Callout style={{width:220}} >
                <View style={{ flex: 1, alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap' }}>
                  <View style={{flex:.4}}>
                  <Image source = {{uri:"https://www.medicandhra.com"+marker.DoctorImage}} style={{height:80,width:70,resizeMode:'cover'}}/>
                  </View>
                  <View style={{flex:.6}}>
                  <View style={{flexGrow:1}}>
                    <Text style={{flex:.3}}>Name:{marker.FirstName} {marker.LastName}</Text>
                      <Text style={{flex:.3}}>Qualification:{marker.Qualification}</Text>
                        <Text style={{flex:.3}}>Fee:{marker.ConsultationFee}</Text>
                      <Text style={{flex:.3}}>Speciality:{marker.SpecialityName}</Text>
                      <TouchableOpacity  onPress={this.bookDoctorsAppointment.bind(this, marker)}>

                    <Text style={{flex:.3,color:'#0000ff',borderBottomWidth:1,borderColor:'#000000'}}>Book Appointment</Text>
                    </TouchableOpacity>
                  </View>
                  </View>
                </View>
            </MapView.Callout>


```

Please Suggest me...

**Comment by alvelig** [comment] 2017-12-16 02:28
Duplicate of #135

**Closed by alvelig** 2017-12-16 02:28 UTC
