### ISSUE TITLE
Marker with custom images does not show callout sometimes. Callout appears behind markers.

### ISSUE THREAD

**Issue by knguyen2708** [react-community/react-native-maps#751] opened 2016-10-31 22:05 UTC
I'm trying to use markers with custom images. Out of 3 markers, only one shows callout when I tap on it. And the callout appears behind the other markers.

The same problem occurs if I use my custom markers. It works just fine if I use the default pin marker.

Code

```js
export default class MockMapApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      places: [
        {
          title: 'A',
          latitude: -31.433333,
          longitude: 152.900000,
        },
        {
          title: 'B',
          latitude: -31.428564,
          longitude: 152.912478,
        },
        {
          title: 'C',
          latitude: -31.440208,
          longitude: 152.918615,
        }
      ],
      region: {
        latitude: -31.433333,
        longitude: 152.900000,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }
    };
  }

  render() {
    return (
      <MapView
          style={{flex: 1}}
          region={this.state.region}
          onRegionChangeComplete={region => this.setState({region: region})}>

          {this.state.places.map((place, index) => {
            const coord = {latitude: place.latitude, longitude: place.longitude};

            return (
              <MapView.Marker
                key={index} identifier={`${index}`}
                coordinate={coord}
                image={require('./images/planned-icon.png')}
                onPress={() => console.log(`marker ${place.title} pressed`)}>

                {/* <MyMarkerView identifier={`${index}`} coordinate={coord} title={place.title}/> */}

                <MapView.Callout style={{width: 300, height: 100}}>
                  <MyCalloutView title={place.title}/>
                </MapView.Callout>

              </MapView.Marker>
            );
          })}

        </MapView>
    );
  }
}

/*
class MyMarkerView extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={{
          width: 44, height: 44,
          flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
          backgroundColor: 'transparent'
        }}>
        <View style={{
            width: 20, height: 20, borderRadius: 10,
            justifyContent: 'center', alignItems: 'center',
            backgroundColor: 'red'}}>
          <Text style={{color: 'white'}}>
            {"P"}
          </Text>
        </View>
      </View>
    );
  }
}
*/

class MyCalloutView extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={{backgroundColor: 'white'}}>
        <Text>{this.props.title}</Text>
      </View>
    );
  }
}

MyCalloutView.propTypes = {
  title: React.PropTypes.string.isRequired
}
```

Screenshot

![simulator screen shot 1 nov 2016 9 01 45 am](https://cloud.githubusercontent.com/assets/3516271/19873308/5c309cbe-a012-11e6-8ddb-3419d8b1ffc5.png)

Thanks,

**Comment by twelvearrays** [comment] 2016-11-12 15:52
Any updates on this issue? I am having the same issue. Thanks
![screen shot 2016-11-12 at 9 52 15 am](https://cloud.githubusercontent.com/assets/11466453/20239063/bc94ea02-a8bd-11e6-8f2b-4c838325c9af.png)

**Comment by knguyen2708** [comment] 2016-11-14 02:58
Nope, no one cares about it

**Comment by twelvearrays** [comment] 2016-11-14 14:13
I have noticed that.  I have found 2 other open issues for the same issue. 
https://github.com/airbnb/react-native-maps/issues/662
https://github.com/airbnb/react-native-maps/issues/553

**Comment by nbolender** [comment] 2016-11-14 18:43
I care about it, but I suspect that airbnb does not since their app does not use callouts at all.

I am working around it in my app by creating a component that uses this library on Android and the included react-native maps library on iOS. Of course the capabilities are different, and the iOS maps has its own set of problems (sometimes shows default markers; custom markers are anchored in the center).

I first tried to use Google Maps on iOS, but the documentation for setting that up is really spotty. I guess this is just the nature of react-native libraries at this early stage.

**Comment by magrinj** [comment] 2016-11-22 09:58
Any news on this ? It's been a while and this bug is really annoying, I try to take a look into it, but I can't figure it out for the moment... @lelandrichardson @spikebrehm @felipecsl @gilbox

**Comment by felipecsl** [comment] 2016-11-23 08:00
@magrinj have you retested with 0.11? Sounds like it has been already fixed, as reported on #518

**Comment by magrinj** [comment] 2016-11-23 08:05
@felipecsl Yes I run the 0.11

**Comment by esutton** [comment] 2016-12-07 17:13
Fixed for me on iOS anyway.  After update from 0.11 to **0.12.1**

**Comment by magrinj** [comment] 2016-12-09 08:16
Still the same for me even on 0.12.1

**Comment by bruzenak** [comment] 2016-12-09 17:48
Same, with a fresh install of 0.12.1 and react-native 0.38.

**Comment by RajkumarPunchh** [comment] 2017-01-05 08:01
I encountered the same issue when `fitToElements` was set `true` for the MapView. Removing it fixed the issue for me, but that might not be an acceptable work-around for all.

**Comment by kamiranoff** [comment] 2017-01-06 15:51
Hum...@RajkumarPunchh I tried your code but it didn't work for me. Callouts are still behind the markers

**Comment by spikebrehm** [comment] 2017-01-07 01:32
I tried to reproduce using this code, but I was not able to:

```js
import React, { Component } from 'react';
import {
  StyleSheet,
  View,
  Text,
} from 'react-native';
import MapView from 'react-native-maps';

export default class MockMapApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      places: [
        {
          title: 'A',
          latitude: -31.433333,
          longitude: 152.900000,
        },
        {
          title: 'B',
          latitude: -31.428564,
          longitude: 152.912478,
        },
        {
          title: 'C',
          latitude: -31.440208,
          longitude: 152.918615,
        }
      ],
      region: {
        latitude: -31.433333,
        longitude: 152.900000,
        latitudeDelta: 0.0922,
        longitudeDelta: 0.0421,
      }
    };
  }

  render() {
    return (
      <View style={StyleSheet.absoluteFill}>
        <MapView
          style={{ flex: 1 }}
          region={this.state.region}
          onRegionChangeComplete={region => this.setState({ region })}
        >

          {this.state.places.map((place, index) => {
            const coord = { latitude: place.latitude, longitude: place.longitude };
            return (
              <MapView.Marker
                key={index} identifier={`${index}`}
                coordinate={coord}
                onPress={() => console.log(`marker ${place.title} pressed`)}
              >
                {/* image={require('./images/planned-icon.png')} */}
                <MyMarkerView identifier={`${index}`} coordinate={coord} title={place.title} />

                <MapView.Callout style={{ width: 300, height: 100 }}>
                  <MyCalloutView title={place.title} />
                </MapView.Callout>

              </MapView.Marker>
            );
          })}

        </MapView>
      </View>
    );
  }
}

class MyMarkerView extends React.Component {
  render() {
    return (
      <View
        style={{
          width: 44, height: 44,
          flexDirection: 'row', justifyContent: 'center', alignItems: 'center',
          backgroundColor: 'transparent'
        }}
      >
        <View style={{
            width: 20, height: 20, borderRadius: 10,
            justifyContent: 'center', alignItems: 'center',
            backgroundColor: 'red'}}>
          <Text style={{color: 'white'}}>
            {"P"}
          </Text>
        </View>
      </View>
    );
  }
}

class MyCalloutView extends React.Component {
  render() {
    return (
      <View style={{ backgroundColor: 'white' }}>
        <Text>{this.props.title}</Text>
      </View>
    );
  }
}

MyCalloutView.propTypes = {
  title: React.PropTypes.string.isRequired
};
```

I merged #936 which I hope will fix it for some of you.  Please LMK if that does not fix it.

Releasing a new version now with that change.

**Comment by Awpatterson217** [comment] 2017-03-30 09:26
i have an idea: change the zIndex of map to negative. Like, -1.

**Comment by alvelig** [comment] 2017-12-05 00:16
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 02:32
Might be related to #483

**Comment by alvelig** [comment] 2017-12-15 05:00
Duplicate of #418

**Closed by alvelig** 2017-12-15 05:00 UTC

**Comment by harutyunian** [comment] 2024-07-28 14:14
Any knows ? for me still same? but before this its worked
here is my callout 

```
import React from "react";
import {Text, StyleSheet, TouchableOpacity} from "react-native";
import {Svg, Image as ImageSvg} from "react-native-svg";
import {useAppSelector} from "../../hook/reduxHooks";
import {IUser} from "../../types/event.type";
import {Image} from "expo-image";

interface IMiniProfileProps {
    user: IUser;
}

export default function MiniProfile(props: IMiniProfileProps) {
    const {user} = props;
    const {avatar, partner, address} = user;
    const colors = useAppSelector((state) => state.theme);

    return (
        <TouchableOpacity
            style={[
                miniProfileStyles.container,
                {backgroundColor: colors.ACCENT["6"]},
            ]}
        >
            <Text>
                <Image
                    priority='high'
                    source={{uri: avatar, width: 60, height: 60}}
                />
            </Text>
            <Svg width={60} height={60}>
                <ImageSvg
                    width={"100%"}
                    height={"100%"}
                    preserveAspectRatio="xMidYMid slice"
                    href={{uri: avatar}}
                />
            </Svg>
            <Text style={[miniProfileStyles.title, {color: colors.ACCENT["1"]}]}>
                {partner}
            </Text>
            <Text style={[miniProfileStyles.address]}>{address}</Text>
        </TouchableOpacity>
    );
}

const miniProfileStyles = StyleSheet.create({
    container: {
        width: 160 - 160 * 0.3,
        height: 190 - 190 * 0.3,
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 10,
    },
    avatar: {
        width: 50,
        height: 50,
    },
    address: {
        fontSize: 12,
        fontWeight: "400",
        color: "#64748B",
    },
    avatarText: {
        position: "relative",
        height: 100,
        bottom: 40,
    },
    title: {
        fontSize: 16,
        fontWeight: "500",
    },
});
```
