### ISSUE TITLE
showsMyLocationButton not working

### ISSUE THREAD

**Issue by radiKal07** [react-community/react-native-maps#1812] opened 2017-11-21 15:51 UTC
`<MapView
          style={styles.container}
          showsUserLocation={true}
          showsMyLocationButton={true}
          onRegionChange={region => this.setState({ region })}
          onRegionChangeComplete={region => this.setState({ region })}
        />`
`"react": "16.0.0",
"react-native": "0.50.0",`

Show my location button still not appearing.

**Comment by Stophface** [comment] 2017-11-27 12:16
Did you solve this? Having the same problem.

**Comment by Germanaz0** [comment] 2017-11-28 15:08
I discovered on android device that when you rotate the phone, the button appears, but not in the initial state.

**Comment by aubreywahl** [comment] 2017-12-01 19:15
seeing the same here on iOS

**Comment by vhuytdt** [comment] 2017-12-07 04:49
![image](https://user-images.githubusercontent.com/18238875/33699205-4f3e9e7a-db44-11e7-90f2-c1f12b667ac6.png)
you set Time out in componentWillMount.. and in 
`  <View style={{paddingTop: this.state.statusBarHeight }}>
        <MapView
           ............................
        </MapView>
        </View>`..
because  showMyLocation init after map paint... => not appear

**Comment by richardstephenz** [comment] 2017-12-07 11:52
I also don't see the showsMyLocationButton on iOS:

            <MapView
               style={{flex:1}}
                      region={this.state.mapRegion}
                      showsUserLocation={true}
                      followUserLocation={true}
                      showsMyLocationButton={true}
                      onRegionChange={this.onRegionChange.bind(this)}>
            </MapView>

    "expo": "^22.0.0",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3"

**Comment by vhuytdt** [comment] 2017-12-12 08:06
@richardstephenz  you setTimeOut and style map.. it will show...

**Comment by alvelig** [comment] 2017-12-13 01:54
Duplicate of #1315

**Closed by alvelig** 2017-12-13 01:54 UTC

**Comment by alvelig** [comment] 2017-12-14 04:06
Duplicate of #1033
