### ISSUE TITLE
Button "show my current location" does not show in Android Emulator

### ISSUE THREAD

**Issue by khuongdv** [react-community/react-native-maps#2408] opened 2018-08-01 00:11 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, read it and followed it

### Environment
    react-native: 0.54.0
    react: 16.3.0-alpha.1
    react-native-maps: 0.21.0

Target Platforms:
- Genymotion Emulator: Samsung Galaxy S8 API 24
- iOS Simulator iPhone 6

### Steps to Reproduce

1. Create a brand new RN project using `react-native init --version="0.54.0" NAME`
2. Install react-native-maps, follow the instruction
Edit App.js as follow:
```
// import...
const {width, height} = Dimensions.get('window')
const ASPECT_RATIO = width / height;
...
render() {
    return (
      <MapView
        style={styles.map}
        showsUserLocation={true}
        provider={MapView.PROVIDER_GOOGLE}
        showsMyLocationButton={true}
        initialRegion={{
          latitude: 20.9833562,
          longitude: 105.850101,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0922 * ASPECT_RATIO,
        }}
      >
      </MapView>
    );
  }
```
3. Run react-native run-ios to view it in ios simulator, run react-native run-android to see it in Genymotion emulator
### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

The button to show current location only displays in iOS simulator, not android, even I tried many times.

(Write what happened. Add screenshots!)

### Reproducible Demo

<img width="1680" alt="screen shot 2018-08-01 at 7 01 29 am" src="https://user-images.githubusercontent.com/7438397/43493777-e7837438-9559-11e8-9369-930d6847273d.png">

**Comment by ntelkedzhiev** [comment] 2018-08-08 10:37
Duplicate of https://github.com/react-community/react-native-maps/issues/2010 and https://github.com/react-community/react-native-maps/issues/2003.

**Comment by goliath45** [comment] 2018-08-08 11:09
Thanks for info

**Comment by khuongdv** [comment] 2018-08-08 18:16
Eventually I did not find out the solution of the lib itself. I had to add an absolute View holding an icon to make a fake button to view current location... :|

**Comment by rborn** [comment] 2018-08-13 09:32
Closing as per https://github.com/react-community/react-native-maps/issues/2408#issuecomment-411362752

**Closed by rborn** 2018-08-13 09:32 UTC
