### ISSUE TITLE
Android: onDeselect / onSelect are not triggered

### ISSUE THREAD

**Issue by mvaivre** [react-community/react-native-maps#227] opened 2016-05-13 08:49 UTC
It seems that the Marker's event callbacks `onDeselect`, `onSelect` and the equivalent on MapView `onMarkerSelect`, `onMarkerDeselect` are never triggered.

Version: 0.4.0

**Comment by mvaivre** [comment] 2016-05-13 13:20
Kind of duplicates https://github.com/lelandrichardson/react-native-maps/issues/114

**Comment by DennisMG** [comment] 2016-05-18 15:03
This is because they are not implemented on android.

**Comment by mvaivre** [comment] 2016-05-19 08:45
@DennisMG : yep, that's why I referenced #114. But it would be a more-than-useful feature :).
In the meantime, we could try to specify more clearly in the doc what's available for Android and what is not!

**Comment by KGALLET** [comment] 2016-07-13 14:23
+1

**Comment by magrinj** [comment] 2017-01-20 10:10
@KGALLET Any news on this ? :)

**Comment by KGALLET** [comment] 2017-01-20 10:25
@magrinj Sorry, but i'm not working on react native project anymore for the moment..

**Comment by magrinj** [comment] 2017-01-20 10:57
@KGALLET Ok no problem, thanks!

**Comment by alvelig** [comment] 2017-12-12 00:32
Duplicate of 114

**Closed by alvelig** 2017-12-12 00:32 UTC
Labels: Android, enhancement
