### ISSUE TITLE
Images on Android don't display if initially rendered off screen

### ISSUE THREAD

**Issue by invig** [react-community/react-native-maps#702] opened 2016-10-18 02:45 UTC
If you put `<Image />` tags in a marker or callout they do not display on the first presentation, and often do not display at all. 

`E/unknown:DraweeEventTracker: 2ecd448: Draw requested for a non-attached controller f3482e1. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, activityStarted=true, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}`

It looks like something to do with Android and the component not being on screen at time of render. 

I've tried this with both `source=require('x')` and `source={{uri: 'x'}}` methods of fetching an image. Neither works reliably.

I'll try to go down the Android stack and figure out what's going on, but I'm by no means an expert on Android so if anyone has any pointers as to where this might be able to be fixed please advise. I do wonder if it's a deeper issue in React.

**Comment by VietDucPhan** [comment] 2016-10-26 06:54
I have the same issues. I am trying to display an image inside a Callout. But it is not display the image. But if i turn on the "touchables" in the inspector, the image is show again. Any advice would be appriciated

**Comment by veedeo** [comment] 2016-11-17 19:14
Same here, even if require local images it doesn't work. Workaround is to put this image somewhere, before showing the map

**Comment by invig** [comment] 2016-11-17 20:01
When you say put this image somewhere, I tried a few places with no luck. Where did you have success putting it?

**Comment by veedeo** [comment] 2016-11-19 08:39
I have another screen before the map, I show there all the images that will be used in the map. You can also put them in splash screen. Not sure how it will work after garbage collection

**Comment by invig** [comment] 2016-11-19 10:17
Damn, my map content is dynamic (pulled in from the server based on position) - so there’s no way for me to do that.

**Comment by veedeo** [comment] 2016-11-19 10:37
If you are showing local Images based on dynamic content, you can show once
all the available images in different screen.
If you are showing images from the net, you can prefetch them with
Image.getSize() prior to adding the marker

**Comment by alvelig** [comment] 2017-07-06 02:42
Damn, this is stupid, lol
I put `<Image source={detail} style={{ height: 0, width: 0 }}/>`
within my `<Marker>` to show the image on first callout appearance...

This is how it works...

**Comment by alvelig** [comment] 2017-12-14 05:03
kinda Duplicate of #100

**Closed by alvelig** 2017-12-14 05:03 UTC
