### ISSUE TITLE
Red screen module "Undifined"

### ISSUE THREAD

**Issue by xxstefanoxx** [react-community/react-native-maps#2117] opened 2018-03-21 17:20 UTC
### Is this a bug report?
when i import:
import MapView from 'react-native-maps';
I recive this error:
Require unknown module "undefined". if you are sure the module is there, try restarting Metro Bundler...

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
    "react": "^16.3.0-alpha.1",
    "react-google-maps": "^9.4.5",
    "react-native": "0.54.2",
    "react-native-maps": "*"
    Target Platform: eg: iOS - native and simulator, Android native and simulator

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

https://ibb.co/j9539c
### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by rborn** [comment] 2018-03-21 17:49
closing , duplicate of https://github.com/react-community/react-native-maps/issues/2071

use the git version.

**Closed by rborn** 2018-03-21 17:49 UTC
