### ISSUE TITLE
Is there a way to create cluster map? with multiple locations like airbnb maps

### ISSUE THREAD

**Issue by anandbabud1987** [react-community/react-native-maps#1942] opened 2018-01-06 02:42 UTC
### Is this a bug report?

(write your answer here)

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by alvelig** [comment] 2018-01-06 02:43
Duplicate of #213

**Closed by alvelig** 2018-01-06 02:43 UTC
