### ISSUE TITLE
Showing "Invariant violation:native component for "AirMap" does not exist"

### ISSUE THREAD

**Issue by aneena-thomas** [react-community/react-native-maps#2247] opened 2018-05-11 09:20 UTC
Installed react-native maps by running "npm install react-native-maps --save"
and linked the react-native-maps
But showing the below error

![simulator screen shot - iphone 6 - 2018-05-11 at 14 48 14](https://user-images.githubusercontent.com/13118654/39917292-b3d6b0c4-552a-11e8-8318-c416dc56b4f0.png)

**Comment by JorgeLoaiza12** [comment] 2018-05-11 21:26
Same problem! 👍

**Comment by rborn** [comment] 2018-05-13 11:09
Duplicate of many other issues, also no template. Closing

**Closed by rborn** 2018-05-13 11:09 UTC
Labels: NO ISSUE TEMPLATE, duplicate

**Comment by aneena-thomas** [comment] 2018-05-13 13:42
@rborn  tried all solutions but still its shows "Invariant violation:native component for "AirMap" does not exist"

**Comment by gabrielbuzziv** [comment] 2018-05-21 12:46
@rborn duplicated of may other issues that you guys didnt solved

**Comment by Yaweii** [comment] 2018-06-10 21:56
@gabrielbuzziv agree!
