### ISSUE TITLE
Setup project using react-native link 

### ISSUE THREAD

**Issue by dheerajsinghanktech** [react-community/react-native-maps#2187] opened 2018-04-12 07:08 UTC
### Is this a bug report?

NO, Is there any way to install this package and then link to android and IOS project using react-native link command?. Because I am getting lots of error while using the installation instruction and also I have installed other package through react-native link therefore that's needs be updated

**Comment by dylmye** [comment] 2018-10-17 21:06
dupe of #2289, #1954

**Closed** 2018-10-18 08:31 UTC
Labels: NO ISSUE TEMPLATE
