### ISSUE TITLE
AirMapsExplorer has stopped on Android device

### ISSUE THREAD

**Issue by compojoom** [react-community/react-native-maps#607] opened 2016-09-25 09:53 UTC
I'm trying to run the examples on my android phone (6.0). 
Unfortunately when I run the example I get AirMapsExplorer has stopped (similar to #285). I launched adb logcat and here is the output

```
09-25 11:48:14.404 28787 28787 E MPlugin : Unsupported class: com.mediatek.settings.ext.ISettingsMiscExt
09-25 11:48:14.406 28787 28787 E MultiWindowProxy: getServiceInstance failed!
09-25 11:48:14.433 20923 20923 E AndroidRuntime: FATAL EXCEPTION: main
09-25 11:48:14.433 20923 20923 E AndroidRuntime: Process: com.airbnb.android.react.maps.example, PID: 20923
09-25 11:48:14.433 20923 20923 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@a5d8190 -- permission denied for this window type
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:707)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:319)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.app.Dialog.show(Dialog.java:326)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:653)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:397)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:815)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:104)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:207)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5741)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
09-25 11:48:14.433 20923 20923 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
09-25 11:48:14.442   896 20946 W AES     : Exception Log handling...
09-25 11:48:14.502   896  4858 W libEGL  : [ANDROID_RECORDABLE] format: 1
09-25 11:48:14.515 19051 10783 E MPlugin : Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
09-25 11:48:14.544 28787 19811 W AppStateAppOpsBridge: AppOp permission exists for package android of user 0 but package doesn't exist or did not request [Ljava.lang.String;@8fc20b3 access
09-25 11:48:14.587 28787 19811 W AppStateAppOpsBridge: AppOp permission exists for package android of user 0 but package doesn't exist or did not request [Ljava.lang.String;@8fc20b3 access
09-25 11:48:14.613 28787 28804 W libEGL  : [ANDROID_RECORDABLE] format: 1
```

I have an app with react-native maps and I have managed to show a map and a marker. So the package should be able to work on my device, however it seems that something is wrong with the example app. Any ideas?

**Comment by leewrigh7** [comment] 2016-10-29 02:53
Same thing here - I'm not having much luck with this package, so far, in a week I've managed to render a google logo after countless errors.

**Comment by alvelig** [comment] 2017-12-14 05:07
Stick to documentation updates, we are working on new examples

**Comment by alvelig** [comment] 2017-12-14 05:09
Duplicate of #594

**Closed by alvelig** 2017-12-14 05:09 UTC
