### ISSUE TITLE
showsMyLocationButton does not work on Android as it should

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-native-maps#1332] opened 2017-05-15 19:55 UTC
currently the only way showsMyLocationButton can appear on android is if the height of the map is adjusted then it will re-render the map and it will appear. Can we fix this so it works without a re-render needed.

**Comment by VietDucPhan** [comment] 2017-06-19 17:51
I tried to change the height and it is buggy as hell. How did you make it appear? I gave up on the way the button support to show.

**Comment by nonameolsson** [comment] 2017-07-11 22:14
I am also encountering this issue. Can't make compass, scale or location button to show up.

**Comment by amsimoes** [comment] 2017-07-13 19:21
I'm having the same issue. 
I found out that the Compass only shows when you rotate the user rotates the Map. 
Regarding the scale I have no idea.

Also, in order to trigger the MyLocation Button to show, I'm leaving this relevant snippet (code incomplete):
```javascript
import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
(...)

class MapScreen {
    state = { hackHeight: height }

    componentWillMount() {
        setTimeout( () => this.setState({ hackHeight: height+1}), 500);
        setTimeout( () => this.setState({ hackHeight: height}), 1000);
    }
    (...)

    <View style= {{ paddingBottom: this.state.hackHeight }}>
        <MapView...
    (...)
}
```

I'm also styling my MapView with:
```javascript
const styles = StyleSheet.create({
	map: {
	  ...StyleSheet.absoluteFillObject,
	},
});
```
This workaround is inspired from the @Lars-m reply on issue #1033 that didn't work straight forward for me.

**Comment by bcitdaltond** [comment] 2017-07-20 22:32
Having the same issue on iOS using mapkit (no button)

**Comment by amsimoes** [comment] 2017-07-21 15:26
Actually, while my workaround worked (not 100% times) on Testing with Expo on real device, now that I've built the release apk it doesn't show the button anymore...

It's a pity and a bit weird that airbnb doesn't fix this simple but very important component of the Map...

**Comment by martinezguillaume** [comment] 2017-08-30 15:50
Pretty unstable workaround for an important feature ☹️, and the workaround in iOS doesn't work...

**Comment by vhuytdt** [comment] 2017-12-12 08:03
i use style below
const styles = StyleSheet.create({
	map: {
	  ...StyleSheet.absoluteFillObject,
	},
});
and setTimeOut repaint map in componentWillMout but no work..

if i don't use StyleSheet.abosluteFillObject and set width height to map, it will show my button..

--  how to it work with absoluteFillObject

**Comment by alvelig** [comment] 2017-12-13 01:58
@rborn @christopherdro 
I suggest we don't support this native feature, as it does not work as expected in Apple Maps nor in GoogleMaps Android. But I can create an example of making a custom 

Actually it is pretty like this https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665, just calling `getCurrentLocation`

**Comment by rborn** [comment] 2017-12-13 08:58
@alvelig we might leave it as an issue for a later stage and see if we'll be able to implement it or find a workable solution.

**Comment by alvelig** [comment] 2017-12-14 04:11
Duplicate of #1033. Follow there

**Closed by alvelig** 2017-12-14 04:11 UTC
Labels: bug, Google Maps

**Comment by gtatyous** [comment] 2019-02-25 00:22
Is this issue fixed?
