### ISSUE TITLE
Location marker does not show on Google maps in IOS

### ISSUE THREAD

**Issue by jojonarte** [react-community/react-native-maps#740] opened 2016-10-28 03:33 UTC
Is this a known issue? It seems to work fine on default map but when using Google map as provider the location marker does not show.

Code is as follow:

```
<MapView
              style={{...StyleSheet.absoluteFillObject,}}
              provider="google"
              showsUserLocation={true}
              cacheEnabled={true}
              showsTraffic={false}
              showsIndoors={false}
              loadingEnabled={true}
              showsBuildings={false}
              region={{
                  latitude: location.latitude,
                  longitude: location.longitude,
                  latitudeDelta: location.latitudeDelta,
                  longitudeDelta: location.longitudeDelta,
                }}
              >

              {businesses.length > 0 ? businesses.map(marker => (
                  <MapView.Marker
                    coordinate={this.getCoordinates(marker)}
                    key={marker.id}
                    flat={true}
                    image={typeof marker.image_url !== 'undefined'  ? marker.image_url : marker.icon}
                  >
                  </MapView.Marker>
              )) : <View />}
            </MapView>
```

XCode 8

**Comment by julien-rodrigues** [comment] 2016-11-21 14:09
The functionality has been merged in version 0.10.4: https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md#0104-october-31-2016

**Comment by macnube** [comment] 2016-12-01 20:45
Was there a possible regression in 0.11? I'm using GoogleMaps on iOS and I'm not able to get this to work on simulator or the iPhone 5s that I'm using for testing.

`<MapView
				provider={"google"}
				style={styles.map}
				region={props.region}
				onRegionChangeComplete={props.handleRegionChange}
				loadingEnabled={true}
				showsUserLocation={true}
				showsPointsOfInterest={false}>`

**Comment by julien-rodrigues** [comment] 2016-12-01 23:06
Yes and no lol

In fact the 0.11 doesn't seem to have everything that's inside the 0.10.4

0.10.4 is out since 31st October but the 0.11 is around since the 16th... https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md#0104-october-31-2016

**Comment by julien-rodrigues** [comment] 2016-12-01 23:12
I opened an issue: https://github.com/airbnb/react-native-maps/issues/851

**Comment by gilbox** [comment] 2016-12-02 05:11
Yeah it's a bit confusing because we have been maintaining 0.10.x releases separately for use at airbnb until we can upgrade to RN@0.38.0. It's good to know that upgrading would introduce a regression for us.

**Comment by julien-rodrigues** [comment] 2016-12-09 15:23
@macnube A new version has been released containing every thing that was missing from the `0.11`

**Comment by rborn** [comment] 2017-12-18 22:45
Please let us know if this is still the case. Thank you.
Closing as it's an old issue.

**Closed by rborn** 2017-12-18 22:45 UTC
