### ISSUE TITLE
master :Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference

### ISSUE THREAD

**Issue by abud4646** [react-community/react-native-maps#1486] opened 2017-07-17 17:45 UTC
im getting the following error on the emulator

 ```

Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference
b
    :com.google.android.gms.DynamiteModulesB:26
onTransact
    :com.google.android.gms.DynamiteModulesB:21
transact
    Binder.java:441
onResume
    null
onResume
    null
zzb
    null
zza
    null
onResume
    null
onResume
    null
onHostResume
    AirMapView.java:307
run
    ReactContext.java:153
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
main
    ActivityThread.java:5417
invoke
    Method.java
run
    ZygoteInit.java:726
main
    ZygoteInit.java:616

```

**Comment by alvelig** [comment] 2017-12-12 04:09
I recently made a fresh example build with pods and GoogleMaps with no issues.
https://github.com/alvelig/react-native-maps-pods-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Comment by alvelig** [comment] 2017-12-12 04:11
Duplicate of #1575

**Closed by alvelig** 2017-12-12 04:11 UTC
