### ISSUE TITLE
My app crashes as soon as i load the map 

### ISSUE THREAD

**Issue by BigPun86** [react-community/react-native-maps#420] opened 2016-07-24 17:54 UTC
Running on Mac, RN29.2, maps v 0.7.1, Android

```
Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
                         E  FATAL EXCEPTION: main
                         E  Process: com.test.test, PID: 12879
                         E  java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/inte
                            rnal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.test.test-1/base.apk)
                         E      at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
                         E      at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:59)
                         E      at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:27)
                         E      at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
                         E      at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:206)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:874)
                         E      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:847)
                         E      at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                         E      at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:549)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:135)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
        ActivityManager  W    Force finishing activity 1 com.test.test/.MainActivity
          EGL_emulation  E  tid 565: eglCreateSyncKHR(1209): error 0x3004 (EGL_BAD_ATTRIBUTE)
```

I have no clue what this stacktrace wants to tell me?!

**Comment by hstabbal** [comment] 2016-07-27 02:12
This is due to different version of com.google.android.gms:play-services-gcm
In order to fix it, you have to look in the list of modules that you added to your project, other than react-native-maps, that also use google play services.
Most probably, it will be something related to push notifications.
Once you identify it, you have to check module build.gradle for the version of gms used. Try putting the version specifically to 8.4.0 for all modules using google play services.

**Comment by hstabbal** [comment] 2016-07-27 02:16
I had the same problem. I was using onesignal for push notifications.
In order to fix the issue, I updated build.gradle for onesignal with  : 
 compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'
And also made sure that for react-native-maps I had :
  compile "com.google.android.gms:play-services-base:8.4.0"
  compile 'com.google.android.gms:play-services-maps:8.4.0'

With these changes, everything worked fine.

To spot the problem, just look at the output during build:
:app:prepareComGoogleAndroidGmsPlayServicesLocation840Library
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library
if you see different version numbers, like : 
:app:prepareComGoogleAndroidGmsPlayServicesLocation921Library
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library

then maps will fail and your app will crash.

**Comment by vandervidi** [comment] 2016-08-19 12:46
@hstabbal  This worked for me! Thanks

**Comment by Nishchit14** [comment] 2017-05-08 04:00
Found this helpful
https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by aaronbuchanan** [comment] 2017-06-30 05:53
dupe of #951 which fixed for me!

**Comment by alvelig** [comment] 2017-12-12 02:57
I recently made a fresh example build.
https://github.com/alvelig/react-native-maps-example.
Try to check it out or build through the README.MD. If it does not help, let me know.

**Closed by alvelig** 2017-12-12 02:57 UTC

**Comment by umairalii** [comment] 2019-05-05 07:44
`<uses-library
        android:name="org.apache.http.legacy"
        android:required='false' />`

in androidmenifest.xml
