### ISSUE TITLE
Is a manual install possible (ios)

### ISSUE THREAD

**Issue by allthetime** [react-community/react-native-maps#1954] opened 2018-01-09 13:17 UTC
Hi, not sure whats going on but the cocoa pods installation is creating all sorts of issues.

It makes my project unbuildable in both the workspace and the xcodeproject

The only way to fix it is to do pod deintegrate, but then I haven't installed maps.

Is there another way?

**Comment by rborn** [comment] 2018-01-09 13:19
Sadly for now this is the most reliable way of installing the plugin.

Closing for not having the issue template.

**Closed by rborn** 2018-01-09 13:19 UTC
Labels: NO ISSUE TEMPLATE

**Comment by allthetime** [comment] 2018-01-09 13:26
@rborn 

But it's not reliable at all. I'm on react-native v52 and the instructions fail, specfically with this:

```
/Users/chris/OnThisSpot/node_modules/react-native/ReactCommon/yoga/yoga/YGNodePrint.cpp:208:46: Implicit conversion loses integer precision: 'size_type' (aka 'unsigned long') to 'const uint32_t' (aka 'const unsigned int')
```

and the classic:

```
: Linker command failed with exit code 1 (use -v to see invocation)
```

more specifically:

```
ld: warning: directory not found for option '-L/Users/chris/Library/Developer/Xcode/DerivedData/OnThisSpot-carmylzvgamftjawdunkdzxxwbzw/Build/Products/Debug-iphonesimulator/React'
ld: warning: directory not found for option '-L/Users/chris/Library/Developer/Xcode/DerivedData/OnThisSpot-carmylzvgamftjawdunkdzxxwbzw/Build/Products/Debug-iphonesimulator/yoga'
ld: library not found for -lPods-OnThisSpot
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rborn** [comment] 2018-01-09 13:29
@allthetime that's a react-native issue: https://github.com/facebook/react-native/issues/17274

**Comment by allthetime** [comment] 2018-01-09 13:32
@rborn ahh... but until that is fixed, how is anyone supposed to install this library on react-native? Do I need to rollback to 51?

**Comment by rborn** [comment] 2018-01-09 13:39
I guess yes. Is there anything new in 0.52 that you need, if no I'd wait for a little before updating (I usually try to do this)

**Comment by allthetime** [comment] 2018-01-09 13:51
@rborn I just rebuilt my project from scratch for 0.52 (I always find it easier to do this than try to update/upgrade with the available tools, so that I could get access to some new features... but all the ones I need are available in 0.51, so I just reverted back to that and everything seems to be working so far

**Comment by alper** [comment] 2018-01-13 11:45
But the project recommends not using react-native-link, but I have an app without a Podfile so the installation instructions do not make sense for me.

**Comment by rborn** [comment] 2018-01-13 13:40
You will need to create one( the pod file)

**Comment by alper** [comment] 2018-01-13 19:27
But if you have a `create-react-native-app` or `react-native-cli` created app you will have to add a Podfile and change your project setup just to be able to use react-native-maps?

By the way I just linked the library and it is working that way. I would prefer it if that way worked because that hugely reduces the amount of friction for people using this library.

**Comment by alvelig** [comment] 2018-01-14 01:31
@alper it's working because you are not using GoogleMaps iOS SDK (`provider="google"`).
We support only `react-native init` created apps, so we can't say what happens with `create-react-native-app`, but as far as I know expo app has already done those 'frictions' and included GM IOS SDK in their bundle.  If you don't want to use Pod file you can link GM SDK manually (much more frictions, believe me)

The problem behind your question is that there are 3 possible scenarios of using this lib in iOS. This way choosing one as a default we close other options for the users. That is not a big deal to follow the docs. If something is not clear or you think should be updated, let us know please.

**Comment by alper** [comment] 2018-01-15 08:52
OK!

- It would be good to know that you can just do `link` and you can then use the maps without Google as a provider. That would be a very quick way for a lot of people to get started (including myself).
- I was hesitant to add a Podfile because I think that would cause a non-trivial reorganization of my project (switch from `xcodeproj` to `xcworkspace` etc.).

**Comment by rborn** [comment] 2018-01-15 10:37
@alper I think you have a valid point. Our concern is that if we encourage people to use link for normal apps it will mean trouble in the long run for most of the users:
- If you want to upgrade the to google maps at a later stage, the linking will mess up everything and will be pretty hard to fix
- If we say "use link for apple maps" many users will half read the instructions and start complaining it's not working
- Cocoapods and project structure change it's a nuisance  for sure, but we try to minimise the risks :(

**Comment by xinlangzi** [comment] 2018-02-06 08:46
@alper 

Have you figure out how to make this work on IOS app without podfile? I'm looking forward to .

**Comment by alvelig** [comment] 2018-02-09 15:50
@xinlangzi https://github.com/alvelig/react-native-maps-example

**Comment by yqbk** [comment] 2018-02-13 08:45
@alvelig Could you provide some basic instruction how to link it manually? Which libraries add to Xcode and so on?

**Comment by alvelig** [comment] 2018-02-13 12:23
@yqbk https://developers.google.com/maps/documentation/ios-sdk/start Tab "Manually"

**Comment by olegserov** [comment] 2018-06-13 14:35
Please see this solution that works without manual linking:
https://github.com/react-community/react-native-maps/issues/2324

**Comment by alvaromb** [comment] 2018-07-06 17:07
Hello @rborn.

Please don't take my following words in a harsh way, but I think your statements are misguided.

> If you want to upgrade the to google maps at a later stage, the linking will mess up everything and will be pretty hard to fix

First of all, why should this library force iOS users to embed & install Google Maps SDK if there's an already built-in solution like Apple Maps? 

Embedding Google Maps inserts a lot of dependencies and headaches for a feature that **not anybody** will implement under iOS. It should be provided as a separated module or an optional installation process. This, of course, will not "mess up everything" and be "pretty hard to fix", because this module is already quite hard to install, partially due this. [This piece](https://sandofsky.com/blog/third-party-libraries.html) written by Ben Sandofsky summarises some of this problems quite well.

Having said this, I would like to know if whoever is responsible for this repo maintenance is open to the following suggestions:

- Bring back support for `react-native link`
- Remove the necessity for Cocoa Pods to use this module
- Temporarily drop Google Maps support for iOS 
- Provide a separate installation guide for Google Maps support under iOS

We would gladly give a hand and use our company time to help with this transition or something similar.

**Comment by rborn** [comment] 2018-07-10 10:36
@alvaromb  I am not offended, don't worry.

This repo happens to be in a "weird" state right now:
- me and @alvelig are reviewing issues and PRs as much as we can, for me it's even worse as my native (ios/android) knowledge is limited
- @christopherdro does the releases on npm but I think he is very very busy and we didn't find anyone who could give us access to npm to be able to publish ourselves 
- we do this as volunteers, we don't own anything here, have limited time and also limited powers (like the above point)

Some replies below:

> First of all, why should this library force iOS users to embed & install Google Maps SDK if there's an already built-in solution like Apple Maps?

Are you sure this is happening? I think you can use the library without Google maps on ios and without the need to embed it. Am I wrong?

> Having said this, I would like to know if whoever is responsible for this repo maintenance is open to the following suggestions:

> Bring back support for react-native link

I totally agree, would be amazing

> Remove the necessity for Cocoa Pods to use this module

As long as this doesn't break anything it should be fine. By "anything" I mean updates from older versions, behaviour in the app, etc. Of course we could make a "breaking" release and warn users but it has to be very well documented.

> Temporarily drop Google Maps support for iOS

As far as I know you **don't need** to use google maps in iOs. If this happened with a PR then we messed up something up or the feature implemented by the PR uses google map as dependency. 
If we can fix this without breaking the library I totally agree.

> Provide a separate installation guide for Google Maps support under iOS

Yes, good idea
 
> We would gladly give a hand and use our company time to help with this transition or something similar.

If you can step in improve the the package we'll be very happy to  help with everything we can.

@alvelig what do you think of this?

@christopherdro man, what can we do to get a faster release pace when it's the case? Who could give access to more people to publish to npm or how can we help you do this faster?

**Comment by alvelig** [comment] 2018-07-10 10:45
Well, @alvaromb you are welcome to push a PR with what you propose. Yes, at some point Google Maps classes were checked in. Just delete that folder and you'll be fine without GMaps in iOS (in previous versions you had to add it manually to have GMaps support).

@rborn I'm completely with you in it. I welcome any support for the library, as we definitely manage only to answer only some issues. Most of the job done by you though.

**Comment by christopherdro** [comment] 2018-07-11 15:38
@rborn If someone can prepare the release, similiar to the last one I'll be more than happy to push it up. Here is the PR from the last release.
https://github.com/react-community/react-native-maps/pull/2146

@felipecsl @lelandrichardson @spikebrehm @gpeal I think one of you might have owner access. 
Could you please help with adding @rborn as a contributor so he can publish releases as well?

**Comment by rborn** [comment] 2018-07-11 16:02
@christopherdro I will try to prepare something, thank you

**Comment by alvaromb** [comment] 2018-07-13 14:25
Thanks for your reply @rborn. Yes, the issue is that Google Maps are checked-in and you can't run the iOS version without installing or deleting them.

This PR seems to fix the current issue, because deleting the `AirGoogleMaps` makes the library work on iOS with `react-native link`.

We're in the middle of a very important release, but I'll be available to help very soon.

Thank for your work guys.

**Comment by thanhdevapp** [comment] 2018-08-09 16:24
@alvaromb so please give me version json lastest react-native-maps work on ios.

**Comment by jose920405** [comment] 2019-06-19 16:10
@allthetime 

I have the same problem with: 
`Directory not found for option '-L....../Build/Products/Debug-iphonesimulator/React`.
