### ISSUE TITLE
MapViewElements Grouped/Nested inside i <View> are not visible on IOS.

### ISSUE THREAD

**Issue by breakeren** [react-community/react-native-maps#1074] opened 2017-03-01 14:36 UTC
On Android, I am able to do something like this

```
<Mapview>
   <View>
      <Marker/>
      <Circle/>
      <Polyline/>
   </View>
</MapView>
```

This is nice because I can make a CustomComponent that renders the Marker, Circle and Polyline

I Can then reuse my CustomComponent on many different maps like this:

```
<MapView>
   {locations.map((loc, i)=><CustomComponent location={loc} key={i}/>)}
</MapView>
```

This works fine on android but is not visible on IOS. In IOS only markers in the top layer are shown - not if they are nested deeper within i a View. Because Components are required to return a single top-level-element, I need to group the MapViewElements under a View.

The documentation does not say explicitly, that I am supposed to be able to do this, but it works on android.

**Comment by MarianoTucat** [comment] 2017-05-19 22:24
Is there any news on this? would this be supported in iOS in the future? or is there any specific component we can use to group others?

**Comment by shanecav** [comment] 2017-08-29 07:40
Sounds like you're wanting for the feature described in #40 (I am too).

**Comment by shanecav** [comment] 2017-08-29 10:36
Once React Native starts using Fiber, you'll be able to build components that return arrays of elements, and won't have to worry about wrapping elements in a parent element. (Hopefully that happens soon, I'm looking forward to composable map features, too!).

I'm guessing nobody has spent time implementing grouped features here because a React solution is around the corner.

**Comment by alvelig** [comment] 2017-12-15 06:11
Duplicate of #764

**Closed by alvelig** 2017-12-15 06:11 UTC
