### ISSUE TITLE
"AIRMap" was not found in the UIManager.

### ISSUE THREAD

**Issue by vemundeldegard** [react-community/react-native-maps#2495] opened 2018-09-18 14:35 UTC
### Is this a bug report?

Yes and No, as it has been answered in many other Issues, but none of the answers seems to work for me...

> Invariant Violation: requireNativeComponent: "AIRMap" was not found in the UIManager.
> 
> This error is located at: in AIRMap (at MapView.js:760) in MapView (at Home.js:118)

![skjermbilde 2018-09-18 kl 16 34 47](https://user-images.githubusercontent.com/36489034/45695045-e18a6c80-bb60-11e8-86f1-c511b647587b.png)

 

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

  "react-native": "^0.57.0-rc.4",
  "react-native-maps": "^0.21.0",

Target platform: iOS Simulator: iPhone 6

### Steps to Reproduce

I tried this: 

1. rm -rf ios android node_modules
2. npm install
3. react-native upgrade
4. react-native link
5. libAirMaps.a is added in Build Phases
6. AirGoogleMaps and AirMaps is added to Frameworks
7. Followed this guide to add Maps SDK for iOS manually without CocoaPods: https://developers.google.com/maps/documentation/ios-sdk/start
8. Added @import GoogleMaps; and [GMSServices provideAPIKey:@"_YOUR_API_KEY_"]; to AppDelegate.m

### Expected Behavior

I have not added this to package.json, as I am unsure what path it is asking for? I found this at https://github.com/react-community/react-native-maps/blob/master/docs/installation.md

```
{
  "name": "your-app",
  "scripts": {
    "postinstall": "./node_modules/react-native-maps/enable-google-maps REPLACE_ME_RELATIVE_PATH_TO_GOOGLE_MAPS_INSTALL"
  }
}
```

The Map would be displayed. But I get the error no matter what I do. 

### Actual Behavior

Added this to my component, followed the guides excactly. Also tried creating a new app, but it doesn't work: 

```
import MapView from 'react-native-maps';
<MapView
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
      />
```

### Reproducible Demo

Working on setting this up.

**Comment by rborn** [comment] 2018-09-18 14:39
@vemundeldegard many other issues say to use the github version - did you try?

**Comment by vemundeldegard** [comment] 2018-09-18 15:12
> @vemundeldegard many other issues say to use the github version - did you try?

Isn't the Github version the same as the npm 0.21.0? How can I use the github version istead? sorry for asking stupidly

**Comment by rborn** [comment] 2018-09-18 15:15
@vemundeldegard sadly no, there is only one person that is allowed to publish to npm and he's very busy

**Comment by vemundeldegard** [comment] 2018-09-18 15:18
> @vemundeldegard sadly no, there is only one person that is allowed to publish to npm and he's very busy

Ah! I see. So you suggest cloning the Git and adding it manually? How can I do that?

**Comment by vemundeldegard** [comment] 2018-09-18 15:33
> "react-native-maps": "https://github.com/react-community/react-native-maps.git"

No difference sadly:( Can't it be something wrong in the xcodeproject? I don't understand...

**Comment by rborn** [comment] 2018-09-18 15:43
did you run `react-native link react-native-maps` ?

**Comment by vemundeldegard** [comment] 2018-09-18 15:46
Yes, I did! 

![skjermbilde 2018-09-18 kl 17 46 16](https://user-images.githubusercontent.com/36489034/45699668-c9b7e600-bb6a-11e8-826d-620de7b5098c.png)

**Comment by rborn** [comment] 2018-09-18 15:54
pod files?

**Comment by vemundeldegard** [comment] 2018-09-21 14:41
> Vemunds-MacBook-Air:ios vemundeldegard$ pod install
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `React` from `../node_modules/react-native`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Fetching podspec for `react-native-google-maps` from `../node_modules/react-native-maps`
> Fetching podspec for `react-native-maps` from `../node_modules/react-native-maps`
> Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`
> [!] Unable to find a specification for `boost-for-react-native` depended upon by `Folly`
> 
> [!] Automatically assigning platform `ios` with version `9.0` on target `AwesomeProject` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Used the Podfile found in the Installation guide...

**Comment by adispartadev** [comment] 2018-09-23 08:01
My issues fixed by using this step

1. Using `"react-native-maps": "https://github.com/react-community/react-native-maps.git"` in my package.json and run `yarn install`

2. In my `android/build.gradle`, add:
```
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "27.1.1"
    googlePlayServicesVersion = "15.0.1"
    androidMapsUtilsVersion = "0.5+"
}
```
May be you must adjust with your project

3. In `android/app/build.grade` add `compile project(':react-native-maps')` in `dependencies` object

4. In `android/app/src/main/java/com/projectName/MainApplication.java` edit in getPackages() function so it look like this 
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new MapsPackage()
      );
    }
```
I fixed my issue by adding this last step. I got the `AIRMap` error when I forget to adding `new MapsPackage()` in my MainApplication.java

May be you must adjust with yout ios setting, btw I didn't develop in ios :smile:

**Comment by ProteanDev** [comment] 2018-09-24 18:38
@vemundeldegard did you solved your problem?

**Comment by amirkheirabadi** [comment] 2018-09-25 09:12
@adispartadev I try this steps, but I get 'AURMAP' not found error again,

**Comment by vemundeldegard** [comment] 2018-09-25 15:40
I didn't solve the problem, but I made it work by redoing everything and making a new project. Start from scratch and install everything again. Works good now.

**Comment by Viktor6713** [comment] 2018-09-30 15:19
I have the same issue. Clean react native 0.57.1 and tried install maps from npm or git. I am just running react-native link, but I am not sure if I should do both steps `iOS - CocoaPods` and `iOS - ReactNative Link` because I do not want google maps for ios.

**Comment by SebastianGrzymala** [comment] 2018-09-30 20:10
I temporary switched to Mike Morris version. This only works fine to me at the moment for 0.57.1. Using react-native link. 
`"react-native-maps": "github:mikemorris/react-native-maps#ef5c839252e427268ae2ebbf4f0cced1cb51fed6"`

**Comment by vutronic** [comment] 2018-10-01 02:18
These steps fixed the issues for me.

  1. Clear watchman watches: watchman watch-del-all
  2. Delete the node_modules: rm -rf node_modules && npm install
  3. Reset Metro Bundler cache:  rm -rf /tmp/metro-bundler-cache-*
  4. Remove haste cache: rm -rf /tmp/haste-map-react-native-packager-*
5. Shut down all terminal windows.
6. Delete the app on the ios simulator (I'm using the simulator).
7. Delete /ios/build
8. run 'react-native run-ios'.

**Closed** 2018-10-11 10:04 UTC

**Comment by atmeanas** [comment] 2018-10-11 13:33
> @vemundeldegard put this in your package.json
> `"react-native-maps": "https://github.com/react-community/react-native-maps.git",` and run `npm install`

I've just tried this and still doesn't work, the error is the same "AIRMap was not found"

**Comment by NTramper** [comment] 2018-10-18 14:06
Still doesn't work for me

"react-native": "0.57.2",
"react-native-maps": "^0.21.0",

**Comment by Viktor6713** [comment] 2018-10-18 19:57
I have got this lib working, after completely updating node and yarn to the latest versions. In the end I've used yarn instead npm, so there might be a problem with npm install.

**Comment by rborn** [comment] 2018-10-19 07:39
@NTramper @benjaminreid `link` is implemented in `0.22` so please update your map package.

**Comment by zafarnadim** [comment] 2018-10-19 21:33
I solved it by adding the .xcodeproj in node_modules/react-native-maps/lib to Libraries by right clicking and then adding it to link binary with libraries and linked frameworks and libraries. 

Shout out to @spearmootz for guiding me on this :D

**Comment by ventr1x** [comment] 2018-10-25 09:31
I love how every issue gets simply closed without solution or help. A simple statement what could be wrong/missing would help. People writing their Android "solution" to an ios OP is also not very helpful and only clutters everything.

I get that it might be a stupid little error. Something missing or clashing. But giving a hint how to validate that everything is linked correctly would be nice.
Something like "downgrade your RN until it works" like many stated is clearly no solution or option whatsoever.

As the podfile in the instructions differs significantly from the default one - and simply replacing it is normally not an option (we have other pods, you know?) - my guess would be people not including all the dependencies correctly. But no one can validate things like that without knowing what is actually needed from the podfile.

**Comment by n13** [comment] 2018-11-02 08:14
Try this before you try anything of the above (I tried a bunch of them and none worked, but they made it more difficult to apply the fix below as I screwed up my project in the process)

**I fixed this one by** 
```
cd ios
pod install
```

The instructions are simply unclear on what to do - the implication seems to be one can either use react native link OR install CocoaPods. When in actuality you have to do a _pod install_ at least.

Although it wasn't that simple as I tried many different things, got maps version 0.21 installed, the pod for that doesn't work, so had to install maps v 0.22, then upgrade the pod to 0.22 - and voila, it works!

It's not difficult to fix! The problem is there's poor documentation, and a lot of the steps in this answer are unnecessary. I am guessing they were for version 0.21 and possibly others that actually had an issue with integration.

0.22 works!

You only have to go to ./ios and run 'pod install'.

**Comment by mkchx** [comment] 2018-11-08 14:53
For me manually linking in iOS was the solution, as for the android, it works by default.
react-native: 0.57.4
react-native-maps: 0.22.0

**Comment by nodexii** [comment] 2018-11-23 08:54
For me 

> My issues fixed by using this step
> 
> 1. Using `"react-native-maps": "https://github.com/react-community/react-native-maps.git"` in my package.json and run `yarn install`
> 2. In my `android/build.gradle`, add:
> 
> ```
> ext {
>     buildToolsVersion = "27.0.3"
>     minSdkVersion = 16
>     compileSdkVersion = 27
>     targetSdkVersion = 26
>     supportLibVersion = "27.1.1"
>     googlePlayServicesVersion = "15.0.1"
>     androidMapsUtilsVersion = "0.5+"
> }
> ```
> May be you must adjust with your project
> 
> 1. In `android/app/build.grade` add `compile project(':react-native-maps')` in `dependencies` object
> 2. In `android/app/src/main/java/com/projectName/MainApplication.java` edit in getPackages() function so it look like this
> 
> ```
> @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new MapsPackage()
>       );
>     }
> ```
> I fixed my issue by adding this last step. I got the `AIRMap` error when I forget to adding `new MapsPackage()` in my MainApplication.java
> 
> May be you must adjust with yout ios setting, btw I didn't develop in ios 😄

This fixed my, I forgot to add new MapsPackage() to getPackages after RNN install. what a painnnnn 🗡

**Comment by rollrodrig** [comment] 2018-12-10 17:22
> My issues fixed by using this step
> 
> 1. Using `"react-native-maps": "https://github.com/react-community/react-native-maps.git"` in my package.json and run `yarn install`
> 2. In my `android/build.gradle`, add:
> 
> ```
> ext {
>     buildToolsVersion = "27.0.3"
>     minSdkVersion = 16
>     compileSdkVersion = 27
>     targetSdkVersion = 26
>     supportLibVersion = "27.1.1"
>     googlePlayServicesVersion = "15.0.1"
>     androidMapsUtilsVersion = "0.5+"
> }
> ```
> May be you must adjust with your project
> 
> 1. In `android/app/build.grade` add `compile project(':react-native-maps')` in `dependencies` object
> 2. In `android/app/src/main/java/com/projectName/MainApplication.java` edit in getPackages() function so it look like this
> 
> ```
> @Override
>     protected List<ReactPackage> getPackages() {
>       return Arrays.<ReactPackage>asList(
>           new MainReactPackage(),
>             new MapsPackage()
>       );
>     }
> ```
> I fixed my issue by adding this last step. I got the `AIRMap` error when I forget to adding `new MapsPackage()` in my MainApplication.java
> 
> May be you must adjust with yout ios setting, btw I didn't develop in ios 😄


LOL
It worked for me

**Comment by MuhammadNayabButt** [comment] 2019-09-23 08:30
I tried lot of things and in the end I realised not one answer was enough. So I compiled and write it into an article . I tried my best and hope it will help everyone
https://medium.com/@nayabbutt1/google-maps-in-react-native-ios-application-3e27eece15b4

**Comment by zeroidentidad** [comment] 2019-10-10 04:20
see https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md

**Comment by Gregory-Canonne** [comment] 2019-11-30 14:34
Where you install react native map, react native keep the old build. You must remote iOS/build and node modules and re-build your application ! In new version builded there are AirMap ! Enjoy

**Comment by debbagh185** [comment] 2020-01-31 23:20
I had the same issue and I fixed it by the folowing steps : 

1) Go to your android/settings.gradle file and add :
```
include ':react-native-maps'
project(':react-native-maps').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps/lib/android')
```
2) Go to your  `android/app/src/java/MainApplication.java` file and add :

`import com.airbnb.android.react.maps.MapsPackage;`

And add `new MapsPackages()` to getPackages() that return a list, something like this : 

```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          ...
          new MapsPackage(),
          ...
      );
    }
```

3) Go to your  android/app/build.gradle file and add : 

 `compile project(':react-native-maps')` to dependencies block. 

4) Finally, go to your  android/build.gradle file and add :
 ```
 ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "15.0.1"
        **androidMapsUtilsVersion = "0.5+"**
    }
```
**I hope this will help you, I am waiting for your feedbacks**

**Comment by dwijonarko** [comment] 2020-02-27 04:15
Anyone have fix this issue for RN version 0.60 ?

**Comment by debbagh185** [comment] 2020-03-10 16:44
try this https://github.com/react-native-community/react-native-maps/issues/2495#issuecomment-580953357

**Comment by hashedIngineer** [comment] 2020-04-20 18:35
> @vemundeldegard put this in your package.json
> ` "react-native-maps": "https://github.com/react-community/react-native-maps.git",` and run `npm install`

why

**Comment by LPitonakova** [comment] 2020-05-07 16:33
If you followed all instructions on the react-native-maps properly, the way to fix this issue is simply to uninstall the app from your device / simulator, then re-running it.

This is a general advice when installing new pods.

**Comment by toplongguodev** [comment] 2020-08-19 06:22
nothing works for me, anyone can help?
I am working on android version.

**Comment by yuukiii** [comment] 2020-09-16 05:25
This works for me: 
1. `npm install react-native-maps@latest --save`
2.  `react-native link react-native-maps` 
For IOS
   1.  `cd ios`
   2. `pod install`
For Android
  1. `gradle clean`

**Comment by ciaranmccaughey** [comment] 2021-01-19 10:29
What worked for me was using yarn instead of npm.

I ran `yarn add react-native-maps -E `instead of `npm install react-native-maps`.

The package was missing under node_modules folder, using yarn did the trick.

Then `cd ios` `pod install`

**Comment by samchidi2005** [comment] 2021-05-29 05:59
I got the same error but fix it. In android/build.gradle, set minSdkVersion value to 22

**Comment by moustafahelmi96** [comment] 2022-05-19 14:39
try to pod install

**Comment by IbthajSami** [comment] 2023-10-23 19:21
> For me manually linking in iOS was the solution, as for the android, it works by default. react-native: 0.57.4 react-native-maps: 0.22.0

No it doesn't for me!!
