### ISSUE TITLE
Incorrect longitude with PROVIDER_GOOGLE on IOS devise

### ISSUE THREAD

**Issue by theKulak123** [react-community/react-native-maps#2565] opened 2018-10-29 10:43 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.56.0
react: 16.4.1
react-native-maps: 0.22
platform: Ios

### Steps to Reproduce

Move map from -120 longitude to 140 longitude

### Expected Behavior

onRegionChange returns region.longitude [-120, ..., -145, ..., -160, ..., -175, ..., 175, ..., 165, ..., 140]

### Actual Behavior

onRegionChange returns region.longitude [-120, ..., -145, ..., 210, ..., 190, ..., 170,  ..., 165, ..., 140]

### Reproducible Demo
```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import MapView, { PROVIDER_GOOGLE } from 'react-native-maps'

export default class App extends React.Component {
  state = { longitude: -120 }

  initialRegion = {
    latitude: 40,
    longitude: -120,
    latitudeDelta: 70,
    longitudeDelta: 70,
  }

  onRegionChange = region => {
    this.setState({ longitude: region.longitude })
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.text}>{this.state.longitude}</Text>
        <MapView
          style={styles.map}
          initialRegion={this.initialRegion}
          onRegionChange={this.onRegionChange}
          provider={PROVIDER_GOOGLE}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  text: { fontSize: 17, alignSelf: 'center', marginTop: 30, marginBottom: 20 },
});
```

**Comment by rborn** [comment] 2018-10-29 11:35
please update the issue to follow the template or I'll close it

**Comment by compojoom** [comment] 2018-11-13 10:07
@rborn - I think that this issue is duplicate of https://github.com/react-community/react-native-maps/issues/2087

**Comment by rborn** [comment] 2018-11-13 12:05
Duplicate of #2087 as per https://github.com/react-community/react-native-maps/issues/2565#issuecomment-438208998

**Closed by rborn** 2018-11-13 12:05 UTC
