### ISSUE TITLE
missing: react-native@0.51.0, required by react-native-maps@0.19.0

### ISSUE THREAD

**Issue by Barani-SBK** [react-community/react-native-maps#1948] opened 2018-01-07 09:19 UTC
After installing **react-native-maps@0.19.0** i am unable to start my npm because its looking for  **react-native@0.51.0.**How to resolve this ? 
Thanks !

![image](https://user-images.githubusercontent.com/25802419/34648131-dd66f41c-f3b9-11e7-8c8f-2b56414ae869.png)

After installing react-native@0.51.0.
![image](https://user-images.githubusercontent.com/25802419/34649725-84f6f2ca-f3da-11e7-9186-c8568287f17f.png)

its showing as invalid

![image](https://user-images.githubusercontent.com/25802419/34649728-9ba5d018-f3da-11e7-83f4-af56b097f2ea.png)

and these file are missing error are appearing now.

![image](https://user-images.githubusercontent.com/25802419/34649736-cc20adf8-f3da-11e7-916e-93088b41e52c.png)

**Comment by timotew** [comment] 2018-01-07 13:18
@Barani-SBK please check to see if your react-native is up to date.
As stated on the README! 

> Due to the rapid changes being made in the React Native ecosystem, we are not officially going to support this module on anything but the latest version of React Native.

**Comment by timotew** [comment] 2018-01-07 15:30
@Barani-SBK  please share the project `package.json` file.
Also, please make a new comment instead of updating the existing comment so that we'll get notified.

**Comment by Barani-SBK** [comment] 2018-01-07 17:38
@timotew yeah sure i will do that ..attached the file
[package.zip](https://github.com/react-community/react-native-maps/files/1610002/package.zip)

**Comment by timotew** [comment] 2018-01-07 23:09
@Barani-SBK I couldn't download the file,  paste here i.e
`
(result)=>{
result * 4
}
`
surround your code with    \`   sign to make it stand-out.

**Comment by alvelig** [comment] 2018-01-07 23:44
`npm i -S react-native@0.49`

**Comment by alvelig** [comment] 2018-01-07 23:45
That is why the template requires a reproducible example.

**Comment by alvelig** [comment] 2018-01-07 23:50
```
npm remove -S react-native
npm i -S react-native
```

The problem is in your package.json:
```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-map": "0.0.1",
    "react-native-maps": "^0.19.0"
  }
}
```

**Comment by rborn** [comment] 2018-01-08 15:41
@Barani-SBK I will close the issue for now (missing issue template, but I appreciate the amount of the information you added though 😊). 
Please check the suggestions and if it's not working, update the issue following the template and ping me to  reopen.

**Closed by rborn** 2018-01-08 15:41 UTC
Labels: NO ISSUE TEMPLATE

**Comment by pankaja92** [comment] 2018-01-18 13:59
I'm having the same issue.

This is my package.json . (I created the app using [create-react-native-app](https://github.com/react-community/create-react-native-app)

```
{
  "name": "helpwithplaces",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.9.0",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-maps": "^0.19.0"
  }
}

```

And I'm getting the same error as the guy posted this issue. 

In my project folder when I run `npm ls` I'm getting this at the end.

`**npm ERR! peer dep missing: react-native@0.51.0, required by react-native-maps@0.19.0**
`

**Comment by rborn** [comment] 2018-01-18 14:19
@pankaja92 you use it with expo, and they have "their own way" of doing things. but the error is clear : you have `"react-native": "0.50.3",` , try to update to 0.51

**Comment by pankaja92** [comment] 2018-01-18 14:39
@rborn I changed `react-native ` version in my package.json from `"0.50.3"` to `"0.51.0"`. And deleted `node_modules` folder and ran `npm install` . But still when I run `react-native --version` inside my app folder I get this
```
react-native-cli: 2.0.1
react-native: 0.50.3
```
It seems react-native hasn't update to 0.51.0 . So how can I update that ? I'm a newbie. Any help would be appreciated.

**Comment by rborn** [comment] 2018-01-18 14:41
Did you save package.json? (don't get me wrong, it happens to me a lot 😹)

**Comment by pankaja92** [comment] 2018-01-18 15:17
@rborn Thanks a lot. Fixed the issue. Something like u mentioned :)

**Comment by Bonobomagno** [comment] 2018-01-25 11:52
I have the same problem, but having react 16.2 and RN 0.53
any update on rn-maps?

**Comment by hekgarcia** [comment] 2018-02-01 04:00
Same problem with me, I have :
"react": "16.2.0", // latest
"react-native": "0.52.2", //latest not RC.
"prop-types": "^15.5.10"

**Comment by bmkopp10** [comment] 2018-02-13 23:40
I've got the same problem when trying to change my dependencies to match that of react native maps.   My map is working perfectly fine even though I'm getting a dependency error... so as of now I'm leaving it.  I'm not sure if that is bad?  I'm relatively new to react, I'm wondering if the react native maps  issue has anything to do with running react native link?

**Comment by Sainathhiwale** [comment] 2018-02-25 18:24
any one give the good solution

**Comment by fernandoem88** [comment] 2018-03-01 00:32
No one found a good solution for this issue? it's about 4 days that I am stuck looking for a solution.
I am using the latest version of expo (v25.0.0), react@16.2.0 and react-native@0.52.0.
running the command 
`create-react-native-app maps`
I have the following warning:
`warning "react-native-maps@0.19.0" has incorrect peer dependency "react@16.0.0".
warning "react-native-maps@0.19.0" has incorrect peer dependency "react-native@0.51.0".`

**Comment by hekgarcia** [comment] 2018-03-02 06:37
The only Solution I found was to downgrade react and react native Versions,
in the meantime Is solved

El 28/02/2018 6:32 p.m., "fernandoem88" <notifications@github.com> escribió:

No one found a good solution for this issue? it's about 4 days that I am
stuck looking for a solution.
I am using the latest version of expo (v25.0.0), react@16.2.0 and
react-native@0.52.0.
running the command
create-react-native-app maps
I have the following warning:
warning "react-native-maps@0.19.0" has incorrect peer dependency
"react@16.0.0". warning "react-native-maps@0.19.0" has incorrect peer
dependency "react-native@0.51.0".

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/react-community/react-native-maps/issues/1948#issuecomment-369432715>,
or mute the thread

**Comment by tingchaoxu** [comment] 2018-03-07 06:10
@hekgarcia It works for me. I just npm install whatever the version it needs and it works. For my issue it required react@16.0.0, react-native@0.51.0, svg and websql so here is what i did

npm install react@16.0.0
npm install react-native@0.51.0
npm install react-native-svg --save
npm install websql

**Comment by assue19** [comment] 2018-10-05 09:03
please help have been trying to  install reactive -native fro google maps  for 2 weeks with  no progress .Have bee geting the followiing
 npm install react-native-maps --save
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Student\pac  kage.json'
C:\Users\Student
`-- react-native-maps@0.21.0

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Student\packag  e.json'
npm WARN react-native-maps@0.21.0 requires a peer of react@^16.0 but none was in  stalled.
npm WARN react-native-maps@0.21.0 requires a peer of react-native@^0.51 || ^0.52   || ^0.53 || ^0.54 but none was installed.
npm WARN react-native-maps@0.21.0 requires a peer of prop-types@^15.0 || ^16.0 b  ut none was installed.
npm WARN Student No description
npm WARN Student No repository field.
npm WARN Student No README data
npm WARN Student No license field.

**Comment by Murunb1** [comment] 2020-04-24 18:00
rollbackFailedOptional: verb npm-session ae2960febc501433
