### ISSUE TITLE
Marker will randomly give option for directions or google maps

### ISSUE THREAD

**Issue by IamJoseph** [react-community/react-native-maps#1010] opened 2017-02-01 21:39 UTC
Honestly I'd prefer this to happen 100% of the time, but it seems to happen about 5%: Clicking on a marker gives option to get directions or open google maps.  Notice the two buttons in the lower right-hand corner of the screen 
![gmapsdirections](https://cloud.githubusercontent.com/assets/8108552/22527370/f8e4ac94-e89c-11e6-88b6-9b47965c909e.PNG)

**Comment by IamJoseph** [comment] 2017-02-01 21:44
I noticed I can force it by clicking on a marker and then rotating the screen with the marker still showing

**Comment by IamJoseph** [comment] 2017-02-01 23:26
Ok I did a lot of digging around and found out this was supposed to be a prop called toolbarEnabled.  It doesn't work as intended and if anyone reads this there is a hack here: #549

**Comment by MatthiasDebaere** [comment] 2017-02-08 05:55
Perhaps you can "center screen over marker on press" manually in the callback of setState? You could use one of the available [methods on the mapview component](https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#methods)

**Comment by iiitmahesh** [comment] 2017-03-24 06:35
@IamJoseph For me go google maps and directions not showing, if  possible can share that particular piece of code.

**Comment by alvelig** [comment] 2017-12-15 06:00
Duplicate of #549

**Closed by alvelig** 2017-12-15 06:00 UTC
