### ISSUE TITLE
componentDidMount doesn't call fitToElements on Android for zooming out to fit all the markers

### ISSUE THREAD

**Issue by clarktank** [react-community/react-native-maps#1799] opened 2017-11-18 02:04 UTC
What is the status of this bug? 
My code works fine on iOS, as soon as my app loads, it fits all the markers on the screen. But on Android, the same code doesn't fit all the markers on the screen.
```
export default class MapScreen extends React.Component {

 componentDidMount() {
  this.map.fitToElements(true);
 }

 render() {
  return (
   <View style={styles.container}>

    <MapView
      ref={ref => { this.map = ref; }}
      region={this.state.region}
      style={{ flex: 1 }}
      onRegionChangeComplete={this._onRegionChangeComplete}
    >
      {places.map(place =>
       <MapView.Marker
         key={place.placetID}
         coordinate={{ latitude: place.lat, longitude: place.lng }}
         title={place.name}
         description={place.address}
        />
     )}
    </MapView>

    <View style={styles.button}>
     <Button
       onPress={() => this.map.fitToElements(true)} 
       title="Search Here"
       color="#841584" 
     />
    </View>

   </View>
  );
 }
}
```
For a workaround, I created a button with an onPress handler that calls:
`onPress={() => this.map.fitToElements(true)} `
So as soon as I press the button the map zooms out to fit all the markers, and it works on both iOS and Android.

The problem is the **componentDidMount** call on android. Has this been fixed? or does anyone know a workaround for it?

**Comment by clarktank** [comment] 2017-11-18 02:06
As a workaround I manage to fix this issue by this:
```
componentDidMount() {
  setTimeout(() => this.map.fitToElements(true), 1000);
}
```
But I don't like my solution!

**Comment by alvelig** [comment] 2017-12-13 04:24
Duplicate of #1149

**Closed by alvelig** 2017-12-13 04:24 UTC

**Comment by clarktank** [comment] 2017-12-14 00:23
On Paper you are right. This is a duplicate of #1149 but onLayout is a bad solution.

1) Imagine you are building an app like Yelp, the first time that the map loads, **onLayout** puts all the markers on the map. But as soon as the user changes the **focus or region** to try new results, the map will **focus back** to the original point.

2) Also if your map loads as soon as the app opens, (I mean the MapScreen is your **first screen** to show up), this.map **ref** doesn't point to **mapView** and you get an undefined error! Even if you put this.map in the **componentDidMount** which indicates that the map has already rendered so therefore there should be a reference to it.

**Comment by alvelig** [comment] 2017-12-14 00:27
I don't claim onLayout is a solution. Just merging tickets to clean up and then have a roadmap.

Don't use layout. See how I manage setting user location: https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
The same logic can be used in your case.

**Comment by clarktank** [comment] 2017-12-14 01:50
I have solved this already by using a similar approach. But honestly, I don't like this solution, where you have to hardcode the initialregion. 

The following should be the right approach 

```
render() {
  if(!this.state.region) {
    return null;
  }

  return (
    ...
  )
}
```

The Mapview shouldn't render before initialregion is set, but it does and that is why you get an undefined error.
