### ISSUE TITLE
Android: MapView.Callout - seems to be clickable with touch feedback

### ISSUE THREAD

**Issue by jeveloper** [react-community/react-native-maps#322] opened 2016-06-24 01:51 UTC
using 0.6.0

It appears that only in android, custom callout content will be clickable. So its impossible to add things like switch or element.

Anyone know a way to around this?

Thanks

```
<MapView.Callout tooltip={true} flat={true}>
              <View>
              <Switch onTintColor='#a4cf5f'/>

                <Text style={{ color: '#fff' }}>This is a custom callout bubble view</Text>

              </View>
            </MapView.Callout>
```

**Comment by esutton** [comment] 2016-08-05 14:26
Same problem.  iOS works fine.

- On Android, any touch anywhere in the callout, highlights the *entire* callout.  
- On Android I cannot activate either the TextInput or the button?
- On Android, the callout layout is not right.  I had to remove a flexDirection: 'row' on Android.

```
  "dependencies": {
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-image-picker": "^0.21.4",
    "react-native-maps": "^0.4.2",
  }
```

<img width="267" alt="screen shot 2016-08-05 at 9 10 53 am" src="https://cloud.githubusercontent.com/assets/6115047/17439278/dff6e5a0-5aec-11e6-985a-9e82fd57e6a0.png">

**Comment by jeveloper** [comment] 2016-08-05 15:49
Same thing with maps 0.7 as well.
May need someone with android (java) experience to add a property to disable touch behaviour on that View that wraps custom elements

**Comment by johnryan** [comment] 2016-08-30 14:26
@jeveloper Did you find any fix for this? If not i'll look into the java end and see if I can figure it out.

**Comment by jeveloper** [comment] 2016-08-30 14:31
@johnryan i had asked someone with more android java experience, they seem to think its definitely in that implementation.
It'd be great to remove OnPress and other handlers , perhaps if its not present, the View can be used. 
Sorry no work around, its just not implemented.

**Comment by johnryan** [comment] 2016-08-30 14:43
Ok, i'll see if I can submit a PR to implement that behavior

**Comment by jeveloper** [comment] 2016-08-30 16:28
Thanks , if you're ever in Toronto, coffee and treats on me!
Strangely IOS has full support for custom <view> and controls e.g. switch to be used in a marker callout.

**Comment by johnryan** [comment] 2016-08-30 16:56
Ha, i'll take that deal, and yea I noticed. I implemented on iOS first and and now doing a run through of all the things that don't work as expected on android. Stay tuned!

**Comment by bleonard** [comment] 2016-10-03 04:27
I noted something interesting when I came across this. using the inspector (on Android) doesn't allow you to select the callout or any views in it. You can only select the entire map. This suggests that somehow touches are handled differently in the implementation.

**Comment by johnryan** [comment] 2016-10-03 13:33
Yea, it seems that the android MapView API doesn't support handling touches on subviews of the callouts. It looks like there are some (hacky) ways of adding support for touches inside a callout but it is more complicated that I would have thought.

**Comment by zolrath** [comment] 2016-12-04 00:09
From that StackOverflow post I see that a third party Android Library has been created for interactive map callouts https://github.com/Appolica/InteractiveInfoWindowAndroid
It'd be great if react-native-maps had iOS/Android parity in Callout interactivity!

**Comment by samer** [comment] 2017-06-04 10:01
Has anyone else run into this? I'm facing the same problem and I am wondering if someone has found a solution. To summarize: custom callouts on Android can't have sub-elements that are tappable, the whole callout acts like one big button.

**Comment by stuharvey** [comment] 2017-06-27 17:31
@samer Also still having this issue. Will let you know if I find a workaround.

**Comment by Ruzo** [comment] 2017-08-19 14:47
Just ran into this issue. Hope it gets popular enough to encourage a fix.

**Comment by jorgutdev** [comment] 2017-09-09 18:47
Same thing, please update this issue if anyone finds someway to do this.

**Comment by namnh240795** [comment] 2017-09-15 07:16
Having the same issue.

**Comment by efistokl** [comment] 2017-09-21 17:48
Me either. It is still unresolved. Sad(

**Comment by jorgutdev** [comment] 2017-09-22 07:59
Anyone wants to try make this functionality on our own? I open to colaborate

**Comment by alvelig** [comment] 2017-12-12 02:14
@jorgutdev https://stackoverflow.com/questions/14123243/google-maps-android-api-v2-interactive-infowindow-like-in-original-android-go/15040761#15040761

See #49 and #135.

I suggest those who want that just create a view above the map and have your buttons there

**Closed by alvelig** 2017-12-12 02:14 UTC
Labels: wontfix

**Comment by alvelig** [comment] 2017-12-13 01:22
#1556 an enhancement issue for that

**Comment by hegelstad** [comment] 2018-04-16 19:39
@alvelig I am trying to create a view above the map where my button**s** are, however, I seem to be unable to the find position of the markers on the screen. Therefore I struggle to place my views correctly. Do you have any tips? So far I've tried marker's onPress but the position given is not the screen (x,y), the same applies for map's pointFromCoordinate.

**Comment by alvelig** [comment] 2018-04-16 19:55
@hegelstad Can you give a use case for what you are trying to achieve? I don't quite get what you are going to do

**Comment by hegelstad** [comment] 2018-04-16 20:01
This is what I'm aiming for (Expected behavior):

<img width="216" alt="screen shot 2018-04-16 at 21 58 50" src="https://user-images.githubusercontent.com/6997343/38831987-6399b448-41c1-11e8-8739-aa2c4b0f1efb.png">

A custom view beneath the marker with 1-x time periods.
The three periods of time (in this example) should be touchable and returning some values.

Actual behavior:

The custom view with time periods isn't positioned correctly. I cannot find the correct coordinates for the markers relative to the top left corner of the map.

**Comment by alvelig** [comment] 2018-04-16 20:29
It won't work as you expect. Android won't allow you to have several buttons. As any map annotation is an image. 
I recommend you show a modal or a bottom bar after marker press something like this: 
<img width="185" alt="screen shot 2018-04-16 at 5 28 13 pm" src="https://user-images.githubusercontent.com/4231544/38833384-b97f060e-419b-11e8-88de-036c9799f1b4.png">

**Comment by hegelstad** [comment] 2018-04-16 20:35
What are the position coordinatws returned by marker onPress? What are they relative to? Are there any dummymarkers used by GM that could be used to calculate relative distance from top-left of the screen?

I really cannot envision a good User experience placing any of the options below the map. :-(

**Comment by alvelig** [comment] 2018-04-16 20:39
@hegelstad you probably will have to change from GM then.

An alternative would be to center map on marker press and show your modal above the map, then if map region changes make the modal disappear.
