### ISSUE TITLE
Marker Oversize when App is released

### ISSUE THREAD

**Issue by felangga** [react-community/react-native-maps#1418] opened 2017-06-20 05:58 UTC
Maps marker works fine on debug mode, but when I try to release the apps, the marker size is changed even with the same mobile phone I use.

**Comment by MeganGilligan1** [comment] 2017-08-15 08:51
@felangga did you manage to find a fix for this?

**Comment by felangga** [comment] 2017-08-15 08:56
Yes, I create Image tag inside MapView.Marker instead using it's image properties.
```
<MapView.Marker
                                                        ref={marker.key}
                                                        key={marker.key}
                                                        id={marker.id}
                                                        coordinate={marker.coordinate}
                                                        title={marker.title}
                                                        onDragEnd={(e) => this.onMarkerDrag(marker.id, e)}
                                                        onPress={(e) => this.onMarkerPress(e)}
                                                        draggable

                                                        >
                                                        <Image
                                                            source={require('./assets/marker_selected.png')}
                                                            style={{width:30, height:30}}
                                                            />
                                                        <MapView.Callout
                                                            tooltip={true}
                                                            onPress={(e) => this.onWaypointCallout(marker, this.state.markers)}
                                                            style={{ flex:1, width: 200}}
                                                            >
                                                            <Callout title={marker.title} address={marker.address} photo={marker.image}>
                                                                <Spinner isVisible={true} size={300} type={'Bounce'} color={'#EEEEEE'}/>
                                                            </Callout>
                                                        </MapView.Callout>
                                                    </MapView.Marker>
```

**Comment by alvelig** [comment] 2017-12-13 02:41
See #1476

**Comment by alvelig** [comment] 2017-12-13 02:42
Duplicate of #1422

**Closed by alvelig** 2017-12-13 02:41 UTC
