### ISSUE TITLE
onRegionChangeComplete is called multiple times during first displaying of the map

### ISSUE THREAD

**Issue by programmersharp** [react-community/react-native-maps#134] opened 2016-03-15 09:29 UTC
onRegionChangeComplete is called several times (2 times as far as I see) during first displaying of the map.

**Comment by bbk1985** [comment] 2016-03-30 10:58
I'm on Android and it seems to be called continuously.

`  constructor(props) {
    super(props);
    this.state = {
      region: {
        latitude: this.props.coords.latitude,
        latitudeDelta: 0.01,
        longitude: this.props.coords.longitude,
        longitudeDelta: 0.01,
      }
    }
  }

  render() {
    return (
      <MapView
        style={styles.map}
        showsUserLocation={true}
        region={this.state.region}
        onRegionChangeComplete={(region)=>{console.log(region); this.setState(region);}}
      >
        <MapView.Marker title='im here' coordinate={{latitude: 0.5901152, longitude: 90.8215704,}}/>
      </MapView>
    );
  }`

**Comment by seanislegend** [comment] 2016-05-05 10:11
I also see that it is called multiple times when moving the map. I assume this is to do with the animation velocity and the region changes on deceleration?

**Comment by jsheets** [comment] 2016-07-14 15:35
On 0.7.1, I'm seeing `onRegionChangeComplete` called continuously (endlessly) on initial load, but as soon as I move the map at all, it stops permanently, even if I pan around more. The exact opposite of what I need.

Works fine on iOS.

Any updates on this? Seems like a bug somewhere in the native Android code...?

**Comment by jsheets** [comment] 2016-07-14 18:19
I figured out a workaround.

What seems to be happening is, when you pass the initialRegion into the `<MapView/>` on Android (unlike iOS?) it triggers an immediate `onRegionChangeComplete` event, with a slightly different region than the initialRegion (perhaps recalculated by Google Maps?). Until you update the map's `region` property with that final new region, it'll keep rapidly re-calling `onRegionChangeComplete`.

Things seem to work much better if I update the map's region in both `onRegionChange` and `onRegionChangeComplete`. Before I was updating it only in `onRegionChange`. I had assumed that the final region would be passed into both already, but perhaps not.

**Comment by ryanhomer** [comment] 2016-07-22 14:38
Thanks for that workaround! I'm not using `onRegionChange` at all, just `onRegionChangeComplete` and updating the state var I use for the map's region with the region parameter passed in to `onRegionChangeComplete` works!

**Comment by ryanhomer** [comment] 2016-07-22 14:44
However, even with this workaround, I still have an issue. I need to be able to determine if it was the **user's intervention** (panning/zooming the map) that caused the `onRegionChangeComplete` event to be triggered. Really, I only want the code in there to be called when the user has interacted with the map at least once. This way, once the user has interacted with the map, I don't change the region programatically anymore during a data refresh.

**Comment by ryanhomer** [comment] 2016-07-22 16:49
I've figured out the issue and have a possible fix but with the recent change using `compile 'com.airbnb.android:react-native-maps:0.7.1'` instead of `compile project(':react-native-maps')` I'm unable to get a local copy of this project running such that I can change the `.java` source files, test and submit a PR.

The issue lies in `AirMapView.java` in the `map.setOnCameraChangeListener` statement. When the map is initially loading, the `OnCameraChangeListener` event gets called one or more times. At this time, `isTouchDown` is `false`. Back in `MapView.js` in the `_onChange` function, `event.native.continuous` is `false` and therefore the `this.props.onRegionChangeComplete` function is called. We need `continuous` to be `true` before the user has actually started interacting with the map, then the value of `isTouchDown` thereafter.

@lelandrichardson I'm willing to submit a PR for this if you can tell me how to set up my local environment to NOT use the precompiled JAR files from the repo. But it's a small change so perhaps you guys can get it done on your end. Thanks!

**Comment by cinder92** [comment] 2016-12-05 03:15
+1 is not that fix for me...

**Comment by ricbermo** [comment] 2017-03-10 17:10
I think the issue is mostly related to the latitude and longitude deltas. I'm saying this because I had those as constants and I was only updating the values for lat and lng. Once I started updating the deltas the callback started firing just once until the next map drag

**Comment by telkandrew** [comment] 2017-09-13 02:39
Would you have any more clarification on how you're grabbing latitude and longitude deltas? I thought updateRegion would grab these values when you run it?

**Comment by AdrianBrown1** [comment] 2017-09-14 20:03
anyone run into a fix for this issue ??

**Comment by telkandrew** [comment] 2017-09-14 20:29
@AdrianBrown1 we haven't yet but it looks like can maybe use onRegionChange and debounce at a set time interval. I'll let you know if it works, keep me in the loop if you figure out anything too please!

**Comment by IjzerenHein** [comment] 2017-10-17 20:32
Guys, please try PR #1710, it fixes the hacky region-change code for Android

**Comment by alvelig** [comment] 2017-12-12 02:29
Hopefully it is fixed. Let me know if still persists.

**Closed by alvelig** 2017-12-12 02:29 UTC

**Comment by jyotishman** [comment] 2020-06-02 14:02
I fixed the problem  by this -


onRegionChange = (region) => {
    if(region.latitude.toFixed(6) === this.state.region.latitude.toFixed(6)
      && region.longitude.toFixed(6) === this.state.region.longitude.toFixed(6)){
        return;
    }

    this.setState({region});
}
