### ISSUE TITLE
marker zIndex ignoring other elements zIndex in rendering sequence

### ISSUE THREAD

**Issue by dbeliaev** [react-community/react-native-maps#983] opened 2017-01-20 12:07 UTC
marker zIndex ignoring callout zIndex in rendering sequence

**Comment by ngandhy** [comment] 2017-06-14 18:15
This might help?

https://github.com/airbnb/react-native-maps/pull/1405

**Comment by alvelig** [comment] 2017-12-05 00:15
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 05:03
Duplicate of #418

**Closed by alvelig** 2017-12-15 05:03 UTC
