### ISSUE TITLE
Performance regression on Android

### ISSUE THREAD

**Issue by rops** [react-community/react-native-maps#716] opened 2016-10-21 11:26 UTC
Did anyone notice a performance regression on Android after #548? Any interaction with the maps gets the screen very sluggish. 

I'll try to investigate more.

**Comment by kkgelu** [comment] 2016-10-26 12:44
Could it be this? https://github.com/airbnb/react-native-maps/pull/728

**Comment by rops** [comment] 2016-10-27 10:26
I've been seeing that too. Could be related. I'll test the patch and see if it get better

**Comment by alvelig** [comment] 2017-12-15 05:52
That's general performance as I see. Dupe of #741

**Closed by alvelig** 2017-12-15 05:52 UTC
Labels: performance
