### ISSUE TITLE
MyLocationButton is hidden until map is rotated

### ISSUE THREAD

**Issue by richardhuang09** [react-community/react-native-maps#644] opened 2016-10-04 00:22 UTC
The render function I'm using is as follows:

render() {
    return (
      <View style={Style.container}>
        <MapView style={Style.map}
          showsUserLocation
          followsUserLocation
          showsMyLocationButton
        />
      </View>
    );

The styles are as follows:

  container: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    backgroundColor: 'transparent',
    ...StyleSheet.absoluteFillObject,
  },

Please let me know if you've faced any similar issues with the "MyLocationButton".

**Comment by alvelig** [comment] 2017-12-14 05:05
Duplicate of #1033

**Closed by alvelig** 2017-12-14 05:05 UTC
