### ISSUE TITLE
Requiring unknown module "undefined".

### ISSUE THREAD

**Issue by jamesDZ** [react-community/react-native-maps#2071] opened 2018-03-08 11:46 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes
### Environment
  "react": "^16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-maps": "^0.20.1"

### Steps to Reproduce

1. create project using npm install -g react-native-cli
2. npm install -g yarn 
3. react-native init < AppName>
4. react-native start 
5. react-native run-ios
6. npm install react-native-maps --save
7. react-native link "used to link the dependencies"

again execute the appliction it is throwing this error. please find the screen shot.

### Expected Behavior
It should launch the map.

(Write what you thought would happen.)

### Actual Behavior
![simulator screen shot - iphone 6 - 2018-03-08 at 17 04 12](https://user-images.githubusercontent.com/772108/37149480-24b176a8-22f4-11e8-881d-9dda88bd537e.png)

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

![simulator screen shot - iphone 6 - 2018-03-08 at 17 04 12](https://user-images.githubusercontent.com/772108/37149094-c5f72ff0-22f2-11e8-86b0-1255c6d2c3e8.png)

**Comment by bbandydd** [comment] 2018-03-08 11:59
I am getting the same issue

**Comment by jamesDZ** [comment] 2018-03-08 12:10
are you able to resolve this issue. If yes can you please help me on this.

**Comment by rborn** [comment] 2018-03-08 12:18
@jamesDZ @bbandydd use the master from git please

**Comment by rborn** [comment] 2018-03-08 12:20
duplicate of https://github.com/react-community/react-native-maps/issues/2051

**Closed by rborn** 2018-03-08 12:20 UTC

**Comment by bharamalhusen** [comment] 2019-07-24 12:58
I have a same issue for updated react native project how to solve
```
{
  "react-native": "0.59.0",
 "react-native-maps": "0.25.0"
}

```
In Release Build of android i get this error in debug all working fine
**Requiring unknown module "undefined"**

**Comment by harrie006** [comment] 2019-08-20 12:19
I am also facing this issue in release build. Not using react-native-maps though. Using react native 0.59.
