### ISSUE TITLE
map markers generate from firebase

### ISSUE THREAD

**Issue by kingtross88** [react-community/react-native-maps#1644] opened 2017-09-13 23:44 UTC
Anyone can assist me with populating the map markers from addresses placed into firebase. I'm working on an app that ask users for their address. once a user puts in their address this information is placed into firebase under an "location" node and then within that node has info such as "title" and "address". I'm trying to pull all those locations into the map markers but having a difficult time. 

below is my listen for markers function.

listenForMarkers(markerRef) {
  markerRef.on("child_added", (dataSnapshot) => {
    var parkingSpots = [];
    dataSnapshot.forEach((child) => {
      parkingSpots.push({
        nickName: dataSnapshot.nickName,
        address: dataSnapshot.address,

      });
    });

    this.setState({
      newParking: parkingSpots,
    });
  });

  }

I also placed my code in my component will mount

 componentDidMount() {
      navigator.geolocation.getCurrentPosition(
      (position) => {
        region = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta:  0.00922,
          longitudeDelta: 0.00421,
          error: null,
        }
        this.setState({
        region
      }); 
    },
    (error) => this.setState({ error: error.message }),
    { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },

    );
      //used to listen for markers once the user geo location shows
       this.listenForMarkers(this.markerRef);
  }

How do i make it show in my map markers coordinates? Any help is greatly appreciated.

**Comment by alvelig** [comment] 2017-12-13 04:12
Duplicate of #1581

**Closed by alvelig** 2017-12-13 04:12 UTC
