### ISSUE TITLE
Have controlled MapView.Callout that is open/closed based on boolean prop?

### ISSUE THREAD

**Issue by acomito** [react-community/react-native-maps#1355] opened 2017-05-21 16:49 UTC
I have something similar to this:

![snap-map-example](https://cloud.githubusercontent.com/assets/12701635/26285726/236a17fc-3e23-11e7-8c1b-64ecab6bb023.gif)

I have the map animating as a user swipes through the carousel on the bottom, but I want to have the `MapView.Callout` open when it's the selected item, but all I see are methods (no props). Is there a clean way to do this? It's easy with, say, the marker color:
```

return (
   <MapView.Marker 
        pinColor={item._id === currentShopId ? 'blue' : 'red'}
    />
);
```

Is there an undocumented prop somewhere like calloutOpen that I can use as:
```

return (
   <MapView.Marker 
        calloutOpen={item._id === currentShopId}
    />
);
```

Airbnb has something like this in their production app. Maybe there's a simple way to do it with the methods that I'm overlooking though.

**UPDATE:**

Looks like maybe not possible with a custom callout:

https://github.com/airbnb/react-native-maps/issues/849

**Comment by anjali14garg** [comment] 2017-08-06 19:16
Hi @acomito ,
Did you found any solution for this callout funtionality

**Comment by alvelig** [comment] 2017-12-12 03:50
Duplicate of #275

**Closed by alvelig** 2017-12-12 03:50 UTC
