### ISSUE TITLE
showsMyLocationButton does not work on android

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-community/react-native-maps#993] opened 2017-01-24 01:18 UTC
Currently showsMyLocationButton does not appear unless the device is rotated or a change of the styling on the map is updated through hot-reload. Current device galaxy s5.

**Comment by MatthiasDebaere** [comment] 2017-01-24 11:32
Same problem as in #549 , map component needs to rerender.

**Comment by psam44** [comment] 2017-03-06 21:12
Please follow the issue on #1033.

**Comment by ashutosh-akss** [comment] 2017-03-08 18:07
Same Problem here, cannot see myLocationButton

**Comment by alvelig** [comment] 2017-12-14 04:10
Duplicate of #1033

**Closed** 2017-12-14 04:11 UTC
