### ISSUE TITLE
no attributes returned on onPress callback

### ISSUE THREAD

**Issue by dinukasal** [react-community/react-native-maps#1977] opened 2018-01-20 06:56 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

yes

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

onPress callback should return { coordinate: LatLng, position: Point }

### Actual Behavior

(Write what happened. Add screenshots!)
Nothing is returned on onPress event as well as onPanDrag.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by alvelig** [comment] 2018-01-20 12:42
Duplicate of #1286

**Closed by alvelig** 2018-01-20 12:42 UTC

**Comment by dinukasal** [comment] 2018-01-20 13:17
Thannks @alvelig !
