### ISSUE TITLE
Blank Map in Release

### ISSUE THREAD

**Issue by veeran-dev** [react-community/react-native-maps#2483] opened 2018-09-11 12:15 UTC
### Is this a bug report?
**No**

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

**Yes**

### Environment
"react": "16.3.1",
"react-native": "^0.55.3",
"react-native-maps": "^0.21.0",

### Steps to Reproduce

Just followed installation instruction

- added google api key
- android manifest permissions are fine
- styles are working
- Worked in debug mode when connected to Redmi A1 device and run react-native run-android

additionally added 
    abortOnError false in react-native-maps/lib/android/build.gradle

### Expected Behavior

A workable map

### Actual Behavior

Blank map with google logo

Do we need to have billing account for google map api keys?

**Comment by rborn** [comment] 2018-09-11 13:10
This is an api key issue, maybe the api key is limited or you didn't enabled it in google console.

**Comment by rborn** [comment] 2018-09-11 13:12
duplicate of #118 #1877

**Closed by rborn** 2018-09-11 13:12 UTC

**Comment by veeran-dev** [comment] 2018-09-12 10:44
@rborn I have billing account as well as already enabled api key but still the map is blank.
is there any way i can check my api is valid
is there any way i can debug the map issue in release apk

**Comment by rborn** [comment] 2018-09-12 11:15
@veeran-dev I believe the logcat should display some complains

**Comment by veeran-dev** [comment] 2018-09-12 13:02
@rborn Thank you

logcat says 
 Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.

Ensure that the "Google Maps Android API v2" is enabled.

But i don't see such option in google console

**Comment by rborn** [comment] 2018-09-12 13:40
Go to google console, select your project -> in the dashboard you will have 
![screen shot 2018-09-12 at 15 35 08](https://user-images.githubusercontent.com/406409/45428417-7a247680-b6a1-11e8-8bee-57b4fc710fac.png)

In that screen click the top left button "+ enable apis and services"
Search for maps, enable android and or ios and it will look like this after you enable it


![screen shot 2018-09-12 at 15 31 07](https://user-images.githubusercontent.com/406409/45428253-2580fb80-b6a1-11e8-9c32-17a1446c7de9.png)

Go to manage and be sure the api key in Credential tabs is the one you use and is not restricted (for now). Once you make it work you can secure it by restricting it to your platform and app following the instructions on screen.

**Comment by veeran-dev** [comment] 2018-09-12 13:57
@rborn yes, i have already enabled it and i also created billing account.

**Comment by rborn** [comment] 2018-09-12 13:59
@veeran-dev same api key in AndroidManifest.xml ?

**Comment by veeran-dev** [comment] 2018-09-12 14:04
@rborn yes, same api key in  AndroidManifest.xml and i genereated apk as per below mentioned guide 
https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by rborn** [comment] 2018-09-12 14:44
no idea, it's definitely an api key issue  but I don't know what

**Comment by tangnv** [comment] 2018-11-18 15:50
@rborn I created new API key based on Google Maps API Guide. That key worked well on web page, but when I put into `AndroidManifest.xml`, your map does not show anything, just a blank and Google text below. Any idea for that?

**Comment by gabrielmoncea** [comment] 2021-04-03 23:15
> @veeran-dev
> 
> Go to google console, select your project -> in the dashboard you will have
> ![screen shot 2018-09-12 at 15 35 08](https://user-images.githubusercontent.com/406409/45428417-7a247680-b6a1-11e8-8bee-57b4fc710fac.png)
> 
> In that screen click the top left button "+ enable apis and services"
> Search for maps, enable android and or ios and it will look like this after you enable it
> 
> ![screen shot 2018-09-12 at 15 31 07](https://user-images.githubusercontent.com/406409/45428253-2580fb80-b6a1-11e8-9c32-17a1446c7de9.png)
> 
> Go to manage and be sure the api key in Credential tabs is the one you use and is not restricted (for now). Once you make it work you can secure it by restricting it to your platform and app following the instructions on screen.

This should be referenced in the docs
