### ISSUE TITLE
how can i load street view of a location inside a view ?

### ISSUE THREAD

**Issue by jpca999** [react-community/react-native-maps#1767] opened 2017-11-07 18:52 UTC

**Comment by tonygentilcore** [comment] 2017-11-14 20:48
I haven't actually done this, but I believe you'd have to wire up the Google Places API: https://developers.google.com/maps/documentation/streetview/intro

That'd let you, for example, grab the street view image for a given lat/long/heading during `MapView`'s `onPress()` event.

**Comment by alvelig** [comment] 2017-12-13 19:13
Duplicate of #1217

**Closed by alvelig** 2017-12-13 19:13 UTC
