### ISSUE TITLE
Custom Marker View Callout Showing Under Marker View

### ISSUE THREAD

**Issue by chadwilken** [react-community/react-native-maps#662] opened 2016-10-07 20:19 UTC
We are using version 0.8.0 and when using a custom `MapView.Marker` and `MapView.Callout` views the callout is sometimes displayed under the marker and other times it displays correct.  I added some code and screenshots below to demonstrate what I mean.
#### Code

```
<MapView.Marker
        ref="marker"
        identifier={`${project.id}`}
        coordinate={coordinates}
        onPress={() => { this.setState({ selected: !this.state.selected }); }}
        onCalloutPress={() => { this.props.onProjectSelect(project); }}
      >
        <View>
          <Image source={mapPinIconOutline} />
        </View>
        <MapView.Callout style={styles.bubble}>

          {
            project.feature_photo_medium_url ?
              <Image
                source={{ uri: project.feature_photo_medium_url }}
                style={{ width: 100, height: 100, marginRight: 10 }}
              /> :
              null
          }

          <View style={{ flexDirection: 'row', alignItems: 'center' }}>
            <View>
              <Text style={styles.bubbleTitle}>{name}</Text>
              {
                address ?
                  <Text style={styles.bubbleSubTitle}>{address}</Text> :
                  null
              }
              <View style={styles.actionWrap}>
                <Image
                  source={cameraIcon}
                  style={{ tintColor: colors.mediumGray, marginRight: 4 }}
                />
                <Image
                  source={chevronRight}
                  style={{ tintColor: colors.mediumGray }}
                />
              </View>
           </View>
        </View>
    </MapView.Callout>
</MapView.Marker>
```

![overlap](https://dl.dropboxusercontent.com/u/13238118/Simulator%20Screen%20Shot%20Oct%207%2C%202016%2C%203.12.01%20PM.png)
![no-overlap](https://dl.dropboxusercontent.com/u/13238118/Simulator%20Screen%20Shot%20Oct%207%2C%202016%2C%203.12.05%20PM.png)

**Comment by esutton** [comment] 2016-12-06 18:22
+1 on iOS ( I have not yet tried Android recently )
```
react-native: ^0.38.1
react-native-maps: ^0.11.0
```
![callout-behind-marker](https://cloud.githubusercontent.com/assets/6115047/20937878/6851f774-bbae-11e6-9ed3-8cef21cbb4b5.png)

**Comment by ngandhy** [comment] 2017-06-14 18:16
Does this fix it? 
https://github.com/airbnb/react-native-maps/pull/1405

**Comment by alvelig** [comment] 2017-12-05 00:16
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by alvelig** [comment] 2017-12-15 04:57
Duplicate of #418

**Closed by alvelig** 2017-12-15 04:57 UTC
