### ISSUE TITLE
Custom Callout Will Not Appear if Custom Marker Is Used

### ISSUE THREAD

**Issue by joncursi** [react-community/react-native-maps#927] opened 2017-01-03 16:59 UTC
When I use the default pins, the custom callout below will show when the marker is pressed. However, when I add any sort of custom marker, in this example an image, the callout fails to appear at all.

```jsx
            <MapView.Marker
              identifier={marker.get('id')}
              onPress={this._onMarkerPress.bind(this, marker.get('id'))}
              ref={ref => { this[marker.get('id')] = ref; }}
            >
              <Image // image as custom marker
                source={
                  require('../../images/map-pin.png') // eslint-disable-line global-require
                }
                style={{
                  height: pinMarkerSize,
                  width: pinMarkerSize,
                }}
              />
              <MapView.Callout>
                <View
                  style={{
                    backgroundColor: 'red',
                    height: 300,
                    width: 300,
                  }}
                >
                  <Text>Callout here</Text>
                </View>
              </MapView.Callout>
            </MapView.Marker>
```

I have tried setting a `width` style attribute on MapView.Callout [as suggested here](https://github.com/airbnb/react-native-maps/issues/377#issuecomment-231728136) but the callout still does not appear. Any ideas?

react-native 0.39.2
react-native-maps 0.12.2

**Comment by vdesdoigts** [comment] 2017-01-12 15:28
I think the hitbox of the marker is not updated with the dimensions of the image.

**Comment by zhbanton** [comment] 2017-01-12 20:07
I've been wrestling with this issue for a while. I found that if I delay rendering the markers until the map has rendered (~500 ms), the callouts will appear normally.

**Comment by Drikoso** [comment] 2017-01-19 19:05
I'm struggling with this issue as well... 
zhbanton, would you mind pasting the code that creates the delay?

thanks in advance

**Comment by zhbanton** [comment] 2017-01-20 19:29
@Drikoso adapted from my code for the sake of being a little more succinct:

```
  const MAP_LOADING_DELAY = 300;

  constructor(props) {
    this.state = {
      isLoading: true
    }
  }

  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      window.setTimeout(() => {
        this.setState({
          isLoading: false
        });
      }, MAP_LOADING_DELAY);
    });
  }

  render() {
    return (
      <MapView
        ref='mapView'
        style={styles.map}
        rotateEnabled={false}
        pitchEnabled={false}
        showsUserLocation={true}>
          {this.state.isLoading ? <View /> : this.genMarkers()}
      </MapView>
    );
  }

  genMarkers() {
    return this.props.places.map((place) => {
      return (
        <MapView.Marker
          key={place.id}
          coordinate={{latitude: place.latitude, longitude: place.longitude}}>
          <MyCustomMarker {...place} />
          <MapView.Callout style={styles.callout}>
            <MyCustomCallout
              place={place}
              onPlaceSelect={this.props.onPlaceSelect.bind(this, place)} />
          </MapView.Callout>
        </MapView.Marker>
      );
    });
  }
```

Basically, this creates a bit of a lag between when the map is rendered and when the markers are rendered, which I don't think looks too bad. Probably could remove the InteractionManager depending on your nav pattern and fiddle with the MAP_LOADING_DELAY time. Lmk if this works!

**Comment by joncursi** [comment] 2017-02-25 07:35
I was able to fix this by manually making the callout hide and disappear, rather than relying on the Maps component to handle it for me. For example, when the user taps on a pin and you want to show the callout, you can open the callout in the callback for setState:

```jsx
    this.setState({
      activeMarkerId: markerId,
    }, () => {
      this[markerId].showCallout();
    });
```

**Comment by dbeliaev** [comment] 2017-03-02 11:43
add prop tooltip:
<Callout tooltip >
      <CustomCallout />
</Callout>

**Comment by 6farer** [comment] 2017-03-25 22:42
hm any proper fix for this yet?

**Comment by alvelig** [comment] 2017-12-12 03:59
Could not reproduce.

**Closed by alvelig** 2017-12-12 03:59 UTC
