### ISSUE TITLE
Gradient on Polyline

### ISSUE THREAD

**Issue by shukerullah** [react-community/react-native-maps#1626] opened 2017-09-08 12:24 UTC
How to apply gradient on Polyline

**Comment by ScholtenSeb** [comment] 2017-09-23 00:53
This might be helpful

https://stackoverflow.com/a/12934900

**Comment by IjzerenHein** [comment] 2017-12-21 15:15
Just added the PR for this on iOS/MapKit: #1911

**Comment by alvelig** [comment] 2017-12-21 18:19
Duplicate of #1088

**Closed by alvelig** 2017-12-21 18:19 UTC
