### ISSUE TITLE
Getting error on real device

### ISSUE THREAD

**Issue by BigPun86** [react-community/react-native-maps#165] opened 2016-04-06 08:04 UTC
Hey there! I am getting following error when i try to start the map on real device. On my emulator everything works perfectly....

![screenshot_20160406-100034](https://cloud.githubusercontent.com/assets/7880624/14309796/dfa1812c-fbde-11e5-98ef-f9c784844a0c.png)

This is what i found but i can´t really do anything with it

https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071

**Comment by zvona** [comment] 2016-04-12 10:27
We're getting the same error occasionally. Here's longer stack trace we're receiving:
```java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
	at android.view.SurfaceView.init(SurfaceView.java:207)
	at android.view.SurfaceView.<init>(SurfaceView.java:187)
	at maps.dz.aq.<init>(Unknown Source)
	at maps.dz.ao.<init>(Unknown Source)
	at maps.dg.u.<init>(Unknown Source)
	at maps.dg.u.a(Unknown Source)
	at maps.ei.ag.a(Unknown Source)
	at maps.ei.bu.a(Unknown Source)
	at maps.ei.r.a(Unknown Source)
	at com.google.android.gms.maps.internal.j$a.onTransact(:com.google.android.gms.alldynamite:66)
	at android.os.Binder.transact(Binder.java:387)
	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at com.AirMaps.AirMapView.<init>(AirMapView.java:71)```

**Comment by jrichardlai** [comment] 2016-04-12 14:18
Can you check your version of com.google.android.gms:play-services-base in your app? react-native-maps is using 8.4.0, can you set it to 8.4.0 to see if that fixes it?

**Comment by zvona** [comment] 2016-04-12 18:17
In build.gradle `compile 'com.google.android.gms:play-services-maps:8.4.0'`, which should be correct.

In our case, this crash seems to happen only on Sony Xperia devices, which are running on Android 6.0. There is similar context on the discussion here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071#c14

**Comment by christopherdro** [comment] 2016-04-14 18:14
@zvona Did you try any of the suggested fixes from the discussion.

https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071#c16
https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071#c18

**Comment by zvona** [comment] 2016-04-15 06:24
@christopherdro, yes. I tried to apply hardware acceleration in manifest to fix Xperia issues, but it didn't help.

**Comment by BigPun86** [comment] 2016-05-12 14:07
+1 any updates on this?

**Comment by heydabop** [comment] 2016-05-17 16:20
Looking at the issue thread, could it also be related to `MapsInitializer.initialize(context.getApplicationContext())` in [AirMapManager.java#70](https://github.com/lelandrichardson/react-native-maps/blob/master/android/lib/src/main/java/com/airbnb/android/react/maps/AirMapManager.java#L70)? It seems the issue was popping up for people when using the application context.

**Comment by zvona** [comment] 2016-05-20 11:03
What @heydabop wrote and what stack trace suggests, it sounds that could be the root cause for error.

The target devices are restricted to Sony Xperia devices with Android 6 installed. However, this audience is large enough to give bad reviews for our application in Play Store :(.

So if you have time to fix this using activity context, it'd really help.

Thanks in advance.

**Comment by yutin1987** [comment] 2016-06-03 07:11
+1,

Target devices follow:
Lenovo Z90/VIBE Shot (zoom_fdd)
Xperia Z5 (E6653)
Xperia Z3+ (E6553)	

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
	at android.view.SurfaceView.init(SurfaceView.java:207)
	at android.view.SurfaceView.<init>(SurfaceView.java:187)
	at maps.X.x.<init>(Unknown Source)
	at maps.X.v.<init>(Unknown Source)
	at maps.E.u.<init>(Unknown Source)
	at maps.E.u.a(Unknown Source)
	at maps.ag.ad.a(Unknown Source)
	at maps.ag.t.a(Unknown Source)
	at maps.ag.Q.a(Unknown Source)
	at vn.onTransact(:com.google.android.gms.DynamiteModulesB:66)
	at android.os.Binder.transact(Binder.java:387)
	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at com.AirMaps.AirMapView.<init>(AirMapView.java:71)
	at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:70)
	at com.AirMaps.AirMapManager.createViewInstance(AirMapManager.java:27)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:204)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:829)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:797)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:603)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5514)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Zidail** [comment] 2016-06-07 06:51
+1

Issue is also happening on:
One Plus Two (Oxygen Android 6.0 Beta)

**Comment by locly** [comment] 2016-06-07 15:50
I've got a fix using the activity context as suggested by others which works on the 0.4-stable branch and tested on an Xperia Z5 Compact running Android 6.0.

If you want to test the fix on a device:

1. Change react-native-maps in package.json to be `git://github.com/locly/react-native-maps.git#6d393fb6796deb4f8620533cee5c90cb8051d48f`

2. Change android/app/src/main/java/com//MainActivity.java to have `new AirPackage(this)` rather than just `new AirPackage()`.

If you could report on any success / failures that would help so that I can put it in the PR

**Comment by BigPun86** [comment] 2016-06-07 16:06
Great work!!! Works perfectly on my Sony Xperia Z5 Bond Edition

**Comment by jrichardlai** [comment] 2016-06-07 23:39
Thanks @locly a PR will be welcomed

**Comment by npomfret** [comment] 2016-06-20 09:26
I've been testing git://github.com/locly/react-native-maps.git#6d393fb6796deb4f8620533cee5c90cb8051d48f and it looks good.  Any chance of getting a release?

**Comment by lapcchan** [comment] 2016-07-18 16:01
we have this problem too, any compatible patch for RN0.29 and RN-maps 0.7.1?

**Comment by lapcchan** [comment] 2016-07-19 19:55
for RN 0.29, new AirPackage() is define inside MainApplication.java instead of MainActivity.java.
new AirPackage(this) is not working. any idea?

**Comment by Rpaixao** [comment] 2016-08-21 12:58
When i try to use locly solution, i get the following error:

![simulator screen shot 21 08 2016 13 57 07](https://cloud.githubusercontent.com/assets/1159505/17837289/2e427d0c-67a7-11e6-8939-79cfda705cb9.png)

Is there anyone with the same problem?

**Comment by spikebrehm** [comment] 2016-08-31 18:09
We think this may be fixed by this PR that was just merged: #449. Perhaps you can verify?

**Comment by zjaml** [comment] 2016-09-04 03:22
I'm having the same issue. Just tried the merged version, didn't work, the problem is still there.

HoursSpent += 3

RN: 0.32

MainActivity.java

```
import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "abc";
    }
}
```

MainApplication.java
```

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.airbnb.android.react.maps.MapsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new MapsPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by neacsugeorge** [comment] 2016-09-10 16:14
Hello @spikebrehm , 
It's not working.
Device: Oneplus Two ( ONE A2003 )
Android Version: 6.0.1
RN: 0.32
react-native-maps: 0.8.2

**Comment by DtCarrot** [comment] 2016-09-12 05:33
Hi there, I tried the merged version and it gave me the same error as well. 

Device: Sony Xperia Z5 
Android Version: 6.0
RN: 0.32.1
react-native-maps: 0.8.2

**Comment by alexHlebnikov** [comment] 2016-09-16 11:26
Have the same issue on Nexus 5, Android 5.1.1, RN 0.34.RC.0, react-native-maps 0.8.2.

**Comment by didaKtik** [comment] 2016-09-16 13:32
Same on Xiaomi Redmi Note 3 - Android 5.1.1, RN 0.33, react-native-maps 0.8.2.

**Comment by Paul776** [comment] 2016-09-18 10:38
Sorry not using this lib...  but I get the exact same error when I try to load a gmap in an overlay windows (from a Service)

this is the line that trigger the error

//"this" is the service
this.mapView.getMapAsync(this);

Full stack trade if it can help:

> java.lang.RuntimeException: Unable to create service com.package.MyService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference at android.app.ActivityThread.handleCreateService(ActivityThread.java) at android.app.ActivityThread.access$1800(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java) at android.os.Handler.dispatchMessage(Handler.java) at android.os.Looper.loop(Looper.java) at android.app.ActivityThread.main(ActivityThread.java) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference at android.view.SurfaceView.init(SurfaceView.java) at android.view.SurfaceView.(SurfaceView.java) at maps.V.x.(Unknown Source) at maps.V.v.(Unknown Source) at maps.D.v.(Unknown Source) at maps.D.v.a(Unknown Source) at maps.ad.ae.a(Unknown Source) at maps.ad.u.a(Unknown Source) at maps.ad.R.a(Unknown Source) at wc.onTransact(:com.google.android.gms.DynamiteModulesB:66) at android.os.Binder.transact(Binder.java) at com.google.android.gms.maps.a.e$a$a.a(Unknown Source) at com.google.android.gms.maps.MapView$a.a(Unknown Source) at com.google.android.gms.dynamic.e.a(Unknown Source) at com.google.android.gms.dynamic.c.a(Unknown Source) at com.google.android.gms.maps.MapView$b.g(Unknown Source) at com.google.android.gms.maps.MapView$b.a(Unknown Source) at com.google.android.gms.dynamic.b.a(Unknown Source) at com.google.android.gms.dynamic.b.a(Unknown Source) at com.google.android.gms.maps.MapView.a(Unknown Source)

**ONLY happening for XIAOMI and SONY devices !**

**Comment by alexHlebnikov** [comment] 2016-09-28 05:00
After update react-native-maps from master (after this PR: #589) the app is no longer crashes with this error.

**Comment by spikebrehm** [comment] 2016-09-28 16:46
Great! I will cut a new release.

**Comment by marseca** [comment] 2017-04-07 18:45
Hi!
I have this error on my Vodafone Smart Prime 7. 
Has anyone found a solution to this problem?

RN: 0.42.0
react-native-maps: 0.13.1

**Comment by iiitmahesh** [comment] 2017-05-05 13:20
Same Problem in Redme Note4 :+1:

**Comment by jeanregisser** [comment] 2017-05-05 14:29
Got the same problem from a Lenovo YT3-X50F user.
react-native: 0.43.0-rc.3
react-native-maps: 0.13.1

```
Android: 6.0.1
Android Build: YT3-X50F_S000118_170317_ROW
Manufacturer: LENOVO
Model: Lenovo YT3-X50F
Thread: main-1

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
	at android.view.SurfaceView.init(SurfaceView.java:207)
	at android.view.SurfaceView.<init>(SurfaceView.java:187)
	at com.google.maps.api.android.lib6.gmm6.vector.an.<init>(:com.google.android.gms.DynamiteModulesB:231)
	at com.google.maps.api.android.lib6.gmm6.vector.ai.<init>(:com.google.android.gms.DynamiteModulesB:163)
	at com.google.maps.api.android.lib6.gmm6.api.ao.<init>(:com.google.android.gms.DynamiteModulesB:389)
	at com.google.maps.api.android.lib6.gmm6.api.ao.a(:com.google.android.gms.DynamiteModulesB:349)
	at com.google.android.gms.maps.internal.eb.a(:com.google.android.gms.DynamiteModulesB:4048)
	at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:403)
	at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:308)
	at com.google.maps.api.android.lib6.impl.da.a(:com.google.android.gms.DynamiteModulesB:79)
	at com.google.android.gms.maps.internal.z.onTransact(:com.google.android.gms.DynamiteModulesB:66)
	at android.os.Binder.transact(Binder.java:387)
	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zzIL(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:93)
	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
	at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:603)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by the-simian** [comment] 2017-05-07 02:43
I am also getting this issue, here is my trace:
```
ResolutionOverride.java:56android.util.ResolutionOverride.<init>	
SurfaceView.java:207android.view.SurfaceView.init	
SurfaceView.java:187android.view.SurfaceView.<init>	
:com.google.android.gms.DynamiteModulesB:231com.google.maps.api.android.lib6.gmm6.vector.an.<init>	
:com.google.android.gms.DynamiteModulesB:163com.google.maps.api.android.lib6.gmm6.vector.ai.<init>	
:com.google.android.gms.DynamiteModulesB:389com.google.maps.api.android.lib6.gmm6.api.ao.<init>	
:com.google.android.gms.DynamiteModulesB:349com.google.maps.api.android.lib6.gmm6.api.ao.a	
:com.google.android.gms.DynamiteModulesB:4048com.google.android.gms.maps.internal.eb.a	
:com.google.android.gms.DynamiteModulesB:403com.google.maps.api.android.lib6.impl.az.a	
:com.google.android.gms.DynamiteModulesB:308com.google.maps.api.android.lib6.impl.az.a	
:com.google.android.gms.DynamiteModulesB:79com.google.maps.api.android.lib6.impl.da.a	
:com.google.android.gms.DynamiteModulesB:66com.google.android.gms.maps.internal.z.onTransact	
Binder.java:387android.os.Binder.transact	
Unknown:-1com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate	
Unknown:-1com.google.android.gms.maps.MapView$zza.onCreate	
Unknown:-1com.google.android.gms.dynamic.zza$3.zzb	
Unknown:-1com.google.android.gms.dynamic.zza$1.zza	
Unknown:-1com.google.android.gms.maps.MapView$zzb.zzbsp	
Unknown:-1com.google.android.gms.maps.MapView$zzb.zza	
Unknown:-1com.google.android.gms.dynamic.zza.zza	
Unknown:-1com.google.android.gms.dynamic.zza.onCreate	
Unknown:-1com.google.android.gms.maps.MapView.onCreate	
AirMapView.java:93com.airbnb.android.react.maps.AirMapView.<init>	
AirMapManager.java:62com.airbnb.android.react.maps.AirMapManager.createViewInstance	
AirMapManager.java:29com.airbnb.android.react.maps.AirMapManager.createViewInstance	
ViewManager.java:46com.facebook.react.uimanager.ViewManager.createView	
NativeViewHierarchyManager.java:218com.facebook.react.uimanager.NativeViewHierarchyManager.createView	
UIViewOperationQueue.java:149com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute	
UIViewOperationQueue.java:892com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations	
UIViewOperationQueue.java:865com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded	
GuardedChoreographerFrameCallback.java:32com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame	
ReactChoreographer.java:131com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame	
Choreographer.java:856android.view.Choreographer$CallbackRecord.run	
Choreographer.java:670android.view.Choreographer.doCallbacks	
Choreographer.java:603android.view.Choreographer.doFrame	
Choreographer.java:844android.view.Choreographer$FrameDisplayEventReceiver.run	
Handler.java:743android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:171android.os.Looper.loop	
ActivityThread.java:5417android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:726com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:616com.android.internal.os.ZygoteInit.main
```

**Comment by fqborges** [comment] 2017-05-11 14:41
Same here:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
at android.util.ResolutionOverride.<init>(ResolutionOverride.java:56)
at android.view.SurfaceView.init(SurfaceView.java:207)
at android.view.SurfaceView.<init>(SurfaceView.java:187)
at com.google.maps.api.android.lib6.gmm6.vector.an.<init>(:com.google.android.gms.DynamiteModulesB:231)
at com.google.maps.api.android.lib6.gmm6.vector.ai.<init>(:com.google.android.gms.DynamiteModulesB:163)
at com.google.maps.api.android.lib6.gmm6.api.ao.<init>(:com.google.android.gms.DynamiteModulesB:389)
at com.google.maps.api.android.lib6.gmm6.api.ao.a(:com.google.android.gms.DynamiteModulesB:349)
at com.google.android.gms.maps.internal.eb.a(:com.google.android.gms.DynamiteModulesB:4048)
at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:403)
at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:308)
at com.google.maps.api.android.lib6.impl.da.a(:com.google.android.gms.DynamiteModulesB:79)
at com.google.android.gms.maps.internal.z.onTransact(:com.google.android.gms.DynamiteModulesB:66)
at android.os.Binder.transact(Binder.java:387)
at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
at com.google.android.gms.maps.MapView$zzb.zzJz(Unknown Source)
at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
at com.google.android.gms.dynamic.zza.zza(Unknown Source)
at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:126)
at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:62)
at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:218)
at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:912)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:884)
at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:912)
at android.view.Choreographer.doCallbacks(Choreographer.java:673)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:900)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by iiitmahesh** [comment] 2017-05-15 07:32
Any Update ?? Workaround to this issue???

**Comment by jeanregisser** [comment] 2017-05-15 09:43
Updating to >= 0.14 should fix it.

See CHANGELOG for 0.14: https://github.com/airbnb/react-native-maps/blame/ca7eee1b59182ea02fd0f92b1cbbdc9bff7b9b8c/CHANGELOG.md#L29-L30

**Comment by iiitmahesh** [comment] 2017-05-15 10:33
@jeanregisser  This issue not resolving with v0.15..!

**Comment by fqborges** [comment] 2017-05-15 14:15
not fixed on version 0.14.0

**Comment by TalkingQuickly** [comment] 2017-05-19 16:12
Also seeing this in version 0.15.0 on the Alcatel Pixi

**Comment by jonesdar** [comment] 2017-06-02 16:31
I notice that the latest fix for this is to try switching contexts (between activity and application context) when one is deemed 'buggy' (i.e. is null or has null resources or configuration).
I'm not sure if it's a great fix as using the application context (when the activity is null) causes this error https://github.com/airbnb/react-native-maps/issues/1202
Is it possible that these problems are caused because react-native-maps doesn't really follow the lifecycle rules for MapView? It's supposed to be forwarding all the activity/fragment lifecycle methods (onPause, onResume etc.) to MapView. Instead it calls onCreate() and onResume() in the AirMapView constructor. If the activity is e.g. paused at that point I can imagine calling MapView.onResume() would cause the kind of problems we're seeing. Thoughts?
Note that I see regular AirMapView null crashes in two places - the constructor and onHostResume().

**Comment by joshuaferrara** [comment] 2017-06-19 16:35
My app is receiving the same trace as @fqborges 

Has there been any work in regards to this?

**Comment by fqborges** [comment] 2017-11-23 16:38
After updating to version 0.16.4, I stopped receiving those crash reports. It seems the issue is solved and can be closed.

Are you still experiencing any crashes related to this?

**Comment by BigPun86** [comment] 2017-11-23 17:56
Seems to be fixed! Thumbs Up!

**Comment by rborn** [comment] 2017-12-12 16:59
@BigPun86 @alvelig could we close the issue then ?

**Closed** 2017-12-12 17:00 UTC
