### ISSUE TITLE
Need Style for Marker image

### ISSUE THREAD

**Issue by MichelDiz** [react-community/react-native-maps#1167] opened 2017-03-27 02:40 UTC
The ` <image> ` from RN have bugs while updating the markes. We need something more "native" from the Map module.

P.S. Things like control the Size.

Best Regards

**Comment by mpakunderscore** [comment] 2017-03-30 22:47
https://github.com/airbnb/react-native-maps/issues/100

```
 <View style={styles.map}>
     {this.state.markers.map(marker => (
         <Image source={{uri: marker.image}} />
     ))}
     <MapView>
         {this.state.markers.map(marker => (
             <MapView.Marker
                 key={marker.id}
                 coordinate={marker.latlng}>
                 <Image source={{uri: marker.image}} style={{width: 42, height: 42}} />
             </MapView.Marker>
         ))}
     </MapView>
 </View>
```

**Comment by ericapply** [comment] 2017-04-03 17:55
Currently you can put Image component as children of Marker to add custom style.
However, you may run into this bug https://github.com/airbnb/react-native-maps/issues/100

**Comment by DiMaNacho** [comment] 2017-12-07 19:29
+1

**Comment by alvelig** [comment] 2017-12-07 21:22
Why do you need to change marker image size?
Could you be more specific on what exactly do you want to style? You know, that it's worth to fix Image bugs than to reimplement React for native image component, with all the limitations the standard marker layout has.

**Comment by alvelig** [comment] 2017-12-07 21:24
@christopherdro I think we can close it as it's old and out of scope of the library, nor in the roadmap or refers to bugs in other libs.

**Comment by MichelDiz** [comment] 2017-12-08 02:19
If you say to me that has another kind of solution better or replaceable I close it myself. Because I think this is necessary. The costumization option.

**Comment by MichelDiz** [comment] 2017-12-08 02:24
Why do you need to change marker image size?

I had tested at the time a map that I did in RN with this lib. And it featured distinct sizes in different simulators. And different smartphones. Some he burst and the others size he looked normal. So if you have anything that can keep the ratio of the marker would be great. Proportion is important.

**Comment by alvelig** [comment] 2017-12-08 21:32
@MichelDiz 
1. Yes, there is a solution and it's obvious and documented: just use ReactNative view within the Marker. If you have problems with RNImage elements these are this element's issues. You may find workarounds like prefetch image in this repo.
2. As far as I understand your problem, different sizes are due to the pixel depth of each phone. You have to use different dpi images (@2x, @3x on iOS, and mdpi, hdpi, xhdpi... in Android), as on different phones the same image will look different: https://facebook.github.io/react-native/docs/images.html 

So, you can't set image width in native marker. The image is used as is and that is documented native behavior.

**Closed** 2017-12-09 04:59 UTC

**Comment by SKempin** [comment] 2018-08-13 16:13
@alvelig as we cannot set the image width or height in the native marker, do I need to simply recreate the image at the different [pixel densities](https://facebook.github.io/react-native/docs/pixelratio#get) for the @2x and @3x images? For example, save the image at 480 DPI for @3x, and at 320 DPI for the @2x versions? 

I am trying to clarify this as I have tested the @3x image structure (as referenced [here](https://facebook.github.io/react-native/docs/images#static-image-resources)) which does select the @3x image correctly on my LG Nexus 5, but displays it at full size (300 x 300) rather than the intended 100 x 100 as there are obviosuly no size dimensions set on the native marker.

Recreating the image at the correct DPI for the @2x and @3x appears to work. Please see the screenshot below. 
![screenshot_20180813-165109_2](https://user-images.githubusercontent.com/10877466/44043874-d31aa694-9f1b-11e8-8cd2-c2d7982287d4.png)

**Comment by alvelig** [comment] 2018-08-13 17:48
@SKempin Check naming and pixels. It should work. You can try to check it in android emulators to see if this is device specific (it happens).

Naming should be according to this specs (see @4x for android): https://developer.android.com/images/screens_support/devices-density_2x.png

**Comment by SKempin** [comment] 2018-08-13 20:12
@alvelig This doesn't work without a `style` attribute, which obviously cannot be appleid to the native marker. 

Creating images at the relevant DPI's does work (as illustrated above) it seems, but simply creating the same image three times larger results in it displaying three times larger (as in the blue square on the example).

**Comment by alvelig** [comment] 2018-08-13 20:18
If you have a square image files like this:
```
image.png (100x100) 
image@2x.png (200x200) 
image@3x.png (300x300) 
image@4x.png (400x400) 
```
it MUST give you 100x100 picture on hdpi, xdpi, xxdpi and xxxdpi devices accordingly. 

If it doesn't, please make a test project to reproduce your problem and mention models and resolutions you've tried.

**Comment by SKempin** [comment] 2018-08-13 20:38
@alvelig This does not happen. I am using an LG Nexus 5 (real device). Unfortunately I don't have time to create a test project currently, but I experience the same issues with standard `Image` component in RN. If the width and height dimensions are not specified then the image displays at full size - so image@4x.png (400x400) would display at 400 x 400, instead of the intended 100 x 100. The only way to ensure it would display correct is to set the width and height on the image's `style` attribute.

**Comment by alvelig** [comment] 2018-08-13 20:43
So, first that's a react-native issue, not react-native-maps one. 

Second, I recently used the same technique for my project to have a complex marker with an image and it works perfectly. I bet that if you take time and make a simple project with one marker (it should take 15 minutes or so), I'll find a problem in your code. :)

And third, also test it on the emulator with corresponding resolution to see that it works (or doesn't and there .

**Comment by SKempin** [comment] 2018-08-13 20:45
@alvelig I will attempt to make a project tomorrow and share with you, thanks. 

Was the image a child of the marker or the prop of the marker in your project? Thanks

**Comment by alvelig** [comment] 2018-08-13 20:54
prop: 
```
import markerImg from '../../images/marker.png';
import androidMarkerImg from '../../images/marker-android.png';

/***
Size | name
5275 marker-android.png
17851 marker-android@2x.png
21757 marker-android@3x.png
30902 marker-android@4x.png
5885 marker.png
12293 marker@2x.png
21757 marker@3x.png
***/

<Marker
      identifier={`${shop.id}`}
      coordinate={{
        latitude: shop.location.lat,
        longitude: shop.location.lng
      }}
      image={Platform.OS === 'ios' ? markerImg : androidMarkerImg}
      onPress={goToShop(dispatch, shop.id)}
    >
<View style={{ height: 100, width: 100, alignItems: 'center', justifyContent: 'center'  }}>
  <Text>{shop.name}</Text>
</View>
</Marker>
```
I had to make 7 images (3 ios and 4 android) to fit this marker, because of differences in ios and android. But that was because of the complexity of the marker that's why I had to use image, otherwise I would have done it with views.

**Comment by SKempin** [comment] 2018-08-14 14:31
@alvelig I've now created the [demo repo](https://sjk1986@bitbucket.org/sjk1986/markers-demo.git) and I'm still getting the same results on my LG Nexus 5.

As you can see in the screenshot, the @3x image is correctly being chosen but it is displaying at 300 x 300, since the native marker cannot have a `style` attribute applied to make it display at 100 x 100. I have also manually inserted the 100 x 100 sized marker for comparison.

I haven't been able to test on any emulators as of yet.

Thanks and I look forward to seeing what results you get.

![nexus5](https://user-images.githubusercontent.com/10877466/44098020-f9aa4efc-9fd6-11e8-94aa-84c83fbab5f3.jpg)

**Comment by alvelig** [comment] 2018-08-14 15:03
@SKempin it doesn't let me open it :) Please, can you check permissions for the project?

**Comment by SKempin** [comment] 2018-08-14 15:06
@alvelig Please try again now - https://github.com/SKempin/markers-demo

Thanks

**Comment by alvelig** [comment] 2018-08-14 16:13
Add this marker:
```
<MapView.Marker
              key={3}
              title={"@3x image"}
              coordinate={{ latitude: 51.509, longitude: -0.15 }}
            >
            <View style={{ 
              borderWidth: 5, 
              borderColor: 'green', 
              backgroundColor: 'white',
              height: 100, 
              width: 100 }}>
              <Text>I'm a 100x100 box</Text>
            </View>
          </MapView.Marker>
```

See: 
<img width="400" alt="screen shot 2018-08-14 at 7 06 00 pm" src="https://user-images.githubusercontent.com/4231544/44103696-9be9e862-9ff5-11e8-83e6-eeb744043dce.png">

Analyse :)
See that your 100x100 image is 4 times smaller and the 400x400 on xxxhdpi is 100x100 (nearly). That is the effect I'm talking about. If you have a single image without @2x, @3x and @4x it will be 4 times smaller in xxxhdpi.

P.S. I'm not happy that the images are not exact as the box. But that's how they appear somehow on Android.

**Comment by alvelig** [comment] 2018-08-14 20:08
@SKempin Glad to help.
The original size should be pixel equal to @1x (hdpi)
@2x should be *twice* big each side - to fit 2x density (xhdpi)
@3x should be *triple* big each side compared to @1x  - to fit 3x density (xxhdpi)
@4x - 4 times larger then...

**Comment by pytyl** [comment] 2019-03-29 02:49
@alvelig thanks for your helpful responses. Isn't **_@1x_** for mdpi, **_@1.5x_** for hdpi, and so on? Or is PixelRatio something different? Here is reference to PixelRatio:
[https://facebook.github.io/react-native/docs/pixelratio](url)

<img width="428" alt="Screen Shot 2019-03-28 at 10 41 48 PM" src="https://user-images.githubusercontent.com/21296284/55205847-e3398a80-51aa-11e9-8162-b1ebcb8f1fed.png">

The whole numbers (**_@1x_**, **_@2x_**, **_@3x_**, **_@4x_**)How would we represent the decimal densities like an image for **_@1.5x_**, **_@3.5x_**? I am guessing we can't just store an image like image@1.5x.png.
