### ISSUE TITLE
MapView props not working: showsMyLocationButton, userLocationAnnotationTitle, showsCompass

### ISSUE THREAD

**Issue by carlitosspot** [react-community/react-native-maps#1263] opened 2017-04-21 18:37 UTC
I'm trying to use the properties I mentioned and none of them seem to work.

When I tap on the user location, the default title appears, "My Location". My custom title is never shown. 

`showsMyLocationButton` and `showsCompass` never get displayed.

I've tried in both iPhone and iPhone simulator.  
Here's my dev info:
- react 15.4.2
- react native: 0.42
- react native maps: 0.14.0

Here's how i'm initializing the MapView Component:
```javascript
const title = "You are here";
<MapView
        showsUserLocation={true}
        showsMyLocationButton={true}
        userLocationAnnotationTitle={title}
        showsCompass={true}
        style={styles.map}
        region={{
          latitude: coordinates.latitude,
          longitude: coordinates.longitude,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}
/>
```
Anyone else having a similar issue?

**Comment by mhaagens** [comment] 2017-04-22 09:52
Same here

**Comment by sonaye** [comment] 2017-04-27 00:51
If you use google as a provider `showsMyLocationButton` should work after this PR https://github.com/airbnb/react-native-maps/pull/1157. As for `userLocationAnnotationTitle` I can confirm the same issue, although it's not a deal breaker it's nice to have this kind of customization, I would prefer "You" over "My Location" for example.

**Comment by svenadlung** [comment] 2017-04-28 12:21
Same here. Any ideas when the fix will be updated to the master?

**Comment by vnhnhm** [comment] 2017-04-28 20:53
Same here.

**Comment by babenzele** [comment] 2017-04-30 18:11
Thanks @vnhnhm, that takes care of `userLocationAnnotationTitle`.

`showsMyLocationButton` and `showsCompass` definitely do not work for me either. They should be shown by default, but they're not shown even if they are set explicitly.

**Comment by supportclik** [comment] 2017-05-03 14:35
some issue.

**Comment by babenzele** [comment] 2017-05-12 02:24
I can find no reference to `showsMyLocationButton` or `MKUserTrackingBarButtonItem` in `react-native-maps`, so I'm pretty sure this hasn't been built yet for iOS. 

https://developer.apple.com/reference/mapkit/mkusertrackingbarbuttonitem

It kind of makes sense since AirBnB does not have a traditional use for mapping:

![img_4182](https://cloud.githubusercontent.com/assets/3578574/25979760/25c6aaf2-367f-11e7-8e71-1bae655a15ce.JPG)

**Comment by chapeljuice** [comment] 2017-06-01 17:08
None of the following are working for me:
`showsScale={true}`
`showsCompass={true}`
`showsPointsOfInterest={true}`
`showsBuildings={true}`

**Comment by nikoootine** [comment] 2017-07-18 06:15
+ 1

**Comment by RobTS** [comment] 2017-07-27 09:49
+1 having problems with showsMyLocationButton on Android, it's simply not there. Extruded buildings were working for me, though, at least in Berlin @chapeljuice

**Comment by chapeljuice** [comment] 2017-07-27 14:22
Yeah not sure what changed but I now see buildings and points of interest ... still no scale or compass though.

**Comment by IAmMarcellus** [comment] 2017-12-01 03:20
Anyone find a fix for this?  showsScale, showsCompass, and showsMyLocationButton aren't working for me.  I'm using an android device and Google Maps as a provider.

**Comment by alvelig** [comment] 2017-12-13 04:38
#1735 Compass is hidden when pointint to the north
#1332 for the showsMyLocationButton

For other props please open new issues mentioning platform and is it google or not for IOS

**Closed by alvelig** 2017-12-13 04:38 UTC

**Comment by kholiavko-roman** [comment] 2018-03-14 13:37
@alvelig I have the same issue on ios -  `showsUserLocation={true}` doesn't not show the button.

I tried  
```
showsScale={true}
showsCompass={true}
showsPointsOfInterest={true}
showsBuildings={true}
```

and also I using hack as in #1332 tread, but nothing helped me. 


I use rn version 0.52.
and plugin version react-native-maps 0.20.1. (Using Apple provider)

**Comment by soomrozaid** [comment] 2020-03-01 02:12
> None of the following are working for me:
> `showsScale={true}`
> `showsCompass={true}`
> `showsPointsOfInterest={true}`
> `showsBuildings={true}`

'showsBuildings' only works for Google Maps, since Apple Maps don't have that feature. Try adding 

import MapView, { PROVIDER_GOOGLE } from 'react-native';

and inside '<MapView' add provider={PROVIDER_GOOGLE} before region.

**Comment by MiguelNiblock** [comment] 2021-01-20 02:10
This is still an issue. These 4 don't work for me.

showsUserLocation={true}
showsMyLocationButton={true}
showsCompass={true}
showsScale={true}

**Comment by AD757** [comment] 2021-03-20 17:31
Is it working for anyone? 

This two doesn't work for me either:
showsUserLocation={true}
showsMyLocationButton={true}

But,
showsCompass={true} works on a real device.

**Comment by Demonbane18** [comment] 2021-04-05 14:22
same.. I already used the PermissionsAPI and it said it is already granted but for some reason no popup or location marker is shown

**Comment by chungkang** [comment] 2021-07-19 11:49
showsMyLocationButton={true}

This one also doesn't work for me.

**Comment by austinhutchison** [comment] 2021-11-18 05:07
`showsMyLocationButton={true}` on iOS only works with  `provider={PROVIDER_GOOGLE}` for me. Can't get a location button on Apple Maps.
