### ISSUE TITLE
Custom marker display wrong location

### ISSUE THREAD

**Issue by KhoaND290391** [react-community/react-native-maps#1939] opened 2018-01-05 08:26 UTC
My setting: 
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-maps": "^0.19.0",
    Simulator: Iphone 6 IOS 11

Please see the attached pictures 
The marker display in different location when i just changed the delta value of longitude and latitude.
With const longitude and latitude value.

![image](https://user-images.githubusercontent.com/11889035/34600966-97442a24-f22c-11e7-93eb-38bb4d1d04c3.png)
![image](https://user-images.githubusercontent.com/11889035/34600970-a0b3f792-f22c-11e7-9e1f-6a6bd0afdf98.png)
![image](https://user-images.githubusercontent.com/11889035/34600979-acb4cbfc-f22c-11e7-97ab-3f7aeec252d0.png)
![image](https://user-images.githubusercontent.com/11889035/34600992-b7b90e1e-f22c-11e7-971a-e0e51d4a2518.png)

and here is my code
![image](https://user-images.githubusercontent.com/11889035/34600891-49793b40-f22c-11e7-9d51-3d32dba0cd96.png)
event when zoom the map
![image](https://user-images.githubusercontent.com/11889035/34600918-652ce7a6-f22c-11e7-8db6-8a43d67fa496.png)

**Comment by alvelig** [comment] 2018-01-05 13:22
It's working as expected. What is your problem?

**Comment by alvelig** [comment] 2018-01-06 02:47
See if apple maps have the same issue. Looks like GoogleMaps issue. But to create a reproducible demo in simulator.

**Comment by rborn** [comment] 2018-01-08 15:47
@KhoaND290391 the code works fine, you have the `anchor` set to `[0,0]` which is the top-left corner of the marker which if you look more carefully at your images is in the same place (more or less in the middle of the 2 small one exit only roads).
You might want to try to set the anchor to [0.5, 0.5] 

I'll close the issue for missing the template (however you added a great amount of information 😊). If my suggestion doesn't work, please update the issue following the template and ping me to reopen.

**Closed by rborn** 2018-01-08 15:47 UTC
Labels: NO ISSUE TEMPLATE
