### ISSUE TITLE
Get coordinates of corners of visible map

### ISSUE THREAD

**Issue by Clcll** [react-community/react-native-maps#975] opened 2017-01-18 07:58 UTC
How to get coordinates of corners of visible bing map?

**Comment by DVassilev** [comment] 2017-01-18 12:26
Get the current region of the map, then add and remove the latitudeDelta to latitude and do the same with longitude. This will give you the coordinates of the corners.

**Comment by beerteam** [comment] 2017-07-14 04:35
Did you solve the problem?

**Comment by jDeppen** [comment] 2017-07-25 18:30
Related (no solution yet) https://github.com/airbnb/react-native-maps/issues/356

**Comment by alvelig** [comment] 2017-12-12 04:35
Duplicate of #356

**Closed by alvelig** 2017-12-12 04:35 UTC
