### ISSUE TITLE
Marker Anchor Inconsistencies

### ISSUE THREAD

**Issue by wbattel4607** [react-community/react-native-maps#1771] opened 2017-11-08 23:56 UTC
I'm using PROVIDER_GOOGLE on both iOS and Android with custom markers for each user on the map.

```
<Marker
    {...user}
    key={user.id}
    onLoad={() => this.forceUpdate()}
    coordinate={(user.location) ? user.location.coordinates : user.coordinate}
    anchor={{x: 0.5, y: 0.5}}
    zIndex={4}
    onPress={() => this.goToProfile(user)}>
    <View style={[styles.borderStyle, {borderColor: imageBorder, borderRadius: 50}]}>
    <Image
        style={styles.imageStyle}
        source={{uri: user.image, width: 50, height: 50}}>
    </Image>
    </View>
</Marker>
```

But sometimes the anchor doesn't apply- and I have no idea why. What makes this difficult to investigate is that it is inconsistent. Sometimes it works as desired, and sometimes it does this....

https://i.imgur.com/AVRMBic.gif

Some of the markers get anchored, and others do not- so when you zoom out, a user in Boston appears to be in Canada.

This seems to happen much more frequently when multiple markers are overlapping, as far as I can tell.

**Comment by wbattel4607** [comment] 2017-12-13 05:20
I reported this while using version 0.17.0. I'm now on 0.18.3 and the issue still exists. Any ideas?

**Comment by alvelig** [comment] 2017-12-13 07:01
Looks like you misunderstand `anchor`. 
It's positioning relative to the image. It's like {
  position: 'relative',
  top: 0.5, //50%
  left: 0.5 //50%
}

From docs:
```
The anchor point is specified in the continuous space [0.0, 1.0] x [0.0, 1.0], where (0, 0) is the top-left corner of the image, and (1, 1) is the bottom-right corner. The anchoring point in a W x H image is the nearest discrete grid point in a (W + 1) x (H + 1) grid, obtained by scaling the then rounding. For example, in a 4 x 2 image, the anchor point (0.7, 0.6) resolves to the grid point at (3, 1).
```

Or I did not get your idea, did I?

**Comment by alvelig** [comment] 2017-12-14 04:39
Duplicate of #867

**Closed by alvelig** 2017-12-14 04:39 UTC
