### ISSUE TITLE
Custom marker with Image won't render first time on Android

### ISSUE THREAD

**Issue by henrikra** [react-community/react-native-maps#924] opened 2017-01-02 14:13 UTC
When making custom `MapView.Marker` with children as prop to Marker like this:
```javascript
<MapView.Marker coordinate={coordinate}>
  <View source={styles.container}>
    <Image source={require('./my-image.png')} style={style.icon}>
    // other stuff here
  </View>
</MapView.Marker>
```
It does **not** render image on first render time on Android. 

But if i use Marker's image prop like this: 
```javascript
<MapView.Marker coordinate={coordinate} image={require('./my-image.png')}>
  <View source={styles.container}>
  // other stuff here
</MapView.Marker>
```
It does render on first time on Android too.

But I cant use second option because I have to set custom size to the image via styles. So either would be nice to be: 
1. able to style image which is passed by `image` prop OR
2. fix bug where image won't render on first try.

Also note that in order to notice the first render bug you have to actually TURN OFF the app and then back on. :) Tell me if you experience this too

**Comment by norbajunior** [comment] 2017-01-02 15:50
I'm having the same issue. I have also tried to pass the image as a prop to MapView.Marker however compromised the styles.

**Comment by gilbox** [comment] 2017-01-03 18:47
I believe it's happening for the same reason as the bug exhibited here:

https://github.com/airbnb/react-native-maps/pull/814

... the image is loaded async and when it's "ready" nothing forces an update. The reason this happens is because on Android custom markers are rendered by generating a bitmap. But when the image gets loaded nothing triggers the re-generation of the bitmap. The only thing that ever triggers the bitmap to regenerate currently is when there is a change in the view hierarchy.

**Comment by henrikra** [comment] 2017-01-03 21:16
Okay so is there is hacky fix to this at the moment? :D

**Comment by gilbox** [comment] 2017-01-03 21:52
@henrikra you could try forcing a view hierarchy change with the `Image` components `onLoad` prop. The way I forced that change in the example is by having some hidden text that changes value: https://github.com/airbnb/react-native-maps/pull/814/files#diff-36881e0ead965fdaf7cdcadb269a42cfR103

**Comment by bfarrgaynor** [comment] 2017-01-06 20:01
https://github.com/airbnb/react-native-maps/issues/882
https://github.com/airbnb/react-native-maps/issues/907

**Comment by bfarrgaynor** [comment] 2017-01-06 20:01
This issue has been reported a bunch of times recently. Definitely a bug being experienced by everyone.

**Comment by Jazz747** [comment] 2017-01-25 14:56
Yeap, could this be a priority  to fix since it is a big impact on the user experience?

**Comment by gilbox** [comment] 2017-01-25 19:55
You're welcome to fix it @Jazz747 ... like most commits to this particular repo, things improve when someone steps up to the plate. We currently use the workaround I mentioned since it's difficult to fix this bug.

**Comment by Jazz747** [comment] 2017-01-26 13:38
I'd like to but I have nowhere near experience and knowledge to try it since I've just started coding :/ @gilbox could you elaborate on how to "force a view hierarchy" in this particular case?

**Comment by gilbox** [comment] 2017-01-27 19:27
@Jazz747 I mean something *other than you marker* has to change in order to trigger your marker to render again. [Here is a concrete example of that](https://github.com/airbnb/react-native-maps/pull/814/files?diff=unified#diff-36881e0ead965fdaf7cdcadb269a42cfR103) ... when something else changes, it means that a component will re-render. The marker in question should be part of that view hierarchy, iow the marker should be in that component, or a descendent of that component.

**Comment by Jazz747** [comment] 2017-01-27 19:48
Yes, figured it out in the meantime :) calling state to switch a simple boolean variable linked to the markers to trigger the re-render. I've put it in componentDidMount() and it works. I'll try to pull the code and dig into it to try to better understand the complete mechanics of the render,

**Comment by vinceyuan** [comment] 2017-02-07 03:44
I can reproduce this issue on both emulator and real devices.

**Comment by sators** [comment] 2017-02-16 13:50
Using @gilbox's idea of having a hidden element that regenerates once loaded, this is a hack that I've come up with that works - one image is loaded, force a reload of the component which regenerates a random number in the hidden text element...BARF!  ...but works!  Need a fix!

```
<Image source={pin} onLoad={() => this.forceUpdate()}>
     <Text style={{width:0, height:0}}>{Math.random()}</Text>
</Image>
```

**Comment by seppemarotta** [comment] 2017-02-23 05:21
I have my Custom Marker function and i want to be able to give it a style to my image because it's original size it's 200 x 200. I've been struggling with this because when i try the image props from MapView.Marker, i can't resize my image. Can someone share me their temporal fix or their solution to this issue? 
I'm kind of new in RN , so i'm not able to find a way to make it work on Android. iOS it's working properly.
`
      return(
        <MapView.Marker
        key={location._id}
        coordinate={ {latitude: location.geometry.coordinates[0], longitude: location.geometry.coordinates[1]}}
        title={location.name}
        description={location.description}
        style={styles.marker}
        //Valores temporales
        anchor ={ {x:0.20, y : 0.5} }
          >
              <Image
                  source={img_marker}
                  style={{ width: 20, height: 20 }} // Valores Temporales
              />
        </MapView.Marker>
      )`

**Comment by shahonseven** [comment] 2017-03-01 15:37
I need to display image from the internet but had the same problem with Image component I ended up using WebView instead.

```
<MapView.Marker coordinate={coordinate}>
  <View source={styles.container}>
    <WebView source={{uri: 'https://...'}} style={{height: 200, width: 200}} />
    <Text>A Building</Text>
  </View>
</MapView.Marker>
```

<img src="https://cloud.githubusercontent.com/assets/372461/23466862/47ed852c-fed7-11e6-92b1-ee2793a88024.png" alt="screenshot_1488382308" width="200" />

**Comment by seppemarotta** [comment] 2017-03-03 16:58
@shahonseven how did you manage to show a custom image marker ? Your code seems to solve the issue with images inside the Callout, however i cant manage to show my custom image markers to android .

**Comment by shahonseven** [comment] 2017-03-03 18:37
@seppemarotta this is my code for custom image marker

```
<MapView.Marker coordinate={marker.coordinate} image={{uri: marker.icon}}>
  ...
</MapView.Marker>
```
<img src="https://cloud.githubusercontent.com/assets/372461/23563613/6251ce80-0082-11e7-9e68-5291e6f49f02.png" alt="screenshot_1488565622" width="200" />

but as mentioned [here](https://github.com/airbnb/react-native-maps/issues/924#issue-198340847), you cannot resize it via style. If you want to control the marker via style you probably should take a look [here](https://github.com/airbnb/react-native-maps/issues/924#issuecomment-275752139) and [here](https://github.com/airbnb/react-native-maps/issues/924#issuecomment-280334935).

```
<MapView.Marker coordinate={marker.coordinate}>
  <Image
    style={styles.customMarker}
    source={{uri: marker.icon}}
    onLoad={() => this.forceUpdate()}>
      <Text style={{width:0, height:0}}>{Math.random()}</Text>
  </Image>
</MapView.Marker>
```
<img src="https://cloud.githubusercontent.com/assets/372461/23563687/b0477a68-0082-11e7-9af3-c17f73fbc1f3.png" alt="screenshot_1488565683" width="200" />

<img src="https://cloud.githubusercontent.com/assets/372461/23563717/d5f81542-0082-11e7-8408-e1340a78f7ce.png" alt="screenshot_1488565689" width="200" />

**Comment by seppemarotta** [comment] 2017-03-03 19:13
@shahonseven Thanks a lot , i understand everything now! I'll give it a try . May i ask how much width and height does your custom marker image has ?

**Comment by shahonseven** [comment] 2017-03-04 18:48
@seppemarotta for my custom image marker, I set 100x100 and for the custom callout image I set 200x200.

**Comment by MathieuMailhos** [comment] 2017-03-18 20:49
Having this issue as well and it is a huge deal.

When adding an hidden <Text> or <View> inside the picture with a random element inside, it works well but the parent <Image> style changes: it becomes a square while it should be a circle. Like if it modified parent's child. 

Does anyone have a fix for this ?

**Comment by stephanedemotte** [comment] 2017-03-28 13:18
any news on that ?

**Comment by justrdk** [comment] 2017-04-05 16:13
any news on this issue? workarounds didn't work for me. I even set a this.forceUpdate on a button call and change state and props and images didn't get rendered.

**Comment by iiitmahesh** [comment] 2017-05-23 08:52
@henrikra @justrdk  any workaround???

**Comment by kinhbang89** [comment] 2017-05-25 12:30
I also experienced the same thing in Android with custom callout image inside. I have to display so many markers on the map but some of them doesn't have the image rendered :(

**Comment by j-nolan** [comment] 2017-06-28 12:44
Here's a workaround that doesn't require listing the Images before-hand:

```jsx
class PinMarker extends Component {
  state = {
    initialRender: true
  }

  render() {
    return (
      <MapView.Marker coordinate={coordinate}>
          <Image
            source={...}
            onLayout={() => this.setState({ initialRender: false })}
            key={`${this.state.initialRender}`}
          />
      </MapView.Marker>
    )
  }
}
```

The idea is to force a re-render when the component is rendered the first time

**Comment by efkan** [comment] 2017-07-12 18:33
@justrdk have you tried to move styles of the hidden text component into a `StyleSheet` method like the following?

```
<Image source={pin} onLoad={() => this.forceUpdate()}>
     <Text style={styles.hiddenText}>{Math.random()}</Text>
</Image>
...

const styles = StyleSheet.create({
    hiddenText: {width:0, height:0},
    ....
    ....
})
```

It gives a bit advantage in my app.

**Comment by justrdk** [comment] 2017-07-12 18:57
@efkan I ended up setting a timer and rendered icons first and then rendered the images.

**Comment by efkan** [comment] 2017-07-12 21:09
@justrdk I had tried setting timers too. But I could not manage it.

Is there any clue for me :)

**Comment by ignivarahulsaini** [comment] 2017-07-18 13:32
I solved this issue by using the same image again outside the mapViw. but with 0 width and 0 height.

<Image style={{width:0,height:0}} source={ Constants.Images.MarkerImage } />

So that Constants.Images.MarkerImage will load before mapView loads markers.

**Comment by WonderDev21** [comment] 2017-08-23 19:19
Hello, every one.
I have one problem on map.maker.
I want to use react-native-circular-action-menu as maker.

<MapView
                style={ styles.container }
             >
              <MapView.Marker
              coordinate={ this.state.region }
              onPress = {()=> this.showMenu()}
              >
              <View >
                <ActionButton buttonColor="rgba(231,76,60,1)" >
                  <ActionButton.Item buttonColor='#9b59b6' title="New Task" onPress={() => console.log("notes tapped!")}>
                    <Text>aaaa</Text>
                  </ActionButton.Item>
                  <ActionButton.Item buttonColor='#3498db' title="Notifications" onPress={() => {}}>
                  <Text>bbb</Text>
                  </ActionButton.Item>
                  <ActionButton.Item buttonColor='#1abc9c' title="All Tasks" onPress={() => {}}>
                  <Text>ccc</Text>
                  </ActionButton.Item>
                </ActionButton>
            </View>
            </MapView.Marker>
          </MapView>

**Comment by shahonseven** [comment] 2017-08-24 05:12
@WonderDev21 put ActionButton after </MapView>

**Comment by michaelstokes** [comment] 2017-09-21 21:28
Hi @henrikra :) Did anything further come of this? I'm the same position currently in that I've got a child component MapMarker rendering many Map Markers and I want to dynamically update the image of a MapMarker if its selected and vice versa but it only appears to be that you dynamically set images for map markers is through the prop 'image' on the MapView.Marker but then you don't get to applying stying or anything.

I'm running a question over here https://stackoverflow.com/questions/46295212/how-do-i-dynamically-update-collection-of-mapmarker-images-based-on-whether-sele additionally

**Comment by AhmedAly86** [comment] 2017-09-26 21:39
Any new updates, i'm stacked

**Comment by ewein** [comment] 2017-11-24 16:24
Same, looking for a fix.

**Comment by efkan** [comment] 2017-11-28 10:16
Hello @AhmedAly86 and @ewein .

I use j-nolan's solution by changing it a little. Thanks to solutions of **gilbox**, **sators** and **j-nolan** we have workarounds for now.

```

class PinMarker extends Component {
  state = {
    extraData: false
  }

  componentDidMount () {
    let self = this
    setTimeout(()=>self.setState({ extraData: true }), 100)
  }

  render() {
    return (
      <MapView.Marker coordinate={coordinate}>
        <Image
          source={...}
          key={`${this.state.extraData}`}
        />
      </MapView.Marker>
    )
  }
}
```

**Comment by alvelig** [comment] 2017-12-12 04:22
Merge to #1870

**Closed by alvelig** 2017-12-12 04:22 UTC
Labels: bug

**Comment by jadsonor** [comment] 2018-06-27 18:09
It worked for me just adding a random key to the image
```
<View style={styles.container}>
    <Image key={Math.random()+''}
         style={styles.image}
         source={{ uri }}
         onLoad={() => {
             this.setState({ loaded: true });
         }}
 />
```

**Comment by pawarvijay** [comment] 2018-07-29 07:17
facing this error in Android
react-native-maps -> 0.21.0
react ->  16.4.1 
react-native -> 56
Android -> Not working

To replicate -> simply setting markers after component did update
Tried -> Tried all above solutions .and some times it renders first and some times it dosen't

**Comment by Khsed4** [comment] 2018-08-27 10:44
@pawarvijay could u or anyone else answer this question

**Comment by Khsed4** [comment] 2018-08-28 07:08
@pawarvijay @efkan @michaelstokes @WonderDev21 @justrdk @alvelig @j-nolan  
could u guys  or anyone else answer this question :
https://stackoverflow.com/questions/51915353/react-native-maps-markers-image-doesnt-show-using-custom-marker-in-react-nativ

**Comment by PacoGD** [comment] 2018-11-08 10:58
Update in your package.json to "react-native-maps": "^0.22.0"

**Comment by abhideepmallick** [comment] 2019-07-26 12:19
Here is a hack that works: https://github.com/react-native-community/react-native-maps/issues/2734#issuecomment-515428771

**Comment by LeeHyangTom** [comment] 2019-09-20 01:17
Please use Unique Key about Marker. Then your marker issue will be disappear on mapview(android). 
of course  your ios version will work well  for you. It is just related with native module for map rendering in android version.

**Comment by scottarnold** [comment] 2019-10-28 20:39
I ran into this today. I was able to solve it with the following:

```js
render() {
  const { selected = false, coordinate } = this.props;

  const icon = selected
    ? require(...regular pin...)
    : require(...selected pin...);

  if (Platform.OS === 'android') {
    return <Marker image={icon} coordinate={coordinate} />;
  }

  return (
    <Marker coordinate={coordinate}>
      <Image source={icon} />
    </Marker>
  );
}
```

**Comment by jjhampton** [comment] 2020-04-01 21:17
@efkan 's solution [here](https://github.com/react-native-community/react-native-maps/issues/924#issuecomment-347476891) seemed to work for me. Thank you.

**Comment by najuasmgr** [comment] 2020-06-28 17:48
If anyone having this issue, can you try loading marker like writter on this site   https://itnext.io/performant-custom-map-markers-for-react-native-maps-ddc8d5a1eeb0

**Comment by Majidsp** [comment] 2021-03-12 11:18
> I solved this issue by using the same image again outside the mapViw. but with 0 width and 0 height.
> 
> `<Image style={{width:0,height:0}} source={ Constants.Images.MarkerImage } /> `
> So that Constants.Images.MarkerImage will load before mapView loads markers.

This is genius! Thank you!

**Comment by Saliheen** [comment] 2023-09-07 11:00
I solved it like this

**Comment by Saliheen** [comment] 2023-09-07 11:03
I solved it like this                                                                                                                                                                        
const [loading, setLoading] = useState(false);

  const handleOnLayout = () => {
    setLoading(true);
  };

  return (
    <Marker
      tracksViewChanges={false}
      coordinate={coords}>
      <Image
        source={imageUrl}
        onLayout={handleOnLayout}
        key={`key-${loading}`}
      />
    </Marker>
  );

**Comment by AleeFarook** [comment] 2024-11-18 07:54
I solved the issue by providing key to Image and Marker

```
  const [refreshKey, setRefreshKey] = useState(0); // Key for triggering re-renders

  const triggerReRender = () => {
    setRefreshKey(prev => prev + 1); // Update refreshKey to force a re-render
  };

  <View style={{ ...AppStyles.mapConatiner, width: ScreenSize.width }}>
      <MapView
        // zoomControlEnabled={true}
        ref={mapRef}
        style={styles.map}
        onTouchStart={() => { setAutoScrolling ? setAutoScrolling(false) : undefined }}
        onTouchEnd={() => { setAutoScrolling ? setAutoScrolling(true) : undefined }}
        clusterColor={AppColors.ballBlue}
        onRegionChangeComplete={(e) => { regionChaged(bussinessType, e.latitude, e.longitude) }}
        initialRegion={{
          latitude: currentLocationLatitude,
          longitude: currentLocationLongitude,
          latitudeDelta: 0.5, // Larger value for delta latitude
          longitudeDelta: 0.5,
        }}
        clusteringEnabled={bussinessType && bussinessType == AppStrings.bussinessTypes.paid ? false : true}
      >
        {nearestBussinessData?.map((marker, index) => (
          <Marker
            onPress={() => bussinesDetails(marker)}
            style={{ zIndex: index }}
            onCalloutPress={() => bussinesDetails(marker)}
            ref={markerRef}
            key={`${marker.coordinate.latitude}_${marker.coordinate.longitude}_${index}_${refreshKey}`} // give refresh key to marker
            coordinate={marker.coordinate}
            tracksViewChanges={false}
          >
            {marker.promotion == 0 || marker.promotion == null ? (
              <>
                <NonpaidBusinesslocationmarker width={30} height={30} />
                {/* Add Callout for non-paid business */}
                <Callout>
                  <View style={{ ...AppStyles.centeredCommon, height: 40, width: 80 }}>
                    <View style={styles.mapview}>
                      <Text style={styles.mapviewtext}>
                        {marker.business_name}
                      </Text>
                    </View>
                  </View>
                </Callout>
              </>
            ) : (
              <>
                <View style={styles.viewcontainer}>
                  <View style={{ backgroundColor: AppColors.white, ...AppStyles.centeredCommon }}>
                    {/* {memoizedMapImage(marker)} */}
                    <TouchableOpacity onPress={() => bussinesDetails(marker)} style={styles.businessdetail}>
                      <Image
                        key={`key-${refreshKey}`}
                        source={{ uri: marker.business_logo }}
                        style={styles.image}
                        onLayout={triggerReRender}
                      />
                    </TouchableOpacity>
                  </View>
                </View>

                <View style={styles.paidview}>
                  <PaidbBusinesslocationmarker width={30} height={30} />
                </View>
              </>
            )}
          </Marker>
        ))}
      </MapView>
//important line
      <View onLayout={triggerReRender} style={styles.refreshButton}>
        <Text style={{ width: 1, height: 0 }}>Refersh</Text>
      </View>
    </View>
```
