### ISSUE TITLE
InitialRegion does not respect lat/lng delta on iOS Google Maps

### ISSUE THREAD

**Issue by emilefleming** [react-community/react-native-maps#1903] opened 2017-12-20 01:22 UTC
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment
 react-native: 0.45.1
    react: 16.0.0-alpha.12
	react-native-maps: 0.19.0

Google Maps on iOS

### Steps to Reproduce
Initialize a MapView with initialRegion prop running Google maps on iOS.

### Expected Behavior

Map opens to provided region

### Actual Behavior

Map loads to desired location but does not respect the zoom level.

### Reproducible Demo

https://snack.expo.io/SyeWo4DfG

**Comment by osaario** [comment] 2017-12-20 10:27
I think this has something to do with map not being ready yet. Did some debugging and noticed that react pushes the initial props to the native GMSMapView component first time on creation. At that time the setInitialRegion is called but the GMSMapView has now window yet and so probably cant calculate the bounds for this region.

```
- (void)setInitialRegion:(MKCoordinateRegion)initialRegion {
  if(!self.window) return; // Don't set camera if no window 
  if (_initialRegionSet) return;
  _initialRegionSet = true;
  self.camera = [AIRGoogleMap makeGMSCameraPositionFromMap:self andMKCoordinateRegion:initialRegion];
}
```

As a hotfix I added a check for the self.window before setting the initialRegion. Now the prop is set when react calls updateView on the GMSMapView. At this time the window is set.

**Comment by wangliguang** [comment] 2017-12-20 10:45
@osaario How do I use your way to fix my problem？

**Comment by osaario** [comment] 2017-12-20 12:43
@wangliguang I am not sure of the stability of this fix and would not recommend it, but you just have to edit the AirGoogleMap.m file. You will see a method there: 

```
- (void)setInitialRegion:(MKCoordinateRegion)initialRegion {
  if (_initialRegionSet) return;
  _initialRegionSet = true;
  self.camera = [AIRGoogleMap makeGMSCameraPositionFromMap:self andMKCoordinateRegion:initialRegion];
}
```

This is a setter for the prop initialRegion. I just added a line there: 

```
- (void)setInitialRegion:(MKCoordinateRegion)initialRegion {
    if(!self.window) return;
  if (_initialRegionSet) return;
  _initialRegionSet = true;
  self.camera = [AIRGoogleMap makeGMSCameraPositionFromMap:self andMKCoordinateRegion:initialRegion];
}
```

Again, probably would not recommend using this fix in production.

**Comment by alvelig** [comment] 2017-12-20 22:49
@osaario probably you are right. That might be related to map not being ready yet. I use it like this (but I use Apple Maps on iOS): https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665. Would you give it a try?

**Comment by wangliguang** [comment] 2017-12-21 01:53
@osaario   I read the source code find than if there are initialRegin and region,  initialRegion is not work.  
<img width="859" alt="e938cf03-679b-4e26-8851-07175ebe6485" src="https://user-images.githubusercontent.com/11457074/34236904-b35a1a92-e634-11e7-8a9e-45f82b97fe03.png">

**Comment by osaario** [comment] 2017-12-21 08:14
@wangliguang Yes this code in the JS side is making sure that the initialRegion prop is set after the layout is done (GMSMapView has a window), but the problem is that in the native Objective-C code the initialRegion prop is also set before this in the initial view creation. 

```
- (void)setInitialRegion:(MKCoordinateRegion)initialRegion {
  if (_initialRegionSet) return;
  _initialRegionSet = true;
  self.camera = [AIRGoogleMap makeGMSCameraPositionFromMap:self andMKCoordinateRegion:initialRegion];
}
```
This sets the _initialRegionSet flag and thus the second update pushed from the code you pasted is not doing anything anymore.

@alvelig Yes this line here is the problem. The prop is set and this gets called when map has no frame set yet and since its impossible for it to calculate on how to fit the initialBounds to the frame.

```
  GMSCameraPosition * position = [map cameraForBounds:bounds insets:UIEdgeInsetsZero];
    return position;
```

**Comment by emilefleming** [comment] 2017-12-21 15:49
This may be deserving of its own issue but onMapReady also never fires on iOS (both Apple and Google maps if I'm not mistaken). Possibly related?

**Comment by alvelig** [comment] 2017-12-21 18:34
@emilefleming I use onMapReady for AppleMaps and that's working all right. Also try master as we recently PRed #1853

**Comment by osaario** [comment] 2017-12-22 11:24
As a more persistent fix I noticed a couple of things that go wrong and why the initialRegion is not working. First of all:

```
    this.state = {
      isReady:
        Platform.OS === "ios" &&
        this.props.provider !== ProviderConstants.PROVIDER_GOOGLE // added this
    }
```

If the provider is google maps in iOS we have to wait for the map to be ready before trying to set the initialRegion prop.

This fixes it for the first render but when you go back and then to the map again it shows blue.

```
      props = {
        style: this.props.style,
        region: null,
        initialRegion: null,
        onMarkerPress: this._onMarkerPress,
        onChange: this._onChange,
        onMapReady: this._onMapReady,
        onLayout: this._onLayout
      }
```
It seems that somehow the null initialRegion passed as prop is calling the setInitialRegion in the native side with a null value. In the first render the null value is correctly not calling the setter. I have no idea why this happening? Well anyway... that gets fixed if we just dont pass the initialRegion prop at all:

```
      props = {
        style: this.props.style,
        onMarkerPress: this._onMarkerPress,
        onChange: this._onChange,
        onMapReady: this._onMapReady,
        onLayout: this._onLayout
      }
```

This should fix that issue but what happens now is that in the second render the map is just rendering the default location (Somewhere over europe for me) and ignores the initialRegion prop. This is because the onMapReady is not called @emilefleming , @alvelig. Seems that there is a global variable in the AirGoogleMap class that is set on the first time and then prevents it after that.

```
- (void)mapViewDidStartTileRendering:(GMSMapView *)mapView {
  if (didCallOnMapReady) return;
  didCallOnMapReady = YES;
  
  AIRGoogleMap *googleMapView = (AIRGoogleMap *)mapView;
  [googleMapView didPrepareMap];
}
```

I dont know what purpose this check serves but when removing it everything works as expected for me.

**Comment by rborn** [comment] 2017-12-22 11:28
I don't use initialRegion at all.

I set the state of the component to a region and use that state for the region property of the map.
when`onRegionChangeComplete` triggers I set the state with the new region and that's it.

It seems to work just fine on both iOs and android using google maps (didn't try with apple yet)

**Comment by osaario** [comment] 2017-12-22 11:47
@rborn yes it might be the solution. Although I don't fully trust that setting the region all the time for map doesn't cause any glitches. F.ex.if the map is middle animation and then the region is forcefully set. It sure is not the way the native GMSMapView is supposed to be used.

**Comment by Agontuk** [comment] 2018-01-09 07:49
Guys, I made a pull request #1953 which attempts to fix several google map issues on iOS including lat/lng delta not setting properly. Can you check and see if it works for you? Feedback is welcome.

**Comment by Frexuz** [comment] 2018-01-10 05:22
Oh, +1000! We'd really want this soon as we're approaching our first production release :D <3

**Comment by slorber** [comment] 2018-01-23 11:44
after upgrading to Expo SDK25, on Android, I also get this delta not taken into account

**Comment by rborn** [comment] 2018-01-23 12:46
@slorber this is an expo issue I think

**Comment by rborn** [comment] 2018-01-23 12:47
closing, https://github.com/react-community/react-native-maps/pull/1953 is merged

**Closed by rborn** 2018-01-23 12:47 UTC

**Comment by slorber** [comment] 2018-01-23 13:01
@rborn not so sure it's related to Expo, I'll try to report it better if I understand it.

What I've seen is that when nesting a map inside a TabNavigator of react-navigation, if we disable tab navigation animations and swipes, it makes the app delta not being taken into account. 

For very unexpected reasons, I can't reproduce it in a Snack while I was able to reproduce with minimal code in my own Expo project (same SDK...)

Here is a snack with the code: https://snack.expo.io/SJNZ9sNBM
Unfortunately, and surprisingly, as a snack it works fine...

**Comment by rborn** [comment] 2018-01-23 13:38
@slorber https://github.com/expo/expo-sdk/blob/master/package.json#L60
sadly we don't have pushed to npm the latest changes so you might want to change that build to the git repo, run `npm install` and check if it's working

**Comment by slorber** [comment] 2018-01-23 13:56
@rborn sorry but I don't really understand what you are asking me to do. I'm using Expo SDK25 which relies on maps 0.19.0 which is the latest published version on NPM. What should I chance and where? I can't upgrade to 0.20.0 as it's not yet released and backporting code of recent pull-requests locally why not but the one linked in this issue only touches iOS native code.

**Comment by rborn** [comment] 2018-01-23 14:00
@slorber it's little complicated. In node_modules you should find the expo sdk, and change it's package.json file to point to `react-native-maps:https://github.com/react-community/react-native-maps.git` and in the same folder run `npm install` This way the expo sdk package should be updated to the last code we have in github.

**Comment by slorber** [comment] 2018-01-23 14:10
Hmmm unfortunately I think it's not so simple for RN world and got a lot of errors due to duplicate Haste module names. For testing RN projects locally I think it's better to checkout git repo, create symlinks and use a bundler like Haul which support symlinks (Metro doesn't).

I'll pass for now and check next release, I've temporarily reenabled tabnav animations in my app to fix the problem.

**Comment by tmaly1980** [comment] 2018-02-08 21:06
Who is in charge of updating the npm listing to point to this updated version?

**Comment by rborn** [comment] 2018-02-08 22:13
We'll have this pushed soon. I need to make a changelog for it and I'll try to make it tomorrow then we push 😊

**Comment by jskidd3** [comment] 2018-02-17 16:26
@Agontuk @rborn I've just installed v0.20.1 which includes the pull request https://github.com/react-community/react-native-maps/pull/1953 but the map is still zoomed right out showing the world on iOS. Our region looks like this `{latitude: 54.5, longitude: -4.5, latitudeDelta: 20, longitudeDelta: 20}` and should focus on the UK. Testing simultaneously on Android device and it focuses correctly on there. Any ideas?

**Comment by chrismcleod** [comment] 2018-02-20 22:54
@Agontuk, I was having the same problem as @jskidd3.

I could not get initialRegion to zoom correctly, even though it does go to the right coordinate. I updated my code to call animateToRegion after onMapReady has been called.  That still did not work so I set some breakpoints in XCode in animateToRegion of AirGoogleMapManager.m and noticed when I call animateToRegion, the block is called twice back-to-back.  Once with the right coordinates, then again with "blank" coordinates.  I console.log my calls to animateToRegion on the javascript side, and it is only called once.

![untitled](https://user-images.githubusercontent.com/1134683/36453236-0589c2b0-165d-11e8-8be3-956a749dc4b6.gif)

Calling animateToRegion (in javascript) after a setTimeout of 0 seems to recenter and zoom correcty.  However, the breakpoint is still hit twice back-to-back.  Again the first time with the right coordinates, and the second time with this:

![image](https://user-images.githubusercontent.com/1134683/36453654-7e466bd0-165e-11e8-8694-ba2995cb6d70.png)

### Workaround
```typescript
componentDidUpdate(nextProps) {
    if (
      nextProps.region && 
      this.map && 
      this.state.ready && 
      !this.state.regionSet
    ) {
      this.setState({ regionSet: true }, () => {
        setTimeout(() => this.map!.animateToRegion(nextProps.region), 0)
      })
    }
  }
```

**Comment by Agontuk** [comment] 2018-02-21 14:14
@jskidd3 , I tried with your coordinates and map is shown like this. It looks ok to me since it's focusing on UK.

![simulator screen shot - iphone 7 - 2018-02-21 at 19 49 10](https://user-images.githubusercontent.com/5656440/36484472-9c82e5e8-1743-11e8-92ad-b5378e50838a.png)
