### ISSUE TITLE
Image Overlay?

### ISSUE THREAD

**Issue by dtruel** [react-community/react-native-maps#400] opened 2016-07-16 19:03 UTC
Hi,

I have a gif I want to overlay.  It is US weather radar:

http://radar.weather.gov/ridge/Conus/RadarImg/latest_radaronly.gif

Is there a way I can do this with this plugin?  I saw there are polygon overlays, but I did not see an image overlay.

**Comment by Nodonisko** [comment] 2016-07-27 14:05
+1

**Comment by sunglee** [comment] 2016-09-12 19:02
@lelandrichardson Any plan to support image overlay yet? Thanks.

**Comment by anupkale1984** [comment] 2016-10-13 18:08
+1

**Comment by zolrath** [comment] 2016-11-10 08:14
:+1: I would love to be able to show something as simple as a logo on the top center of the map but still have Callouts appear above it when Markers are pressed.

**Comment by kanekotic** [comment] 2017-01-01 21:19
+1

**Comment by danielreuterwall** [comment] 2017-01-23 08:17
I got an image overlay to the map like this.

`<MapView></MapView>
<View pointerEvents="none" style={{position: 'absolute', top: x, left: y}}>
  <Image source={{uri: 'zzz'}} />
</View>`

The pointerEvents="none" makes sure the map gets all touch events. Hope this helps.

**Comment by Nodonisko** [comment] 2017-01-23 11:51
But we want overlay, not something like watermark :) Overlay should reflect zoom, tilt etc.

**Comment by danielreuterwall** [comment] 2017-01-23 11:59
Ah, misunderstood :)

**Comment by fmelp** [comment] 2017-04-11 13:07
+1 on image overlay responsive to zoom and rotation

**Comment by alvelig** [comment] 2017-12-15 02:22
Duplicate of #103

**Closed by alvelig** 2017-12-15 02:22 UTC
