### ISSUE TITLE
Cannot click on button inside MapView.Callout 

### ISSUE THREAD

**Issue by johnspaul** [react-community/react-native-maps#1541] opened 2017-08-10 16:34 UTC

**Comment by jordonmckoy** [comment] 2017-09-28 03:16
```JSX
<MapView.Callout onPress={() => console.log("This is logged")}>
  <Link to="/random/route" onPress={() => console.log("This is not fired")}>
    <Text>Click Me!</Text>
  </Link>
</MapView.Callout>
```

I'm currently developing for android

**Comment by alvelig** [comment] 2017-12-13 01:06
Duplicate of #135. Wontfix, sorry

**Closed by alvelig** 2017-12-13 01:06 UTC

**Comment by alvelig** [comment] 2017-12-13 01:22
#1556 an enhancement issue for that

**Comment by richard4s** [comment] 2019-04-24 01:42
You could try this depending on your needs https://stackoverflow.com/a/41161292/9104897
