### ISSUE TITLE
Markers hijacking map zoom even when child views have pointer events none set on them

### ISSUE THREAD

**Issue by martsie** [react-community/react-native-maps#1731] opened 2017-10-25 11:09 UTC
I have a MapView with custom map markers on them. When initiating a two finger zoom gesture, if one or both of the fingers happens to rest on a marker then the zoom doesn't work. Single finger drag doesn't work either.

The UIView inside the marker has pointerEvents to none on it so it's not those views intercepting it.

![mapzoombug 2](https://user-images.githubusercontent.com/11308291/31995687-2e50e41e-b9d1-11e7-813f-f48708493a19.gif)

**Attempted solution**
- Setting pointerEvents to none on the MapView.Marker itself. This fixed the problem, however, the Marker's onPress no longer works. onSelect does work but has a large delay which makes the UI feel unresponsive.

Any ideas? Using the default iOS markers (ie MapView.Marker's with no subviews) doesn't create the same issue.

**Comment by aksonov** [comment] 2017-10-31 16:25
The same problem - even with built-in markers with custom images.

**Comment by wbattel4607** [comment] 2017-11-04 06:45
Us as well. We've been struggling with it for a while- still not sure how to avoid it.

**Comment by martsie** [comment] 2017-11-05 05:07
One way I've found to get around it is to set the MapView.Marker's themselves to have `pointerEvents="none"` and then respond to map presses (rather than marker presses). Then detect the latitude and longitude of where the user clicked, loop through your markers and try and find if any markers were within a hitbox area. 

For that, you'll need to convert latitude and longitude to pixels, which requires you to divide the map's current width by the longitude delta, and height by the latitude delta. Also, know that because of the nature of latitude and longitude, simply dividing won't be accurate for the more zoomed out views because the longitude per pixel changes depending on how far away from the equator you are.

This is some excerpts code from my project that may put you on the right track. It's highly simplified and not particularly optimised however if you have under 1000 markers on the map, and you're zoomed in far enough, it should be fine.

```
<MapView
       ...
        onPress={(e) => this.onMapPress(e.nativeEvent.coordinate)}
      >

onMapPress(event) {
    if (!event) {
      return;
    }

    const { latitude, longitude } = event;
    const { width, height } = this.state;
    const latPerPixel = (this.state.latitudeDelta) / height;
    const LngPerPixel = (this.state.longitudeDelta) / width;

    const markerWidth = 50;
    const markerHeight = 50;

    const closestMarker = this.state.clusters.find(({ center }) => {
      const { lat, lng } = center;

      const minLng = lng - LngPerPixel * (markerWidth / 2);
      const maxLng = lng + LngPerPixel * (markerWidth / 2);
      const minLat = lat - latPerPixel * (markerHeight / 2);
      const maxLat = lat + latPerPixel * (markerHeight / 2);

      return latitude > minLat && latitude < maxLat && longitude > minLng && longitude < maxLng;
    });

    // Can also set null as the closet marker.
    this.setState({ activeMarker: closestMarker });
  }
```

**Comment by compojoom** [comment] 2017-11-06 08:57
Thanks for the code snipped @martsie It's an interesting workaround and I'll try it out as this was driving me nuts for some time. If replacing the apple map with google maps on Ios wasn't causing 100% cpu usage with custom markers then I would have long ditched apple maps in favor of google.

This is issue is also a duplicate of this https://github.com/airbnb/react-native-maps/issues/1539

**Comment by alvelig** [comment] 2017-12-13 05:18
Duplicate of #1539

**Closed by alvelig** 2017-12-13 05:18 UTC
