### ISSUE TITLE
The MapView dont show me the UserLocation on Android

### ISSUE THREAD

**Issue by avedismb** [react-community/react-native-maps#1011] opened 2017-02-01 22:50 UTC
It shows me the map correctrly but without the user location.

This is my code:

MapView
        showsUserLocation={true}
        showsMyLocationButton={true}
        style={{ height: 600 }}
        initialRegion={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        }}

Any idea ?

Thanks.

**Comment by spikebrehm** [comment] 2017-02-02 00:50
Probably you have to enable a permission or something in Google Play Services for this to work.  Does it work in other apps that utilize Goole Maps?

**Comment by avedismb** [comment] 2017-02-02 00:56
No, I didnt test it in other app or in IOS. Maybe is that , I will investigate that.

**Comment by jeffreymendez1993** [comment] 2017-02-03 21:09
this is a current bug on android

**Comment by philberg** [comment] 2017-02-08 04:51
+1

**Comment by AugustoAleGonZhipCode** [comment] 2017-02-26 00:04
Check the permissions on my application the current location works perfect. What it is not supported is the followsUserLocation

**Comment by Ethan0007** [comment] 2017-05-29 14:16
try to landscape your device the showsUserLocation will show.

**Comment by alvelig** [comment] 2017-12-15 05:59
Duplicate of #1033

**Closed by alvelig** 2017-12-15 05:59 UTC
