### ISSUE TITLE
Make callout visibility controlled / declarative

### ISSUE THREAD

**Issue by afilp** [react-community/react-native-maps#34] opened 2016-01-23 23:52 UTC
This is a similar wish to this:
https://github.com/facebook/react-native/issues/4656

I understand that we have the `showCallout` method but this seems to be an imperative way to do so, plus it needs to know when the marker is rendered, etc.

I would expect something like this (`showsCalloutOnLoad` property):

```
                        <MapView.Marker
                            key={marker.key}
                            coordinate={marker.coordinate}
                            title={marker.title}
                            description={marker.description}
                            showsCalloutOnLoad
                        />
```

If more than one marker uses this property then only one of them shows the callout (the last one loaded?), since you do not support multiple open callouts. Obviously, we can have checks to make sure that only the marker that interests the user will have this property as `true` on render.

**Comment by lelandrichardson** [comment] 2016-01-24 00:12
@af7 I agree I think callout visibility could ideally be done as a declarative API.

a bit different to your proposed API, I envision something like this:

```jsx
<MapView.Marker
  visible={this.state.visible}
  onCalloutVisibleChange={visible => this.setState({ visible })}
/>
```

As long as there is no major qwerkiness, this would be a change I would support :+1:

**Comment by af7** [comment] 2016-01-24 04:20
Did you mean to write `<MapView.Callout` and not `<MapView.Marker` on the example above?

**Comment by lelandrichardson** [comment] 2016-01-24 04:32
@af7 hmm. I dunno, I think this might work better on the Marker. The `<MapView.Callout />` component isn't necessary if you're just filling out a `title` and a `description` on the Marker.

`calloutVisible` might make more sense:

```jsx
<MapView.Marker
  calloutVisible={this.state.visible}
  onCalloutVisibleChange={visible => this.setState({ visible })}
/>
```

**Comment by af7** [comment] 2016-01-24 16:01
Yes, the naming now makes sense! I am absolutely OK with this.

**Comment by jedlau** [comment] 2016-02-05 00:49
Along similar lines, is it possible to enable/disable the callout for an annotation? My use case is that I want a marker to be displayed, but not tappable (i.e., no callout appears when the marker is tapped).

**Comment by af7** [comment] 2016-03-06 10:11
@lelandrichardson 

I am afraid I do not know the internals well to help on this task in a timely manner. If you think you can do this relatively easily can you please give it a priority, if possible?

Thanks!

**Comment by bufke** [comment] 2017-01-23 22:36
Here's a horrible workaround.

```
  render() {
    if (this.props.showCallout) {
      setTimeout(() => {
        this.refs.marker.showCallout();
        this.props.clearCalloutMarker();
      }, 0);
    }

    return (
      <MapView.Marker
        ref="marker"
        ect..
      >
```

In my case I'm using redux but you could do it with normal state and props. Basically I have an action to set a marker to show the callout and another action to null this back out. I use setTimeout so it runs async after render returns. It's a little bit horrible but if you manage state right you can move the horribleness out into a dumb component where it will cause minimal confusion. Now I can call my action anywhere I want and I know it will cause the callout to show up.

**Comment by ahstro** [comment] 2017-03-18 11:37
I love @lelandrichardson's proposed API, but how would that work with not supporting multiple visible callouts? Is that required behaviour?

**Comment by SavaStanislav** [comment] 2017-11-10 13:06
I have also had to create custom children with custom callouts, due to the library not supporting multiple visible callouts. Is there actually a reason behind this restriction?

**Comment by alvelig** [comment] 2017-12-12 04:02
Duplicate of #275

**Closed by alvelig** 2017-12-12 04:02 UTC
Labels: enhancement, help wanted

**Comment by NeliHarbuzava** [comment] 2020-11-26 15:02
Need the possibility to show callouts for multiple markers at the same time. For now, it is possible to show only one callout with `showCallout()` method. When `showCallout` called, another callouts got hidden. How we can implement this?
