### ISSUE TITLE
Calling animateToRegion during componentDidMount doesn't work properly

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-community/react-native-maps#1717] opened 2017-10-19 16:24 UTC
Since the initialRegion prop doesn't work I need to be able to animate into the region right after the map mounts but if you call animateToRegion during the componentDidMount, it will move your position over your region but it doesn't respect the deltas, so the map is completely zoomed out to see most of the world. But if I then trigger the exact same line of code with the exact same region manually with a button press it works perfectly. Does anyone know why this doesn't work directly after mount?

**Comment by RyanMitchellWilson** [comment] 2017-10-19 16:44
Found a little work around, if you delay calling `animateToRegion` by just a couple milliseconds inside the componentDidMount it seems to work properly. Not sure why the slight delay helps exactly but it does.

```
componentDidMount() {
  setTimeout(() => {
    this.mapView && this.mapView.animateToRegion(this.region, 500)
  }, 10)
}
```

**Comment by fredrikwithpettersen** [comment] 2017-10-22 11:07
Did you set the reference to mapView?

```
<MapView style={styles.map}
                         ...
                         ref={ref => { this.mapView= ref; }}
                         ...
```

**Comment by RyanMitchellWilson** [comment] 2017-10-23 15:24
Yes that is not the problem, as I stated above it will animate the map to be over your region but it does not respect the deltas, so it does not zoom in to your region. You are just left directly above your region but completely zoomed out to the point you can see most of the world.

**Comment by alvelig** [comment] 2017-12-13 04:42
Please try this example: 
https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665
Comment if it does not do what you want.

**Comment by RyanMitchellWilson** [comment] 2017-12-13 18:36
Can you please stop closing these issues without fixing them? This issue for for trying to animateToRegion on mount. I cannot use initialRegion due to the fact that it is fundamentally broken in ios. https://github.com/react-community/react-native-maps/issues/1617 Does not work when mounting a map after one has already been mounted.

**Comment by rborn** [comment] 2017-12-13 18:41
@RyanMitchellWilson we have a lot of issues and we try to sort the ones that don't apply anymore, so please don't get upset 😊

Can you try this PR to see if it fixes your issue? https://github.com/react-community/react-native-maps/pull/1715 I'll reopen the issue meanwhile.
(Actually @alvelig told you to comment on the issue if the suggested fix doesn't work)

**Comment by RyanMitchellWilson** [comment] 2017-12-13 18:48
I'm not really upset, all I'm asking is that you wait for a response if you suggest something instead of just closing the issue. Especially if the suggestion doesn't directly relate to the issue. This issue is specifically about calling animateToRegion on didMount, not about setting an initialRegion.

**Comment by alvelig** [comment] 2017-12-13 18:51
@RyanMitchellWilson the example in my comment in 209 shows how to `animateToRegion` after the map is ready, which may not be the same as componentDidMount. It actually won't work in Android because componentDidMount may be called before the map is ready. And there's not much to do about it. If you want to help, please.

- [ ] Comment if #1715 
- [ ] Comment if https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665 worked
- [ ] Create an example project to reproduce
- [ ] Complete your issue according to the new template (pressing New issue will give you that)

P.S. Closing the issue does not mean we are not open to comments. And I closed this because I gave a solution to your business logic problem. (See 209)

**Comment by alvelig** [comment] 2017-12-15 15:06
@RyanMitchellWilson not to leave this stale we will reopen as soon as get a feedback from you for the checks mentioned above

**Closed by alvelig** 2017-12-15 15:06 UTC

**Comment by lingzt** [comment] 2019-01-29 15:49
call it on onMapReady works
