### ISSUE TITLE
Ability to turn on navigation

### ISSUE THREAD

**Issue by patrickml** [react-community/react-native-maps#413] opened 2016-07-22 01:55 UTC
Does this package have the ability to turn on navigation? I.e. walking paths to get to a location?

**Comment by dhdo** [comment] 2016-08-10 15:23
Yes, when you hit a marker a "Navigate to" button appear on the bottom right corner of the map.

**Comment by CharlieIGG** [comment] 2016-08-13 23:56
@dhdo I have the toolbar enabled and when I click on a marker no buttons show up. What else could I be missing?

**Comment by comountainclimber** [comment] 2016-09-07 22:34
I am having a somewhat related issue... On press the marker does not reveal the toolbar it is only when I interact with the container component that the toolbar appears really bizarre behavior

**Comment by MatthiasDebaere** [comment] 2016-12-20 13:49
Same here @comountainclimber , I've got two map containers in my app. One of them shows the toolbar correctly on marker press. Other one doesn't. I've searched after differences between the two, but haven't found anything which fixes the toolbar in the first one. (tried adjusting style, onMarkerPress functions, rendering sequence (first one is rendered on startup), ... i'm stuck 😢 )

**Comment by MatthiasDebaere** [comment] 2017-01-16 09:47
See https://github.com/airbnb/react-native-maps/issues/549 for a hacky solution I thought of.

**Comment by GuelorEmanuel** [comment] 2017-03-27 17:18
@MatthiasDebaere 
Is your hacky solution exclusive to Android? is there a way to turn on navigation for IOS?

**Comment by rborn** [comment] 2017-12-15 14:36
Closing as it's an old question. Please comment to reopen.

**Comment by alvelig** [comment] 2017-12-15 14:37
Duplicate of #778

**Closed by rborn** 2017-12-15 14:36 UTC
Labels: question
