### ISSUE TITLE
animateToRegion crashing app sometimes

### ISSUE THREAD

**Issue by bgdavidx** [react-community/react-native-maps#1055] opened 2017-02-23 09:05 UTC
Hey there,

We are getting this crash for 8% of our users (we have a few thousand users), when we call animateToRegion on the map:

```       at com.google.android.gms.common.internal.zzaa.zzb(Unknown Source)
       at com.google.android.gms.maps.CameraUpdateFactory.zzbsd(Unknown Source)
       at com.google.android.gms.maps.CameraUpdateFactory.newLatLngBounds(Unknown Source)
       at com.airbnb.android.react.maps.AirMapView.animateToRegion(AirMapView.java:483)
       at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:209)
       at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:29)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:703)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:257)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:543)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5017)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Any idea what could be causing this?

In Crashlytics it says:

```Fatal Exception: java.lang.NullPointerException
CameraUpdateFactory is not initialized
```

**Comment by esutton** [comment] 2017-03-31 13:38
+1

@bgdavidx  did you find a solution?

```
E/unknown:React(28975): Exception in native call
E/unknown:React(28975): java.lang.NullPointerException: CameraUpdateFactory is not initialized
E/unknown:React(28975): 	at com.google.android.gms.common.internal.zzac.zzb(Unknown Source)
E/unknown:React(28975): 	at com.google.android.gms.maps.CameraUpdateFactory.zzIz(Unknown Source)
E/unknown:React(28975): 	at com.google.android.gms.maps.CameraUpdateFactory.newLatLngBounds(Unknown Source)
E/unknown:React(28975): 	at com.airbnb.android.react.maps.AirMapView.fitToCoordinates(AirMapView.java:573)
E/unknown:React(28975): 	at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:217)
E/unknown:React(28975): 	at com.airbnb.android.react.maps.AirMapManager.receiveCommand(AirMapManager.java:29)
E/unknown:React(28975): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:703)
E/unknown:React(28975): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:258)
E/unknown:React(28975): 	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784)
```

I am using react-native-device-info.  To fix a gms conflict I added this to my build.gradle
https://github.com/airbnb/react-native-maps/issues/1028

```
// Use same version react-native-maps specifies com.google.android.gms 10.0.1
// to prevent crash when using react-native-device-info
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.getRequested().getGroup() == 'com.google.android.gms') {
            details.useVersion('10.0.1')
        }
    }
}
```

But now I get exception **CameraUpdateFactory is not initialized** 

```
    "react": "~15.4.1",
    "react-native": "0.42.3",
    "react-native-device-info": "^0.10.1",
    "react-native-maps": "^0.13.1",
```

**Comment by henrikra** [comment] 2017-04-12 09:17
We have got same error couple times:
```
java.lang.NullPointerException CameraUpdateFactory is not initialized 
    Unknown:-1 com.google.android.gms.common.internal.zzac.zzb
    Unknown:-1 com.google.android.gms.maps.CameraUpdateFactory.zzJn
    Unknown:-1 com.google.android.gms.maps.CameraUpdateFactory.newLatLngBounds
    AirMapView.java:573 com.airbnb.android.react.maps.AirMapView.fitToCoordinates
    AirMapManager.java:217 com.airbnb.android.react.maps.AirMapManager.receiveCommand
    AirMapManager.java:29 com.airbnb.android.react.maps.AirMapManager.receiveCommand
    NativeViewHierarchyManager.java:703 com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand
    UIViewOperationQueue.java:258 com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute
    UIViewOperationQueue.java:784 com.facebook.react.uimanager.UIViewOperationQueue$2.run
    UIViewOperationQueue.java:831 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:45 com.facebook.react.uimanager.UIViewOperationQueue.access$1500
    UIViewOperationQueue.java:870 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedChoreographerFrameCallback.java:32 com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame
    ReactChoreographer.java:131 com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    Choreographer.java:775 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:590 android.view.Choreographer.doCallbacks
    Choreographer.java:559 android.view.Choreographer.doFrame
    Choreographer.java:763 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:145 android.os.Looper.loop
    ActivityThread.java:6872 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Method.java:372 java.lang.reflect.Method.invoke
    ZygoteInit.java:1404 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:1199 com.android.internal.os.ZygoteInit.main
```

**Comment by Moumene** [comment] 2017-04-12 13:12
Sometimes it works and some other times nothing happen when use it inside `componentWillReceiveProps`

**Comment by the-simian** [comment] 2017-05-19 22:12
I was able to reproduce this error on my android emulator. I got a message in my app stating that the binary would not run unless I updated google play services. Upon updating Google Play services (in the emulator) the problem went away.

I think if the user is behind for Google play services, you see this. When they update, you're ok.

**Comment by jpmazza** [comment] 2017-10-20 19:59
Any updates on this?
I am calling `fitToCoordinates` inside the `componentWillReceiveProps` method and it works in development mode but it crashes in release mode. Why?

**Comment by the-simian** [comment] 2017-10-26 02:32
@jpmazza regarding `fitToCoordinates`, there's still some issues there, depending on the lifecycle of the map. Here is a relevant thread with more information: https://github.com/airbnb/react-native-maps/issues/1227

I can't say for certain your problem is the same, but look in there and see if that is the case

**Comment by alvelig** [comment] 2017-12-16 02:40
You need to wait for onMapReady. Actually kinda duplicate of #1227

**Comment by alvelig** [comment] 2017-12-16 02:40
For an idea see https://github.com/react-community/react-native-maps/issues/209#issuecomment-350907665

**Closed by alvelig** 2017-12-16 02:40 UTC
