### ISSUE TITLE
Overlay: Image overlay on map

### ISSUE THREAD

**Issue by anupkale1984** [react-community/react-native-maps#868] opened 2016-12-08 02:12 UTC
Can i do Image overlay on Map and put marker on top of it?
I dont have Tile based mechanism with my application.

I have a use case where on Selection on particular marker, i show floor map and need to put some marker on it.

**Comment by symmetriccurve** [comment] 2016-12-28 02:48
You can Probably use two markers with zIndex, one with the floor map image and one with the actual marker(only if I understood your question correctly, an sample image of what are you trying to achieve  is helpful)

**Comment by markmssd** [comment] 2017-02-04 19:11
I think he is referring to this kind of image: https://developers.google.com/maps/documentation/javascript/examples/groundoverlay-simple
Which is not a Marker (it's size will change with the zoom level)

Is that possible?

**Comment by markmssd** [comment] 2017-02-21 19:52
@anupkale1984 Any luck on this?

**Comment by anupkale1984** [comment] 2017-03-08 21:47
@markmssd not yet

**Comment by geek2050** [comment] 2017-04-06 07:05
I don't know how to modify the react-native-maps properly, but I have hacked and hard coded it locally in my code **for iOS only** to make this happen. Can someone familiar with react-native-maps development please modify the codes to incorporate into react-native-maps the following:

1.  A parameter for the image for the groundoverlay e.g. adelaidemap.jpg
2. The coordinates for the 2 corners of the ground overlay: south-west & north-east
     See the **groundOverlay** parameter in the example usage below

`

        <MapView 
             style={styles.mapContainer}
             provider={PROVIDER_GOOGLE}
                initialRegion={{
                latitude: -34.911703, 
                longitude: 138.579694,
                latitudeDelta: 0.01,
                longitudeDelta: 0.01,
             }}

             showsUserLocation={true}              

             groundOverlay={{
                 groundImage: 'adelaidemap.jpg',
                 south: -34.952547, 
                 west: 138.579217,
                 north: -34.905822, 
                 east: 138.614837
             }}>                   

             <MapView.Marker
                coordinate={coordinate}
                title={'test'}
             />
          </MapView>
`


3. Then in the **AirGoogleMaps/AIRGoogleMap.m**, make the following changes:


- (instancetype)init
{
  if ((self = [super init])) {
    _reactSubviews = [NSMutableArray new];
    _markers = [NSMutableArray array];
    _polygons = [NSMutableArray array];
    _polylines = [NSMutableArray array];
    _circles = [NSMutableArray array];
    _tiles = [NSMutableArray array];
    _initialRegionSet = false;
    
    [self groundOverlay];
  }
  return self;
}


- (void) groundOverlay
{
  // use the input boundary from javascript
  CLLocationCoordinate2D southWest = CLLocationCoordinate2DMake(**south, west**);
  CLLocationCoordinate2D northEast = CLLocationCoordinate2DMake(**north,east**);
  GMSCoordinateBounds *overlayBounds = [[GMSCoordinateBounds alloc] initWithCoordinate:southWest  coordinate:northEast];

  UIImage *icon = [UIImage imageNamed:**groundImage**];
  
  _overlay = [GMSGroundOverlay groundOverlayWithBounds:overlayBounds icon:icon];
  _overlay.zIndex = 1000;
  _overlay.map = self;
}


In the meantime, if you need to hardcode it then, you just need to grab the AIRGoogleMap.m and do what I did. Not ideal but a hack to make it work. 

Unless someone can show me on how to extend the react-native-maps interface to make this happen

**Comment by fmelp** [comment] 2017-04-06 15:20
+1 on this issue. Any chance it can be integrated into the package for both android and iOS? Thank you very much!!

and thanks @geek2050 for the temp workaround!

**Comment by aaronbuchanan** [comment] 2017-06-30 19:45
+1

**Comment by BuffMcBigHuge** [comment] 2017-07-19 03:22
+1

**Comment by yaswanthsvist** [comment] 2017-07-27 16:01
+1

**Comment by fredesse** [comment] 2017-09-07 02:30
+1

**Comment by neilyoung** [comment] 2017-09-11 17:29
+1

**Comment by rahmanmarija** [comment] 2017-09-14 14:37
+1

**Comment by aaronbuchanan** [comment] 2017-09-27 21:27
Jun 30 — when I was last here, still trying to solve this 🤕

**Comment by alvelig** [comment] 2017-12-13 21:03
Duplicate of #103

**Closed by alvelig** 2017-12-13 21:03 UTC
