### ISSUE TITLE
Update Podfile contents on setup instructions readme

### ISSUE THREAD

**Issue by rishabhmathur1693** [react-community/react-native-maps#2073] opened 2018-03-08 14:14 UTC
Please update the Podfile contents on installation documents as per latest react native version. Some of the values are not needed are giving compile time error if added like "BatchedBridge", etc.

**Comment by rborn** [comment] 2018-03-08 14:41
closing, no template and duplicate of various other issues. There is also a PR opened but you didn't bother to search

**Closed by rborn** 2018-03-08 14:41 UTC
Labels: NO ISSUE TEMPLATE

**Comment by rishabhmathur1693** [comment] 2018-03-08 14:51
@rborn When I previously checked the pull requests, it wasn't there. I saw that after I posted the issue.

**Comment by rborn** [comment] 2018-03-08 14:53
@rishabhmathur1693 that's ok, but please for the other issues you raise respect the template.
We do this in our free time and the template helps us evaluate the issues faster.

**Comment by rishabhmathur1693** [comment] 2018-03-08 14:54
@rborn Will do.
