### ISSUE TITLE
Polyline problem - rendering to infinity

### ISSUE THREAD

**Issue by feromakovi** [react-community/react-native-maps#306] opened 2016-06-20 09:12 UTC
Hello guys, 

we have a problem on iOS platform and the problem is:
There are several geo points (markers) shown on the map and we connect them with polyline (source-code attached below). 

```
<Polyline
    coordinates={this.props.list.map(item => {
        return {
            latitude: item.latitude,
            longitude: item.longitude,
        }
    })}
    strokeColor="rgb(0,0,255)"
    strokeWidth={3}
/>
```

The problem occur just after different zoom scales. If the map is zoomed-in enough, it works fine - all the points are connected with the polyline correctly (zoomed to ~ street level)
Rendered polyline starts and finishes in defined points
![mapscreen2](https://cloud.githubusercontent.com/assets/805629/16188512/1f058fd4-36d6-11e6-8ca9-46e6c429f883.png)

but if you zoom-out so the polyline starts from undefined point - kinda wrong calculation of the start or of the length of polyline and the polyline finishes in undefined point as well (zoomed to ~ state level). 
Consider there is no other point on the map
![mapscreen](https://cloud.githubusercontent.com/assets/805629/16188580/86658ee0-36d6-11e6-9f61-5160cfd3fe5e.png)

another pict (zoomed to ~ continent level). As you can see the end of polyline is in undefined point
![mapscreen3](https://cloud.githubusercontent.com/assets/805629/16188756/71684522-36d7-11e6-865e-8a3a8730c544.png)

The problem occur only on iOS platform, it works well on Android platform at all.

Please, what is the issue? Can you help me how to fix it or prevent this problem?
Thanks!

**Comment by jrichardlai** [comment] 2016-06-22 15:41
Seems to be duplicate of https://github.com/lelandrichardson/react-native-maps/issues/248

**Comment by feromakovi** [comment] 2016-06-22 15:43
Yes, it could be. I'm sorry, I haven't mentioned that.

**Closed** 2017-12-10 01:07 UTC
