### ISSUE TITLE
How to apply customMapStyle without losing all places / sightseeing spots (shops, restourants etc..)?

### ISSUE THREAD

**Issue by AntonioErdeljac** [react-community/react-native-maps#1857] opened 2017-12-06 17:56 UTC
When applying `customMapStyle` property to` <MapView />` compoent with only `[{"stylers":[{"hue": "#1fcf7c"}]}]` applied all spots are disabled.

**Comment by alvelig** [comment] 2017-12-13 01:33
duplicate of #1535

**Closed by alvelig** 2017-12-13 01:33 UTC
