### ISSUE TITLE
showsMyLocationButton,showsScale property not working

### ISSUE THREAD

**Issue by Rashhh** [react-community/react-native-maps#691] opened 2016-10-13 13:14 UTC
```
   <MapView
     style={styles.map}
    onPress={(e) => this.onMapPress(e)}
   provider="google"
     zoomEnabled={true}
      scrollEnabled={true}
      showsScale={true}
      mapType='satellite'
      showsMyLocationButton={true}
      showsScale={true}
      showsCompass={true}
      loadingIndicatorColor="#228B22"
     onRegionChange={()=>this.onRegionChange()}
     region={this.state.region}
   >
   </MapView>
```

**Comment by barrilocho** [comment] 2016-10-18 01:13
Same :( 
Any solution?

**Comment by voidale** [comment] 2016-10-28 09:07
same case `showsMyLocationButton` has no effect, should it put something on the map?

**Comment by JonoH** [comment] 2016-11-02 12:00
Yeah none of the toolBar control properties seem to work my side either.

**Comment by pewh** [comment] 2016-12-06 16:15
+1 Same issue

**Comment by lucianomlima** [comment] 2016-12-07 01:48
+1

**Comment by gilbox** [comment] 2016-12-07 08:26
`showsMyLocationButton` is not implemented for google provider on iOS. You're welcome to make a PR to add the feature.

**Comment by JonoH** [comment] 2016-12-07 09:16
@gilbox they aren't working on Android either.

**Comment by win45** [comment] 2016-12-17 09:36
**on Android:** This is a stretch, but make sure the `showsMyLocationButton` isn't caught behind an overlaying element i.e. navigationBar. Also, the event wasn't working on my emulator for whatever reason, but worked on a device.

**Comment by psam44** [comment] 2017-03-06 21:10
For the button to be visible you must set `showsUserLocation={true}` because the default is `false`.
Afterwards, please follow the issue on #1033.

**Comment by alvelig** [comment] 2017-12-14 04:10
Duplicate of #1033

**Closed** 2017-12-14 04:09 UTC
Labels: enhancement, help wanted
